#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  xkb_0_1_0 = buildCratesLib {
    name = "xkb";
    version = "0.1.0";
    hash = "7dd0f3bda662c16f5fc24ed423863209e5621c69525776cfb9b071f787c15424";
    deps = with allCrates; [  all__xkbcommon-sys.xkbcommon-sys_0_7 all__libc.libc_0_2 all__bitflags.bitflags_0_7 ];
  };
  xkb_0_1_1 = buildCratesLib {
    name = "xkb";
    version = "0.1.1";
    hash = "962ff4c85eda2c4fb44b62836069146e422597c6802fb3cf7c5b94db65098e0d";
    deps = with allCrates; [  all__bitflags.bitflags_0_7 all__xkbcommon-sys.xkbcommon-sys_0_7 all__libc.libc_0_2 ];
  };
  "xkb_0_1" = xkb_0_1_1;
  "xkb_0" = xkb_0_1_1;}