#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  event-emitter_0_0_1 = buildCratesLib {
    name = "event-emitter";
    version = "0.0.1";
    hash = "5d523424584621847acb03ee745f89c1692f46ed3c2a731569c69e9f55a4f4c4";
    deps = with allCrates; [  forever uuid event typemap unsafe-any ];
  };
  "event-emitter_0_0" = event-emitter_0_0_1;
  "event-emitter_0" = event-emitter_0_0_1;}