#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  fswatch-sys_0_1_0 = buildCratesLib {
    name = "fswatch-sys";
    version = "0.1.0";
    hash = "4f4d29d05f88e766d277052daf0ef15734d359ac0e2907dca8766b1e16b4df10";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  fswatch-sys_0_1_1 = buildCratesLib {
    name = "fswatch-sys";
    version = "0.1.1";
    hash = "0a63fc7b91345a3c574a6d895acc7ddcd67a6bf2c190e82961097120c559c638";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  fswatch-sys_0_1_2 = buildCratesLib {
    name = "fswatch-sys";
    version = "0.1.2";
    hash = "f663ba5f40bdcf2dab786a964fbf8f8d2d0cb741f54c654c719d11cc61e6600f";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  fswatch-sys_0_1_3 = buildCratesLib {
    name = "fswatch-sys";
    version = "0.1.3";
    hash = "7c60683011bb870892e676dce10b54afefc211f72eb23fabb37fa6397b6c9274";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  fswatch-sys_0_1_4 = buildCratesLib {
    name = "fswatch-sys";
    version = "0.1.4";
    hash = "d539e3597592f27508272c6aa2858d5f7bd85c578ebcc1cb94d1313baa4a4792";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  "fswatch-sys_0_1" = fswatch-sys_0_1_4;
  "fswatch-sys_0" = fswatch-sys_0_1_4;}