#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  positioned-io_0_1_0 = buildCratesLib {
    name = "positioned-io";
    version = "0.1.0";
    hash = "4358f11ed9c41fa93e4403823c83955f6824e1aabc4d20f44dc6b5dd3cf04e52";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 all__nix.nix_0_6 ];
  };
  positioned-io_0_2_0 = buildCratesLib {
    name = "positioned-io";
    version = "0.2.0";
    hash = "6802916551e67f35cd14bdb4c9c1c772e1f79fdeef722cb5ed1f44f5099e9e1f";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 all__nix.nix_0_6 ];
  };
  "positioned-io_0_1" = positioned-io_0_1_0;
  positioned-io_0_2_1 = buildCratesLib {
    name = "positioned-io";
    version = "0.2.1";
    hash = "f10ebdd76fb93931b8970e75d79c440773a0aae63d075f72365bebdcde6845d5";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 all__libc.libc_0_2 ];
  };
  positioned-io_0_2_2 = buildCratesLib {
    name = "positioned-io";
    version = "0.2.2";
    hash = "c405a565f48a728dbb07fa1770e30791b0fa3e6344c1e5615225ce84049354d6";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 all__libc.libc_0_2 ];
  };
  "positioned-io_0_2" = positioned-io_0_2_2;
  "positioned-io_0" = positioned-io_0_2_2;}