#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ruma-client-api_0_0_0 = buildCratesLib {
    name = "ruma-client-api";
    version = "0.0.0";
    hash = "9a41258bde0fcc1a4b50fd87503dadecc9ad2a2e8c430591e9ccd37038a209e6";
    deps = with allCrates; [  ];
  };
  "ruma-client-api_0_0" = ruma-client-api_0_0_0;
  "ruma-client-api_0" = ruma-client-api_0_0_0;}