#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ruma-federation_0_0_0 = buildCratesLib {
    name = "ruma-federation";
    version = "0.0.0";
    hash = "55a031fba0bd0f9f80a769222e23c444d003dc535280a789cf0cef2a943500cd";
    deps = with allCrates; [  ];
  };
  "ruma-federation_0_0" = ruma-federation_0_0_0;
  "ruma-federation_0" = ruma-federation_0_0_0;}