#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  golang_0_1_0 = buildCratesLib {
    name = "golang";
    version = "0.1.0";
    hash = "5517b48353473e01cba2d4e20681eb89413f7a627103528564b039a05d14c346";
    deps = with allCrates; [  ];
  };
  golang_0_1_1 = buildCratesLib {
    name = "golang";
    version = "0.1.1";
    hash = "6f2efce676589661eb14a82c56325d99ae4b4dc034ca0b9e2f8bb18b79b287ae";
    deps = with allCrates; [  ];
  };
  "golang_0_1" = golang_0_1_1;
  "golang_0" = golang_0_1_1;}