#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cast5_0_0_0 = buildCratesLib {
    name = "cast5";
    version = "0.0.0";
    hash = "1db08f6bc2e6a0bc3b7fdb89bc3fee5010a27a8bcc8c7b8e8ec7626488f68339";
    deps = with allCrates; [  ];
  };
  "cast5_0_0" = cast5_0_0_0;
  "cast5_0" = cast5_0_0_0;}