#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ess_0_3_1 = buildCratesLib {
    name = "ess";
    version = "0.3.1";
    hash = "f266926a8bbfe61027c0c3a8431ca5fa33b5d1e316ad427a2ea2abe77034bded";
    deps = with allCrates; [  ];
  };
  ess_0_4_0 = buildCratesLib {
    name = "ess";
    version = "0.4.0";
    hash = "48f4e6a0b178821e1592888fdc9628585008940512fc0d2d0101b2a90d0f9e9d";
    deps = with allCrates; [  ];
  };
  "ess_0_3" = ess_0_3_1;
  "ess_0_4" = ess_0_4_0;
  "ess_0" = ess_0_4_0;}