#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  fountain_codes_0_1_0 = buildCratesLib {
    name = "fountain_codes";
    version = "0.1.0";
    hash = "9cd9605f4568b8ad930b4821faa87762e3be6bde814cb85bde23e1f54f013eba";
    deps = with allCrates; [  all__rand.rand_0_3 ];
  };
  "fountain_codes_0_1" = fountain_codes_0_1_0;
  "fountain_codes_0" = fountain_codes_0_1_0;}