#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  migrant_0_1_0 = buildCratesLib {
    name = "migrant";
    version = "0.1.0";
    hash = "387b17970ecd94366290018259392012dbfeaa4d4d6c39771be44b538579a09b";
    deps = with allCrates; [  all__chrono.chrono_0_2 all__rpassword.rpassword_0_3 clap all__rustc-serialize.rustc-serialize_0_3 all__walkdir.walkdir_1 all__error-chain.error-chain_0_7 ];
  };
  "migrant_0_1" = migrant_0_1_0;
  "migrant_0" = migrant_0_1_0;}