#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  wolfram_alpha_0_1_0 = buildCratesLib {
    name = "wolfram_alpha";
    version = "0.1.0";
    hash = "5a6e13ca764b5bceb0761412f604395d9804509a815fd7d3d44779525ad76621";
    deps = with allCrates; [  all__serde.serde_0_7 all__log.log_0_3 all__serde_xml.serde_xml_0_7 all__url.url_1_1 ];
  };
  wolfram_alpha_0_1_1 = buildCratesLib {
    name = "wolfram_alpha";
    version = "0.1.1";
    hash = "2d5977a93bd5bbb21dbcf4c9f8ab52e33bce19a5ab044a7cb33133c2d2189956";
    deps = with allCrates; [  all__serde.serde_0_8 all__url.url_1_1 all__log.log_0_3 all__serde_xml.serde_xml_0_8 ];
  };
  wolfram_alpha_0_2_0 = buildCratesLib {
    name = "wolfram_alpha";
    version = "0.2.0";
    hash = "2f9c75205c3da66da46b4217c2852bf71d646c35bf19db81ff998795a25d15cb";
    deps = with allCrates; [  all__serde.serde_0_8 all__url.url_1_1 all__log.log_0_3 all__serde_xml.serde_xml_0_8 ];
  };
  "wolfram_alpha_0_1" = wolfram_alpha_0_1_1;
  wolfram_alpha_0_2_1 = buildCratesLib {
    name = "wolfram_alpha";
    version = "0.2.1";
    hash = "18eab4279b2e98f9e68f75fb27c631655f14ba84063321400cf5f0ab0801f2b1";
    deps = with allCrates; [  all__serde_xml.serde_xml_0_8 all__url.url_1_1 all__serde.serde_0_8 all__log.log_0_3 ];
  };
  wolfram_alpha_0_3_0 = buildCratesLib {
    name = "wolfram_alpha";
    version = "0.3.0";
    hash = "1627a5d00bfff3f102146ff132fad0c982bbdadb62d63eb91c68f72766d190a2";
    deps = with allCrates; [  all__log.log_0_3 all__url.url_1_1 all__serde.serde_0_8 all__serde_xml.serde_xml_0_8 ];
  };
  "wolfram_alpha_0_2" = wolfram_alpha_0_2_1;
  "wolfram_alpha_0_3" = wolfram_alpha_0_3_0;
  "wolfram_alpha_0" = wolfram_alpha_0_3_0;}