#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  vulkanology_0_1_0 = buildCratesLib {
    name = "vulkanology";
    version = "0.1.0";
    hash = "624b47f4b38ef5b88baf15e4a742288023b212b7eecb9d8cb50075c85f580c0f";
    deps = with allCrates; [  all__rand.rand_0_3 all__vulkano.vulkano_0_3 all__vulkano-shaders.vulkano-shaders_0_3 ];
  };
  "vulkanology_0_1" = vulkanology_0_1_0;
  "vulkanology_0" = vulkanology_0_1_0;}