#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  block-cipher-trait_0_1_0 = buildCratesLib {
    name = "block-cipher-trait";
    version = "0.1.0";
    hash = "aa2f119d25c9ad6a9515b7bcefaed8e8bad42d3118da768b617eb131181a7f5d";
    deps = with allCrates; [  all__generic-array.generic-array_0_5 ];
  };
  block-cipher-trait_0_2_0 = buildCratesLib {
    name = "block-cipher-trait";
    version = "0.2.0";
    hash = "41a08485030995580831d8887edade5c8ffbd0db512f33d776056fc8ebeac2e0";
    deps = with allCrates; [  all__generic-array.generic-array_0_5 ];
  };
  "block-cipher-trait_0_1" = block-cipher-trait_0_1_0;
  block-cipher-trait_0_3_0 = buildCratesLib {
    name = "block-cipher-trait";
    version = "0.3.0";
    hash = "a1dc8a6d88bfdefdd3c27d35f53e882dfff58d64caa21f14e759b27a99397c8f";
    deps = with allCrates; [  all__generic-array.generic-array_0_6 ];
  };
  "block-cipher-trait_0_2" = block-cipher-trait_0_2_0;
  "block-cipher-trait_0_3" = block-cipher-trait_0_3_0;
  "block-cipher-trait_0" = block-cipher-trait_0_3_0;}