#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  curl-easybuilder_0_1_0 = buildCratesLib {
    name = "curl-easybuilder";
    version = "0.1.0";
    hash = "9140765295f0f8695c6ee163b399ed9b25b0d0fb524515eb5562e9c683260940";
    deps = with allCrates; [  all__curl.curl_0_4 all__error-chain.error-chain_0_7 ];
  };
  "curl-easybuilder_0_1" = curl-easybuilder_0_1_0;
  "curl-easybuilder_0" = curl-easybuilder_0_1_0;}