#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  raster_0_0_1 = buildCratesLib {
    name = "raster";
    version = "0.0.1";
    hash = "208eba348186a49e980366cc0f22629f4bb76b532fa0a8ebda205ca50414994d";
    deps = with allCrates; [  all__image.image_0_10 ];
  };
  raster_0_0_2 = buildCratesLib {
    name = "raster";
    version = "0.0.2";
    hash = "cad8c5eaa91ddb3aad48ef6f1d45b3ae4f02489e17dd832461e13a08dea6b4d3";
    deps = with allCrates; [  all__image.image_0_10 ];
  };
  raster_0_0_3 = buildCratesLib {
    name = "raster";
    version = "0.0.3";
    hash = "cd514a8ac98678825273acfbc48816c4c6f1dd6129b096a3f16cea78a326b1a7";
    deps = with allCrates; [  all__image.image_0_10 ];
  };
  raster_0_0_4 = buildCratesLib {
    name = "raster";
    version = "0.0.4";
    hash = "52c07a33bae01d48e6abca171f5763860812e6056d29ec2839bf7ed389f22d68";
    deps = with allCrates; [  all__image.image_0_10 ];
  };
  raster_0_0_5 = buildCratesLib {
    name = "raster";
    version = "0.0.5";
    hash = "24b9b7e819c54dc7f81e7e7a2dfa7ba62a1724c1a25c590c6aa4449d4f2915f3";
    deps = with allCrates; [  all__image.image_0_10 ];
  };
  raster_0_0_6 = buildCratesLib {
    name = "raster";
    version = "0.0.6";
    hash = "7c269b2fec1427f680e38e2644fed0116aa538aae43b57ef1a5b4698a6db4af3";
    deps = with allCrates; [  all__image.image_0_10 ];
  };
  raster_0_0_7 = buildCratesLib {
    name = "raster";
    version = "0.0.7";
    hash = "9f7a3b806626f5b0f10b662c611ec47ed95970bf5514ccbe881280c7f5a58a9d";
    deps = with allCrates; [  all__image.image_0_10 ];
  };
  raster_0_0_8 = buildCratesLib {
    name = "raster";
    version = "0.0.8";
    hash = "d8fdde65b0269ef8cb42d8b304f303aad64276073e5eb230940f700f1b6d2c73";
    deps = with allCrates; [  all__image.image_0_10 ];
  };
  raster_0_1_0 = buildCratesLib {
    name = "raster";
    version = "0.1.0";
    hash = "d4ca25494fbb7cad5a428c36b3d68d6e3e92da59b7b26226489942673b8c3c99";
    deps = with allCrates; [  all__image.image_0_10 ];
  };
  "raster_0_0" = raster_0_0_8;
  raster_0_2_0 = buildCratesLib {
    name = "raster";
    version = "0.2.0";
    hash = "4c3f9e9cfa4260e25ea0d3bc72f3724afbeb65a61f8cb4d38c1d4de5309cd7ef";
    deps = with allCrates; [  all__png.png_0_5 all__gif.gif_0_9 all__image.image_0_10 ];
  };
  "raster_0_1" = raster_0_1_0;
  "raster_0_2" = raster_0_2_0;
  "raster_0" = raster_0_2_0;}