#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  huffman-coding_0_1_0 = buildCratesLib {
    name = "huffman-coding";
    version = "0.1.0";
    hash = "3c8738b57ff2bb63fba61f371fd893595e60404073c159fcf6c606c664b4e1cf";
    deps = with allCrates; [  all__bitstream-rs.bitstream-rs_0_1 all__bit-vec.bit-vec_0_4 ];
  };
  huffman-coding_0_1_1 = buildCratesLib {
    name = "huffman-coding";
    version = "0.1.1";
    hash = "aacb6076007715dc29ebedfd60cf5e9a178fabc0eab707caa8e8a3471428ce07";
    deps = with allCrates; [  all__bitstream-rs.bitstream-rs_0_1 all__bit-vec.bit-vec_0_4 ];
  };
  huffman-coding_0_1_2 = buildCratesLib {
    name = "huffman-coding";
    version = "0.1.2";
    hash = "bd43974ad95725c17acfb87d4244c6f2eadec51262e7d200695582af7cd3c4cd";
    deps = with allCrates; [  all__bitstream-rs.bitstream-rs_0_1 all__bit-vec.bit-vec_0_4 ];
  };
  "huffman-coding_0_1" = huffman-coding_0_1_2;
  "huffman-coding_0" = huffman-coding_0_1_2;}