#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cdrs_0_1_0 = buildCratesLib {
    name = "cdrs";
    version = "0.1.0";
    hash = "0de66b327c5a8c24d32ac5acaa05aa93e069468f24718ad69d7c1e35eee9dbfd";
    deps = with allCrates; [  all__log.log_0_3 all__lz4-compress.lz4-compress_0_1 all__uuid.uuid_0_2 all__byteorder.byteorder_0_5 all__snap.snap_0_1 ];
  };
  cdrs_0_2_0 = buildCratesLib {
    name = "cdrs";
    version = "0.2.0";
    hash = "7b43fa4ade1a34b8fb9c6ba773c028a07087b715c5f44d1074139753c8c4d857";
    deps = with allCrates; [  all__log.log_0_3 all__snap.snap_0_1 all__byteorder.byteorder_0_5 all__uuid.uuid_0_2 all__lz4-compress.lz4-compress_0_1 ];
  };
  "cdrs_0_1" = cdrs_0_1_0;
  cdrs_0_3_0 = buildCratesLib {
    name = "cdrs";
    version = "0.3.0";
    hash = "6713c9115dfc15f3082bcd41e4a18575d6adcb31b96eff59fdfcdebdd396c211";
    deps = with allCrates; [  all__uuid.uuid_0_2 all__lz4-compress.lz4-compress_0_1 all__byteorder.byteorder_0_5 all__log.log_0_3 all__snap.snap_0_1 ];
  };
  "cdrs_0_2" = cdrs_0_2_0;
  cdrs_0_4_0 = buildCratesLib {
    name = "cdrs";
    version = "0.4.0";
    hash = "b56e30c1162a8c97fb5fa0f3296d27d6d5af5798c379d4ab9b18e7e9a9142359";
    deps = with allCrates; [  all__uuid.uuid_0_2 all__log.log_0_3 all__snap.snap_0_1 all__byteorder.byteorder_0_5 all__lz4-compress.lz4-compress_0_1 ];
  };
  "cdrs_0_3" = cdrs_0_3_0;
  cdrs_0_4_1 = buildCratesLib {
    name = "cdrs";
    version = "0.4.1";
    hash = "e54c98d407e25bd14bc0095486c6af4a3776331342102f79503223bcc43f96a1";
    deps = with allCrates; [  all__snap.snap_0_1 all__byteorder.byteorder_0_5 all__log.log_0_3 all__lz4-compress.lz4-compress_0_1 all__uuid.uuid_0_2 ];
  };
  cdrs_0_5_0 = buildCratesLib {
    name = "cdrs";
    version = "0.5.0";
    hash = "da5c89e34effe3f404bac345d611ac780fd64049d3888c333138f4abf11d9406";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 all__log.log_0_3 all__snap.snap_0_1 all__uuid.uuid_0_2 all__lz4-compress.lz4-compress_0_1 ];
  };
  "cdrs_0_4" = cdrs_0_4_1;
  cdrs_0_6_0 = buildCratesLib {
    name = "cdrs";
    version = "0.6.0";
    hash = "5decd76b799214eca33527c53812c194d20e5fad3075e5872b646ae05bef01d3";
    deps = with allCrates; [  all__log.log_0_3 all__snap.snap_0_1 all__byteorder.byteorder_0_5 all__uuid.uuid_0_2 all__lz4-compress.lz4-compress_0_1 ];
  };
  "cdrs_0_5" = cdrs_0_5_0;
  "cdrs_0_6" = cdrs_0_6_0;
  "cdrs_0" = cdrs_0_6_0;}