#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tablegen_0_1_0 = buildCratesLib {
    name = "tablegen";
    version = "0.1.0";
    hash = "70202bacec4894200c4acef5d7503982b073548d03d733c700ba3be68a3d798e";
    deps = with allCrates; [  all__cmake.cmake_0_1 ];
  };
  "tablegen_0_1" = tablegen_0_1_0;
  "tablegen_0" = tablegen_0_1_0;}