#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cargo-doc-coverage_0_1_0 = buildCratesLib {
    name = "cargo-doc-coverage";
    version = "0.1.0";
    hash = "f01831d8193fcd7bb6e17c3de7ab09b9b5f86971faa5f01272e59824d33a40d6";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__matches.matches_0_1 ];
  };
  cargo-doc-coverage_1_0_0 = buildCratesLib {
    name = "cargo-doc-coverage";
    version = "1.0.0";
    hash = "ceb2563636487b95988c3092368073d31bbbdac01c06852d186fe74d8e514561";
    deps = with allCrates; [  all__matches.matches_0_1 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "cargo-doc-coverage_0_1" = cargo-doc-coverage_0_1_0;
  "cargo-doc-coverage_0" = cargo-doc-coverage_0_1_0;
  "cargo-doc-coverage_1_0" = cargo-doc-coverage_1_0_0;
  "cargo-doc-coverage_1" = cargo-doc-coverage_1_0_0;}