#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  act_0_1_0 = buildCratesLib {
    name = "act";
    version = "0.1.0";
    hash = "e77f3b77aa740ba84f5b95cd86a2ebc1929585a81f3d93f75ba23a427b9149d4";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__ansi-escapes.ansi-escapes_0_1 ];
  };
  act_0_1_1 = buildCratesLib {
    name = "act";
    version = "0.1.1";
    hash = "cfe6f2e07093a6b7720b85ff92109b622c01a0f46feb4f84d7bd266595b38630";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__ansi-escapes.ansi-escapes_0_1 ];
  };
  "act_0_1" = act_0_1_1;
  "act_0" = act_0_1_1;}