#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  anl_0_1_0 = buildCratesLib {
    name = "anl";
    version = "0.1.0";
    hash = "3bf9dbe5a0c316bff389e2969ce1667b5f30bfb306a7c92b3588ec62095a3355";
    deps = with allCrates; [  all__time.time_0_1 all__lazy_static.lazy_static_0_2 ];
  };
  "anl_0_1" = anl_0_1_0;
  "anl_0" = anl_0_1_0;}