#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rucaja_0_1_0 = buildCratesLib {
    name = "rucaja";
    version = "0.1.0";
    hash = "6d499464c22866c2ceeecd30f5b47cb9ae51f0aa538fb7e6c7c2489e04856950";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_1 = buildCratesLib {
    name = "rucaja";
    version = "0.1.1";
    hash = "82cfb49d1a45a186998b7cda163b221432d9c64e49c2ac079ab58bd7b1994953";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_2 = buildCratesLib {
    name = "rucaja";
    version = "0.1.2";
    hash = "5cefccceb3e662f1996c9368413be0a14bbec3752409abbd7a0e8dd909149d83";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_3 = buildCratesLib {
    name = "rucaja";
    version = "0.1.3";
    hash = "b0a4a1d4756af15e9df2af35809b65f7e2c5eb547fd8276622461a33a48a5344";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_4 = buildCratesLib {
    name = "rucaja";
    version = "0.1.4";
    hash = "bd3020bd22b3bb0a28bd0e611f95829eea23ea5f0d7296d41ff1901cd7a37160";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  "rucaja_0_1" = rucaja_0_1_4;
  "rucaja_0" = rucaja_0_1_4;}