#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rucaja_0_1_0 = buildCratesLib {
    name = "rucaja";
    version = "0.1.0";
    hash = "6d499464c22866c2ceeecd30f5b47cb9ae51f0aa538fb7e6c7c2489e04856950";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_1 = buildCratesLib {
    name = "rucaja";
    version = "0.1.1";
    hash = "82cfb49d1a45a186998b7cda163b221432d9c64e49c2ac079ab58bd7b1994953";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_2 = buildCratesLib {
    name = "rucaja";
    version = "0.1.2";
    hash = "5cefccceb3e662f1996c9368413be0a14bbec3752409abbd7a0e8dd909149d83";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_3 = buildCratesLib {
    name = "rucaja";
    version = "0.1.3";
    hash = "b0a4a1d4756af15e9df2af35809b65f7e2c5eb547fd8276622461a33a48a5344";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_4 = buildCratesLib {
    name = "rucaja";
    version = "0.1.4";
    hash = "bd3020bd22b3bb0a28bd0e611f95829eea23ea5f0d7296d41ff1901cd7a37160";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_5 = buildCratesLib {
    name = "rucaja";
    version = "0.1.5";
    hash = "329841091e777a15caa4aa1b4e462e637a19cd8a58d2644e6f8e4fd01608cece";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_6 = buildCratesLib {
    name = "rucaja";
    version = "0.1.6";
    hash = "7189edd9e065eaca89b2e9b063ad81c53b4c6a43c8c53113b765b61773310fa0";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_7 = buildCratesLib {
    name = "rucaja";
    version = "0.1.7";
    hash = "973af1a9150d0d6af60dacf430bd1aa7fcfb581b8a362cd514d9852148170598";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_8 = buildCratesLib {
    name = "rucaja";
    version = "0.1.8";
    hash = "1e5575344df30f8ef1d4e56130d0dfb6987d6ce3cb782231f6efcaa2f3771d23";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_1_9 = buildCratesLib {
    name = "rucaja";
    version = "0.1.9";
    hash = "e8eb29fdb48eb82f8f23c83878a79274e82972cf56b15d89c18e1b6daa3a9b58";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  rucaja_0_2_0 = buildCratesLib {
    name = "rucaja";
    version = "0.2.0";
    hash = "96cfe47e0ccf10b018cdc2031b09e6d9e88a24f86a43a8bb4534889360f6d85f";
    deps = with allCrates; [  all__jni-sys.jni-sys_0_2 ];
  };
  "rucaja_0_1" = rucaja_0_1_9;
  "rucaja_0_2" = rucaja_0_2_0;
  "rucaja_0" = rucaja_0_2_0;}