#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cross_0_1_0 = buildCratesLib {
    name = "cross";
    version = "0.1.0";
    hash = "2049479fdd2a71767534a4358fc5fe90ce1baf51352713300d3d5376f918d1e0";
    deps = with allCrates; [  all__libc.libc_0_2 all__rustc_version.rustc_version_0_1 all__error-chain.error-chain_0_7 ];
  };
  cross_0_1_1 = buildCratesLib {
    name = "cross";
    version = "0.1.1";
    hash = "c2b3ef2b5671ae9e00066dd46bf1e624193f656e69b870437cd57cab5f76cfef";
    deps = with allCrates; [  all__error-chain.error-chain_0_7 all__libc.libc_0_2 all__rustc_version.rustc_version_0_1 ];
  };
  "cross_0_1" = cross_0_1_1;
  "cross_0" = cross_0_1_1;}