#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  httprequestsdemo_0_1_0 = buildCratesLib {
    name = "httprequestsdemo";
    version = "0.1.0";
    hash = "6dd355925906890ee6294fc0b6e2f26b6eaf020f1d3e63c991096f3a92837b3d";
    deps = with allCrates; [  all__hyper.hyper_0_9 ];
  };
  "httprequestsdemo_0_1" = httprequestsdemo_0_1_0;
  "httprequestsdemo_0" = httprequestsdemo_0_1_0;}