#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  httpbis_0_1_1 = buildCratesLib {
    name = "httpbis";
    version = "0.1.1";
    hash = "4ec15ac25b40038c76fbe61f77731ab0455b80555f99065d5cd98bea7bbdc82d";
    deps = with allCrates; [  all__hpack.hpack_0_3 futures-cpupool tokio-tls tokio-core log futures ];
  };
  "httpbis_0_1" = httpbis_0_1_1;
  "httpbis_0" = httpbis_0_1_1;}