#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  union-future_0_1_0 = buildCratesLib {
    name = "union-future";
    version = "0.1.0";
    hash = "2511fd872a6b90baddd077ac18a4d5ba075454122a29527d531f3ddea43eabf5";
    deps = with allCrates; [  all__futures.futures_0_1 ];
  };
  union-future_0_1_1 = buildCratesLib {
    name = "union-future";
    version = "0.1.1";
    hash = "a8977af6af881c3d99de38bb274b03fd4340e1f0d4635a5e642402a24e84339d";
    deps = with allCrates; [  all__futures.futures_0_1 ];
  };
  "union-future_0_1" = union-future_0_1_1;
  "union-future_0" = union-future_0_1_1;}