#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  reroute_0_1_0 = buildCratesLib {
    name = "reroute";
    version = "0.1.0";
    hash = "ccdb2d02b437bee6593287ee59ab7da0b64b601f3582348c9f0b4183404ed33a";
    deps = with allCrates; [  all__regex.regex_0_1 all__hyper.hyper_0_8 ];
  };
  reroute_0_1_1 = buildCratesLib {
    name = "reroute";
    version = "0.1.1";
    hash = "3823d58df385d26f41e7c06658c55e62a01c47095678c93d01db7fde66275e80";
    deps = with allCrates; [  all__hyper.hyper_0_8 all__regex.regex_0_1 ];
  };
  reroute_0_1_2 = buildCratesLib {
    name = "reroute";
    version = "0.1.2";
    hash = "e8e82d5bf281985fd5e33d646a8e5216ed18791cef674beb2e04be5b798a0082";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__regex.regex_0_1 ];
  };
  reroute_0_2_0 = buildCratesLib {
    name = "reroute";
    version = "0.2.0";
    hash = "0540ebbd22367a11550275c6e9b31ce8b96d4118cb11237386aab15ea331e126";
    deps = with allCrates; [  all__regex.regex_0_1 all__hyper.hyper_0_9 ];
  };
  "reroute_0_1" = reroute_0_1_2;
  reroute_0_2_1 = buildCratesLib {
    name = "reroute";
    version = "0.2.1";
    hash = "2da3401b745f17bf5cec70edede12d9d6e15690615ee9ad3559ab9b7352e7f66";
    deps = with allCrates; [  all__regex.regex_0_1 all__hyper.hyper_0_9 ];
  };
  reroute_0_2_2 = buildCratesLib {
    name = "reroute";
    version = "0.2.2";
    hash = "21e6361c1699ba80e23fcef47fe9c1d8b2c248ed462f0f736f7b99a5aed40354";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__regex.regex_0_1 ];
  };
  reroute_0_2_3 = buildCratesLib {
    name = "reroute";
    version = "0.2.3";
    hash = "84733f53e4aa1d15c73c1c289817671dbf81891cf6ea3e16fa8dce5eec379533";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__regex.regex_0_1 ];
  };
  reroute_0_2_4 = buildCratesLib {
    name = "reroute";
    version = "0.2.4";
    hash = "defd5950794fc798d3c010ec75ce40e12e4e22c8219b4e002b5f4f7373d7322e";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__regex.regex_0_1 ];
  };
  reroute_0_3_0 = buildCratesLib {
    name = "reroute";
    version = "0.3.0";
    hash = "f9a06555566e73926d2e132190ca709e924fbfdfad2aa6a3020fba0d599e7949";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__regex.regex_0_1 ];
  };
  "reroute_0_2" = reroute_0_2_4;
  reroute_0_3_1 = buildCratesLib {
    name = "reroute";
    version = "0.3.1";
    hash = "841fb8c3f48953f3e84c2aef7f430aacd37c08a17382572a6d006b1c5161869f";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__regex.regex_0_2 ];
  };
  reroute_0_3_2 = buildCratesLib {
    name = "reroute";
    version = "0.3.2";
    hash = "60e74d10c2baf37be4ded4c6f24fdc385f71fc6f1259f668ec5750f38897adfd";
    deps = with allCrates; [  all__regex.regex_0_2 all__hyper.hyper_0_10 ];
  };
  "reroute_0_3" = reroute_0_3_2;
  "reroute_0" = reroute_0_3_2;}