#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  same-file_0_1_0 = buildCratesLib {
    name = "same-file";
    version = "0.1.0";
    hash = "3ae91cd5ff84da895a4a0b953b3e9dc121613d915fa1e6275bcd9d5a556647c3";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  same-file_0_1_1 = buildCratesLib {
    name = "same-file";
    version = "0.1.1";
    hash = "05f5dc7680f4bdc74fa0df5f32fcbaf1174a92e65bf3d69e0288248604306875";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  "same-file_0_1" = same-file_0_1_1;
  "same-file_0" = same-file_0_1_1;}