#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  intecture-api_0_3_0 = buildCratesLib {
    name = "intecture-api";
    version = "0.3.0";
    hash = "d66aedb947fd266534860fe086d948a4904240db379c2b345a26fb4960d9f06d";
    deps = with allCrates; [  all__zdaemon.zdaemon_0_0_2 all__rustc-serialize.rustc-serialize_0_3 all__serde_json.serde_json_0_8 all__libc.libc_0_2 all__regex.regex_0_1 all__zfilexfer.zfilexfer_0_0_2 all__lazy_static.lazy_static_0_2 all__mustache.mustache_0_8 all__tempfile.tempfile_2_1 all__serde.serde_0_8 ];
  };
  "intecture-api_0_3" = intecture-api_0_3_0;
  "intecture-api_0" = intecture-api_0_3_0;}