#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  conio_0_1_0 = buildCratesLib {
    name = "conio";
    version = "0.1.0";
    hash = "71937768f09545f1fb45f1d625513d105bc08c7840384047893cf5e4f1b79a68";
    deps = with allCrates; [  ];
  };
  "conio_0_1" = conio_0_1_0;
  "conio_0" = conio_0_1_0;}