#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rs6502_0_1_0 = buildCratesLib {
    name = "rs6502";
    version = "0.1.0";
    hash = "8ca82d061870d5750778184dd538fcaa6ea598b9d4df1fa5a8a2b127c8c3913d";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 ];
  };
  "rs6502_0_1" = rs6502_0_1_0;
  "rs6502_0" = rs6502_0_1_0;}