#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  dmsort_0_1_0 = buildCratesLib {
    name = "dmsort";
    version = "0.1.0";
    hash = "262f7c4737b46fec6c080a8cec98f7dcec26efeb757f3f9a4210dd9049593ebc";
    deps = with allCrates; [  ];
  };
  dmsort_0_1_1 = buildCratesLib {
    name = "dmsort";
    version = "0.1.1";
    hash = "a9e0a37fa01dc7d022d11d99416be948c5ef93bdae19801d7d984741fb8cd17f";
    deps = with allCrates; [  ];
  };
  "dmsort_0_1" = dmsort_0_1_1;
  "dmsort_0" = dmsort_0_1_1;}