#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cpp_to_rust_build_tools_0_0_0 = buildCratesLib {
    name = "cpp_to_rust_build_tools";
    version = "0.0.0";
    hash = "73648f7fa4ecf6f767b536c1cc07a72974dfcba686aee2ebac0bb8647fb04831";
    deps = with allCrates; [  all__cpp_to_rust_common.cpp_to_rust_common_0_0 ];
  };
  cpp_to_rust_build_tools_0_1_0 = buildCratesLib {
    name = "cpp_to_rust_build_tools";
    version = "0.1.0";
    hash = "dea91c747636c9d4098d512c90963da441c965eafeed5e8f00e6c9e5b7125b59";
    deps = with allCrates; [  all__cpp_to_rust_common.cpp_to_rust_common_0_0 ];
  };
  "cpp_to_rust_build_tools_0_0" = cpp_to_rust_build_tools_0_0_0;
  "cpp_to_rust_build_tools_0_1" = cpp_to_rust_build_tools_0_1_0;
  "cpp_to_rust_build_tools_0" = cpp_to_rust_build_tools_0_1_0;}