#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cpp_to_rust_common_0_0_0 = buildCratesLib {
    name = "cpp_to_rust_common";
    version = "0.0.0";
    hash = "544a3bb9c64f1c358cf75c5b41d1739eb74e70908e63efb6274db170c7ac8b82";
    deps = with allCrates; [  all__error-chain.error-chain_0_5 all__num_cpus.num_cpus_1_0_0 all__backtrace.backtrace_0_2 all__ansi_term.ansi_term_0_7 all__regex.regex_0_1 all__serde_json.serde_json_0_8 all__serde.serde_0_8 ];
  };
  "cpp_to_rust_common_0_0" = cpp_to_rust_common_0_0_0;
  "cpp_to_rust_common_0" = cpp_to_rust_common_0_0_0;}