#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  crates-api_0_1_0 = buildCratesLib {
    name = "crates-api";
    version = "0.1.0";
    hash = "e8957368999084633f42439b4f5e296a2985db6bf3a100f148b00b0b1a4c4965";
    deps = with allCrates; [  all__serde.serde_0_8 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__serde_derive.serde_derive_0_8 ];
  };
  "crates-api_0_1" = crates-api_0_1_0;
  "crates-api_0" = crates-api_0_1_0;}