#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  managed_0_0_0 = buildCratesLib {
    name = "managed";
    version = "0.0.0";
    hash = "2756de0fbab723fa5e9c3da9e8b84c5e8a510034433a9c42ae251c9c524ec0a0";
    deps = with allCrates; [  ];
  };
  "managed_0_0" = managed_0_0_0;
  "managed_0" = managed_0_0_0;}