#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  fsb_0_0_0 = buildCratesLib {
    name = "fsb";
    version = "0.0.0";
    hash = "cc7598fd757f24624e86865fe3a12a26419b694463596fe036d281bc7e839a47";
    deps = with allCrates; [  ];
  };
  "fsb_0_0" = fsb_0_0_0;
  "fsb_0" = fsb_0_0_0;}