#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tunein-rs_0_1_0 = buildCratesLib {
    name = "tunein-rs";
    version = "0.1.0";
    hash = "a9ac132e88e02b4e5aacb70549972c8f49106be4ec3a0177f17c1a298b9b7af8";
    deps = with allCrates; [  all__xml-rs.xml-rs_0_3 ];
  };
  "tunein-rs_0_1" = tunein-rs_0_1_0;
  "tunein-rs_0" = tunein-rs_0_1_0;}