#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  kalyna_0_0_0 = buildCratesLib {
    name = "kalyna";
    version = "0.0.0";
    hash = "c69909c1cbf6f328639f1c10e50de9108d3289e7573b75ed55d00da1b1daf58e";
    deps = with allCrates; [  ];
  };
  "kalyna_0_0" = kalyna_0_0_0;
  "kalyna_0" = kalyna_0_0_0;}