#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  unicode-xid_0_0_1 = buildCratesLib {
    name = "unicode-xid";
    version = "0.0.1";
    hash = "c57c7d77ce303b7214479ffc12ae82be53ebb6a8720ff4a322e412c119747f82";
    deps = with allCrates; [  ];
  };
  unicode-xid_0_0_2 = buildCratesLib {
    name = "unicode-xid";
    version = "0.0.2";
    hash = "f69506a2561962651710609304bbb961fa3da598c812f877975a82e48ee144f9";
    deps = with allCrates; [  ];
  };
  unicode-xid_0_0_3 = buildCratesLib {
    name = "unicode-xid";
    version = "0.0.3";
    hash = "36dff09cafb4ec7c8cf0023eb0b686cb6ce65499116a12201c9e11840ca01beb";
    deps = with allCrates; [  ];
  };
  unicode-xid_0_0_4 = buildCratesLib {
    name = "unicode-xid";
    version = "0.0.4";
    hash = "8c1f860d7d29cf02cb2f3f359fd35991af3d30bac52c57d265a3c461074cb4dc";
    deps = with allCrates; [  ];
  };
  "unicode-xid_0_0" = unicode-xid_0_0_4;
  "unicode-xid_0" = unicode-xid_0_0_4;}