#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  magma_0_0_0 = buildCratesLib {
    name = "magma";
    version = "0.0.0";
    hash = "77297a9448711049ba9666e5bd6f358f7409ea056df3aa820875c9338d72c2e3";
    deps = with allCrates; [  ];
  };
  "magma_0_0" = magma_0_0_0;
  "magma_0" = magma_0_0_0;}