#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  pathfinding_0_1_0 = buildCratesLib {
    name = "pathfinding";
    version = "0.1.0";
    hash = "abfd4d37cd74d35909bea6c62caf0adf37303bed0deb79a599217611b5751be6";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  pathfinding_0_1_1 = buildCratesLib {
    name = "pathfinding";
    version = "0.1.1";
    hash = "9b1babeda9853f9a54cda651430df5f302890b2dfb07cf9840c5a5b766f05c5b";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  pathfinding_0_1_2 = buildCratesLib {
    name = "pathfinding";
    version = "0.1.2";
    hash = "120489f55a4d14876b5425eb3c79e0172328b67184dcae9b7322608dc23989ab";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  pathfinding_0_1_3 = buildCratesLib {
    name = "pathfinding";
    version = "0.1.3";
    hash = "f4fc9fb53c5d0ea6fc7068240b8c3abe7f770982f774e971dd1c72db905c2169";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  pathfinding_0_1_4 = buildCratesLib {
    name = "pathfinding";
    version = "0.1.4";
    hash = "f8177c5043b15d708a70cca8d06c42a56b94919def23f9356c3229f52b2fc3d4";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  pathfinding_0_1_5 = buildCratesLib {
    name = "pathfinding";
    version = "0.1.5";
    hash = "65491434437535e5ac7eff552e11b03b5511269a3ab93a802c8a5f9a32000d58";
    deps = with allCrates; [  all__num-traits.num-traits_0_1 ];
  };
  "pathfinding_0_1" = pathfinding_0_1_5;
  "pathfinding_0" = pathfinding_0_1_5;}