#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  simmons_rooms_0_1_0 = buildCratesLib {
    name = "simmons_rooms";
    version = "0.1.0";
    hash = "e14036cd90fc2fdfef240426f915987187af532330bb8b61ae2f2ff1e5d9cfa3";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  simmons_rooms_0_1_1 = buildCratesLib {
    name = "simmons_rooms";
    version = "0.1.1";
    hash = "c29bd06a0545bbabee4a6f1b229be6ee18e6688608a56697d1c1985b8c1ed4c2";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  "simmons_rooms_0_1" = simmons_rooms_0_1_1;
  "simmons_rooms_0" = simmons_rooms_0_1_1;}