#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  chrono_utils_0_1_0 = buildCratesLib {
    name = "chrono_utils";
    version = "0.1.0";
    hash = "fc095b4170cf7f50a0d95037540742c409fdc47692a3646607a9c488ac7dc5f0";
    deps = with allCrates; [  chrono ];
  };
  "chrono_utils_0_1" = chrono_utils_0_1_0;
  "chrono_utils_0" = chrono_utils_0_1_0;}