#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  consistency_1_0_0 = buildCratesLib {
    name = "consistency";
    version = "1.0.0";
    hash = "b8e6c237eef1f36d2b6c1ae8c741e0a3cdc7e6491ea7f752719388e905b58e30";
    deps = with allCrates; [  all__rust-crypto.rust-crypto_0_2 all__clippy.clippy_0_0_70 ];
  };
  "consistency_1_0" = consistency_1_0_0;
  "consistency_1" = consistency_1_0_0;}