#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  xinput_0_1_0 = buildCratesLib {
    name = "xinput";
    version = "0.1.0";
    hash = "303b2e098d8b16d196a87d5233f5bf7646fde8ec3e444cae79ae7fbb55726846";
    deps = with allCrates; [  all__xinput-sys.xinput-sys_0_2 all__winapi.winapi_0_2 ];
  };
  xinput_0_1_1 = buildCratesLib {
    name = "xinput";
    version = "0.1.1";
    hash = "d27d0b198112ad2da86f781352f3dd6ef51ac604728eb481e0a14bc835ad857b";
    deps = with allCrates; [  all__winapi.winapi_0_2 all__xinput-sys.xinput-sys_0_2 ];
  };
  "xinput_0_1" = xinput_0_1_1;
  "xinput_0" = xinput_0_1_1;}