#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  gomoku-core_0_1_0 = buildCratesLib {
    name = "gomoku-core";
    version = "0.1.0";
    hash = "ca82721344067df9d88e1dc4e834944ea7e2393211d2a3081bcb2cb5a2257b82";
    deps = with allCrates; [  ];
  };
  "gomoku-core_0_1" = gomoku-core_0_1_0;
  "gomoku-core_0" = gomoku-core_0_1_0;}