#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  verilog_0_0_1 = buildCratesLib {
    name = "verilog";
    version = "0.0.1";
    hash = "a9592a3981e44baaa92b88a754dfe4427c596c0eba7e4270e2141f08841abe40";
    deps = with allCrates; [  all__lalrpop-util.lalrpop-util_0_12 all__regex.regex_0_1 all__libflate.libflate_0_1 ];
  };
  "verilog_0_0" = verilog_0_0_1;
  "verilog_0" = verilog_0_0_1;}