#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  kitchensink_0_1_0 = buildCratesLib {
    name = "kitchensink";
    version = "0.1.0";
    hash = "3249209a2b42eb2eac7ef73e8fcf8db7e5fc74dc47ab6a5d7e333e92223a2679";
    deps = with allCrates; [  all__openssl.openssl_0_7 url all__openssl-verify.openssl-verify_0_1 hyper ];
  };
  kitchensink_0_2_0 = buildCratesLib {
    name = "kitchensink";
    version = "0.2.0";
    hash = "b0b2b58df56f32516802aeaacd541965b598ef9c4d84a57d7298be4dc25a7a4b";
    deps = with allCrates; [  url all__openssl-verify.openssl-verify_0_1 hyper all__openssl.openssl_0_7 ];
  };
  "kitchensink_0_1" = kitchensink_0_1_0;
  kitchensink_0_2_1 = buildCratesLib {
    name = "kitchensink";
    version = "0.2.1";
    hash = "71eb1e39801271ccf8e8c347969deaaad3b07c63e24add01bb9e3526ec9a8674";
    deps = with allCrates; [  all__openssl-verify.openssl-verify_0_1 hyper url all__openssl.openssl_0_7 ];
  };
  kitchensink_0_3_0 = buildCratesLib {
    name = "kitchensink";
    version = "0.3.0";
    hash = "b2a6e55ffffa94ba201fe50a80beb2f259d9cb71d52157f8915f846927109ed7";
    deps = with allCrates; [  hyper url all__openssl.openssl_0_7 ];
  };
  "kitchensink_0_2" = kitchensink_0_2_1;
  "kitchensink_0_3" = kitchensink_0_3_0;
  "kitchensink_0" = kitchensink_0_3_0;}