#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  minrs_0_1_0 = buildCratesLib {
    name = "minrs";
    version = "0.1.0";
    hash = "f6d02d09a8a81a2b02fd4e369ed69543d42669165a3623db9e7167c7d3c3c45d";
    deps = with allCrates; [  all__docopt.docopt_0_6 all__rustc-serialize.rustc-serialize_0_3 all__glium.glium_0_16 ];
  };
  minrs_0_1_1 = buildCratesLib {
    name = "minrs";
    version = "0.1.1";
    hash = "3cd46923d76eabe4f807c7b5c9782c8bf60d9c981b64a26ab3decc3a55502067";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__docopt.docopt_0_6 all__glium.glium_0 ];
  };
  minrs_0_1_2 = buildCratesLib {
    name = "minrs";
    version = "0.1.2";
    hash = "5ed00b8253049cfbf0b76221802000cf55fb7c05c113c248fae666e277a0d264";
    deps = with allCrates; [  all__docopt.docopt_0_6 all__glium.glium_0 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  minrs_0_2_0 = buildCratesLib {
    name = "minrs";
    version = "0.2.0";
    hash = "0c987d5400bb3bc7e31c8c0e0cdb335c053e6b1bf7eb7d8828bca4ec35d81cec";
    deps = with allCrates; [  all__docopt.docopt_0_6 all__rustc-serialize.rustc-serialize_0_3 all__glium.glium_0 ];
  };
  "minrs_0_1" = minrs_0_1_2;
  minrs_0_2_1 = buildCratesLib {
    name = "minrs";
    version = "0.2.1";
    hash = "15bcc0a7785af2c35161263f89a7e65f35fe1b65e3ee1c6cc1b95295082e5dbf";
    deps = with allCrates; [  all__docopt.docopt_0_6 all__glium.glium_0 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  minrs_0_2_2 = buildCratesLib {
    name = "minrs";
    version = "0.2.2";
    hash = "ce11b09c5918804ff1439f27c1c9927b21be4fc35ddf4645cfa0b7b220d103e2";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__glium.glium_0 all__docopt.docopt_0_6 ];
  };
  "minrs_0_2" = minrs_0_2_2;
  "minrs_0" = minrs_0_2_2;}