#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  nvptx-builtins_0_1_0 = buildCratesLib {
    name = "nvptx-builtins";
    version = "0.1.0";
    hash = "1001d126c981bc3b6d85e55bfb242696cef7cf5791d68a25fa3a4b55bbd9d979";
    deps = with allCrates; [  ];
  };
  "nvptx-builtins_0_1" = nvptx-builtins_0_1_0;
  "nvptx-builtins_0" = nvptx-builtins_0_1_0;}