#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  alcibiades_0_2_0 = buildCratesLib {
    name = "alcibiades";
    version = "0.2.0";
    hash = "ece62c432a0207c828cdcbb1dea14608518b9f2eadb4835898cf8f6fb2401759";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__rand.rand_0_3 all__regex.regex_0_1 ];
  };
  alcibiades_0_2_1 = buildCratesLib {
    name = "alcibiades";
    version = "0.2.1";
    hash = "c9e305d3f2434cc53ebbbc4acdc4033cdf901368ffa166cd9b3e775b00ce66c6";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__rand.rand_0_3 all__regex.regex_0_1 ];
  };
  alcibiades_0_2_2 = buildCratesLib {
    name = "alcibiades";
    version = "0.2.2";
    hash = "5fa49b3c6b67b206e901d377e16df5b8d514d1e5255c1977c13d6b07c3d552c1";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__regex.regex_0_1 all__rand.rand_0_3 ];
  };
  alcibiades_0_2_3 = buildCratesLib {
    name = "alcibiades";
    version = "0.2.3";
    hash = "1412a3854100b0434de4b6787f66ad9928f72f07be2e92c172cd0599e50f01c5";
    deps = with allCrates; [  all__regex.regex_0_1 all__rand.rand_0_3 all__lazy_static.lazy_static_0_2 ];
  };
  alcibiades_0_2_4 = buildCratesLib {
    name = "alcibiades";
    version = "0.2.4";
    hash = "5a9634dd2e62cabe6e8c2b12c051df858f78395434b649b845c53e6bb11af22f";
    deps = with allCrates; [  all__rand.rand_0_3 all__lazy_static.lazy_static_0_2 all__regex.regex_0_1 ];
  };
  alcibiades_0_2_5 = buildCratesLib {
    name = "alcibiades";
    version = "0.2.5";
    hash = "97a89e838f0dd848759429453b3a2aec7a26f67c7975b85922b98c623960d66e";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__rand.rand_0_3 all__regex.regex_0_2 ];
  };
  "alcibiades_0_2" = alcibiades_0_2_5;
  "alcibiades_0" = alcibiades_0_2_5;}