#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  relay_0_0_0 = buildCratesLib {
    name = "relay";
    version = "0.0.0";
    hash = "290cba365dbf949419ba5d363e2339f49b775f119f05c077f545660859a430ef";
    deps = with allCrates; [  ];
  };
  relay_0_1_0 = buildCratesLib {
    name = "relay";
    version = "0.1.0";
    hash = "f301bafeb60867c85170031bdb2fcf24c8041f33aee09e7b116a58d4e9f781c5";
    deps = with allCrates; [  all__futures.futures_0_1 ];
  };
  "relay_0_0" = relay_0_0_0;
  "relay_0_1" = relay_0_1_0;
  "relay_0" = relay_0_1_0;}