#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  multistr_0_1_0 = buildCratesLib {
    name = "multistr";
    version = "0.1.0";
    hash = "580cf28d7f3f14dc8493e67999a4f3a0cf628a7b2317b36f4d9306a9653e856a";
    deps = with allCrates; [  ];
  };
  multistr_0_2_0 = buildCratesLib {
    name = "multistr";
    version = "0.2.0";
    hash = "57b2e1925ea33b663d5b6f6c95f2355e6b32bff8cb95a0504c9d58682e9c863c";
    deps = with allCrates; [  ];
  };
  "multistr_0_1" = multistr_0_1_0;
  multistr_0_2_1 = buildCratesLib {
    name = "multistr";
    version = "0.2.1";
    hash = "948d1285dd39981f6a5b1a72624c323312d29e2121682a742a87a773dd723bef";
    deps = with allCrates; [  ];
  };
  "multistr_0_2" = multistr_0_2_1;
  "multistr_0" = multistr_0_2_1;}