#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  pcx_0_1_0 = buildCratesLib {
    name = "pcx";
    version = "0.1.0";
    hash = "373b36a176c3f00551acc93f6bf0589845d93106eb06f3d5f808398f0f3bdb0f";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 ];
  };
  pcx_0_1_1 = buildCratesLib {
    name = "pcx";
    version = "0.1.1";
    hash = "05ccfc26b3e769c6a16b2fb21f08e813288d8da0ed23c8df0e8811f38b322c33";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 ];
  };
  pcx_0_1_2 = buildCratesLib {
    name = "pcx";
    version = "0.1.2";
    hash = "aea95d95f755c16677477acd124c27a4311f460ccccd0f2eaa68caf58a447101";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 ];
  };
  pcx_0_2_0 = buildCratesLib {
    name = "pcx";
    version = "0.2.0";
    hash = "6af3bd865189a5698609548e7be537b9d94de5cb207e622ebfe01aca667940e1";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 ];
  };
  "pcx_0_1" = pcx_0_1_2;
  "pcx_0_2" = pcx_0_2_0;
  "pcx_0" = pcx_0_2_0;}