#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  psl_0_0_0 = buildCratesLib {
    name = "psl";
    version = "0.0.0";
    hash = "573755cf3a9508453eecd3e992b66d06dc1a67e798e4d3601fa9298b12998840";
    deps = with allCrates; [  all__publicsuffix.publicsuffix_1_3 all__lazy_static.lazy_static_0_2 ];
  };
  psl_0_0_1 = buildCratesLib {
    name = "psl";
    version = "0.0.1";
    hash = "5f859a0f6530776222abb2588cc2fe3f130c3821541750f9228316fef2fed740";
    deps = with allCrates; [  all__slog-scope.slog-scope_0_2 all__publicsuffix.publicsuffix_1_3 all__parking_lot.parking_lot_0_3 all__lazy_static.lazy_static_0_2 all__slog.slog_1_2 ];
  };
  psl_0_0_2 = buildCratesLib {
    name = "psl";
    version = "0.0.2";
    hash = "a834ee1c7c6339cf3060df164fc842c36cae33906066e68aab0d53461cb287eb";
    deps = with allCrates; [  all__parking_lot.parking_lot_0_3 all__publicsuffix.publicsuffix_1_3 all__slog.slog_1_2 all__app_dirs.app_dirs_1_1 all__lazy_static.lazy_static_0_2 all__slog-scope.slog-scope_0_2 ];
  };
  "psl_0_0" = psl_0_0_2;
  "psl_0" = psl_0_0_2;}