#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  px8_0_0_1 = buildCratesLib {
    name = "px8";
    version = "0.0.1";
    hash = "3f6e7ece793569c35850163dd7362fe48a6488bec2f50acf217ac661af3539e5";
    deps = with allCrates; [  all__libc.libc_0_2 all__image.image_0_11 all__env_logger.env_logger_0_3 all__rand.rand_0_3 all__getopts.getopts_0_2 all__rusttype.rusttype_0_2 all__time.time_0_1 all__sdl2.sdl2_0_27 all__png.png_0_5 all__rustc-serialize.rustc-serialize_0_3 all__chrono.chrono_0_2 all__glium.glium_0_15 all__byteorder.byteorder_1_0_0 all__log.log_0_3 all__chan.chan_0_1 all__nalgebra.nalgebra_0_10 all__gif.gif_0_9 all__regex.regex_0_2 ];
  };
  "px8_0_0" = px8_0_0_1;
  "px8_0" = px8_0_0_1;}