#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  slice-pool_0_1_0 = buildCratesLib {
    name = "slice-pool";
    version = "0.1.0";
    hash = "efe62818daaa306bf511cfd921319563fd332b91774ae90b69faf429ce53eeaa";
    deps = with allCrates; [  ];
  };
  slice-pool_0_2_0 = buildCratesLib {
    name = "slice-pool";
    version = "0.2.0";
    hash = "8d2805509ae9ce8ac838a811ce0c552e7a55ee2864a7d27115b3d2b1124c572a";
    deps = with allCrates; [  ];
  };
  "slice-pool_0_1" = slice-pool_0_1_0;
  slice-pool_0_3_0 = buildCratesLib {
    name = "slice-pool";
    version = "0.3.0";
    hash = "e3161d6686c93b61527355e2f5eede9e66177c8075d60f2b688bd3a835c13d2b";
    deps = with allCrates; [  ];
  };
  "slice-pool_0_2" = slice-pool_0_2_0;
  slice-pool_0_3_1 = buildCratesLib {
    name = "slice-pool";
    version = "0.3.1";
    hash = "a95e1a650e20cf4c0a6ae7d85256d4d8fc2d428d34c3f353bf12c6a7f2ee05c3";
    deps = with allCrates; [  ];
  };
  slice-pool_0_3_2 = buildCratesLib {
    name = "slice-pool";
    version = "0.3.2";
    hash = "d1acd79f5dfe99af8cee838d3eb2b0aa7deb9b600ae159ecb16c6dc654c25ca1";
    deps = with allCrates; [  ];
  };
  slice-pool_0_3_3 = buildCratesLib {
    name = "slice-pool";
    version = "0.3.3";
    hash = "b9a593f5116c625ea2aac7dd133e136012177a48eb039182127ea68dba199516";
    deps = with allCrates; [  ];
  };
  "slice-pool_0_3" = slice-pool_0_3_3;
  "slice-pool_0" = slice-pool_0_3_3;}