#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  symtern_0_1_0 = buildCratesLib {
    name = "symtern";
    version = "0.1.0";
    hash = "7c417caafd2806afc40200d012904ba86acec394a6e480db15a9299a3ddca90d";
    deps = with allCrates; [  all__num-traits.num-traits_0_1 ];
  };
  "symtern_0_1" = symtern_0_1_0;
  "symtern_0" = symtern_0_1_0;}