#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rain_0_1_0 = buildCratesLib {
    name = "rain";
    version = "0.1.0";
    hash = "596fbd3ed8f7b5b6d602ecf8a315bb98667e0ffd63f1bffb9a30369be6c6db7a";
    deps = with allCrates; [  all__ansi_term.ansi_term_0 all__term_size.term_size_0 all__mowl.mowl_1 all__log.log_0 ];
  };
  rain_0_2_0 = buildCratesLib {
    name = "rain";
    version = "0.2.0";
    hash = "a9cdb13c18d0aac3c16cc1de46c3b8d1244a6342ca173f1ea28c14b2412fbfa2";
    deps = with allCrates; [  all__log.log_0 all__mowl.mowl_1 all__termion.termion_1 ];
  };
  "rain_0_1" = rain_0_1_0;
  rain_0_2_1 = buildCratesLib {
    name = "rain";
    version = "0.2.1";
    hash = "a3e88072f0dd0c3765d198f30ebd2c3e021084d8361d4470d1d56dc44b7bc940";
    deps = with allCrates; [  all__termion.termion_1 all__mowl.mowl_1 all__log.log_0 ];
  };
  rain_0_2_2 = buildCratesLib {
    name = "rain";
    version = "0.2.2";
    hash = "f6c66fc4f3aa674447ec60e553b35f05f83a4d8309f7808ecc75514bd6b4f066";
    deps = with allCrates; [  all__log.log_0 all__termion.termion_1 all__mowl.mowl_1 ];
  };
  "rain_0_2" = rain_0_2_2;
  "rain_0" = rain_0_2_2;}