#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  shell-escape_0_1_0 = buildCratesLib {
    name = "shell-escape";
    version = "0.1.0";
    hash = "f155750265e04a1d42cc4bba7dbcadf7ca055b11f8c1e01884a40fc7d91a8431";
    deps = with allCrates; [  ];
  };
  "shell-escape_0_1" = shell-escape_0_1_0;
  "shell-escape_0" = shell-escape_0_1_0;}