#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rope_0_0_1 = buildCratesLib {
    name = "rope";
    version = "0.0.1";
    hash = "0cec661612abf8dc4b3ec71f5ff2ddd4a8985de623951eccf895c35ba569176d";
    deps = with allCrates; [  fingertree epsilonz_algebra ];
  };
  "rope_0_0" = rope_0_0_1;
  "rope_0" = rope_0_0_1;}