#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  omnibus_0_1_1 = buildCratesLib {
    name = "omnibus";
    version = "0.1.1";
    hash = "32c2fc4d742f83c887f28a54d3fc1e02864a90060c46aae1aaa4ff247b35ce70";
    deps = with allCrates; [  ];
  };
  "omnibus_0_1" = omnibus_0_1_1;
  "omnibus_0" = omnibus_0_1_1;}