#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  plist-rs_0_1_0 = buildCratesLib {
    name = "plist-rs";
    version = "0.1.0";
    hash = "12dd1f1c1eff8769df084de43480e18a250e7cea16c4128dd2b539864f17faed";
    deps = with allCrates; [  all__chrono.chrono_0_2 all__xml-rs.xml-rs_0_3 all__rustc-serialize.rustc-serialize_0_3 all__fnv.fnv_1_0 ];
  };
  "plist-rs_0_1" = plist-rs_0_1_0;
  "plist-rs_0" = plist-rs_0_1_0;}