#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  m3u_0_1_0 = buildCratesLib {
    name = "m3u";
    version = "0.1.0";
    hash = "518595c23830e55742bc2d69313fb5db0077d2125d02ca124fe970e147a7a3c6";
    deps = with allCrates; [  all__url.url_1_2 ];
  };
  m3u_1_0_0 = buildCratesLib {
    name = "m3u";
    version = "1.0.0";
    hash = "ca48bebf6a7397a81aa8b9dcc8a7cfcbacab3e15a28f49d2aabaa9e3c06def4d";
    deps = with allCrates; [  all__url.url_1_2 ];
  };
  "m3u_0_1" = m3u_0_1_0;
  "m3u_0" = m3u_0_1_0;
  "m3u_1_0" = m3u_1_0_0;
  "m3u_1" = m3u_1_0_0;}