#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  md5_0_1_0 = buildCratesLib {
    name = "md5";
    version = "0.1.0";
    hash = "c0a756d916e21425fc59dba958089f40b4eae39628041e82f022f2091a760676";
    deps = with allCrates; [  ];
  };
  md5_0_1_1 = buildCratesLib {
    name = "md5";
    version = "0.1.1";
    hash = "a5539a8dee9b4ae308c9c406a379838b435a8f2c84cf9fedc6d5a576be9888db";
    deps = with allCrates; [  ];
  };
  md5_0_2_0 = buildCratesLib {
    name = "md5";
    version = "0.2.0";
    hash = "f5384d8984cacd657f3aadf44dc4bbb0b9e3e3cf4435268572af0a0614a76256";
    deps = with allCrates; [  ];
  };
  "md5_0_1" = md5_0_1_1;
  md5_0_2_1 = buildCratesLib {
    name = "md5";
    version = "0.2.1";
    hash = "7df230903ccdffd6b3b4ec21624498ea64c912ce50297846907f0b8e1bb249dd";
    deps = with allCrates; [  ];
  };
  md5_0_3_0 = buildCratesLib {
    name = "md5";
    version = "0.3.0";
    hash = "d67cbb88c73b2c6256ec40ce7f41f72754a1eb5b938b2541e105d1e7fce3a933";
    deps = with allCrates; [  ];
  };
  "md5_0_2" = md5_0_2_1;
  md5_0_3_1 = buildCratesLib {
    name = "md5";
    version = "0.3.1";
    hash = "c0faf23e8298646d24521edde22e09d1d16597e4dbf18ca9046daec34a82aae1";
    deps = with allCrates; [  ];
  };
  md5_0_3_2 = buildCratesLib {
    name = "md5";
    version = "0.3.2";
    hash = "6fce5a83f1379e0a2353a8ac5d15270d417ad36c6ac78ea4d4beae7482e6812d";
    deps = with allCrates; [  ];
  };
  "md5_0_3" = md5_0_3_2;
  "md5_0" = md5_0_3_2;}