#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rocket_0_1_0 = buildCratesLib {
    name = "rocket";
    version = "0.1.0";
    hash = "fde816bd0ca692c38e64c53584ee6c17ce691955655e0527df6f68275be97746";
    deps = with allCrates; [  all__url.url_1 all__toml.toml_0_2 all__term-painter.term-painter_0_2 all__log.log_0_3 all__hyper.hyper_0_9 ];
  };
  "rocket_0_1" = rocket_0_1_0;
  "rocket_0" = rocket_0_1_0;}