#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  dns2_0_0_0 = buildCratesLib {
    name = "dns2";
    version = "0.0.0";
    hash = "258f72b948c551e98aa2149f63e560491f525a1f8cea92157c8ae33eb008fa23";
    deps = with allCrates; [  ];
  };
  "dns2_0_0" = dns2_0_0_0;
  "dns2_0" = dns2_0_0_0;}