#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  volatile_cell_0_0_1 = buildCratesLib {
    name = "volatile_cell";
    version = "0.0.1";
    hash = "5b2a561791fb68263a4ddaab8a4bc9f0169c831df739a2a614b5fc471f6a8eca";
    deps = with allCrates; [  all__rust-libcore.rust-libcore_0_0_1 all__rust-libcore.rust-libcore_0_0_1 all__rust-libcore.rust-libcore_0_0_1 ];
  };
  volatile_cell_1_0_0 = buildCratesLib {
    name = "volatile_cell";
    version = "1.0.0";
    hash = "e89c44c56cc47ef6c4fccb52a3a5c48c4306929294fdf4ffe67321a0071bba72";
    deps = with allCrates; [  rust-libcore rust-libcore rust-libcore ];
  };
  "volatile_cell_0_0" = volatile_cell_0_0_1;
  "volatile_cell_0" = volatile_cell_0_0_1;
  "volatile_cell_1_0" = volatile_cell_1_0_0;
  "volatile_cell_1" = volatile_cell_1_0_0;}