#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  isatty_0_1_0 = buildCratesLib {
    name = "isatty";
    version = "0.1.0";
    hash = "cc6f3814cf31e88ad07af1c78568413fec0a904309ca6c3d4468020e50d282b9";
    deps = with allCrates; [  all__libc.libc_0_2 all__kernel32-sys.kernel32-sys_0_2 all__winapi.winapi_0_2 ];
  };
  isatty_0_1_1 = buildCratesLib {
    name = "isatty";
    version = "0.1.1";
    hash = "7408a548dc0e406b7912d9f84c261cc533c1866e047644a811c133c56041ac0c";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  isatty_0_1_2 = buildCratesLib {
    name = "isatty";
    version = "0.1.2";
    hash = "eec9bf0758220f4bcf033823234bada5756056412294acf544742af1417e9fa4";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  isatty_0_1_3 = buildCratesLib {
    name = "isatty";
    version = "0.1.3";
    hash = "fa500db770a99afe2a0f2229be2a3d09c7ed9d7e4e8440bf71253141994e240f";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  "isatty_0_1" = isatty_0_1_3;
  "isatty_0" = isatty_0_1_3;}