#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cpr_1_0_0 = buildCratesLib {
    name = "cpr";
    version = "1.0.0";
    hash = "6ef0c338675b618149b0c0354cd891b25c8fa5d04fe32b6039d84c11b5d17d78";
    deps = with allCrates; [  all__bio.bio_0_9 all__scoped_threadpool.scoped_threadpool_0_1 all__getopts.getopts_0_2 all__num.num_0_1 all__num_cpus.num_cpus_1_0 all__lazy_static.lazy_static_0_1 all__time.time_0_1 ];
  };
  cpr_1_0_1 = buildCratesLib {
    name = "cpr";
    version = "1.0.1";
    hash = "5f2c0fd38f82418beed2fbdf3b55dc6202139409c9bc34256a79aa4a89499837";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 all__getopts.getopts_0_2 all__time.time_0_1 all__num_cpus.num_cpus_1_0 all__scoped_threadpool.scoped_threadpool_0_1 all__bio.bio_0_9 all__num.num_0_1 ];
  };
  cpr_1_0_2 = buildCratesLib {
    name = "cpr";
    version = "1.0.2";
    hash = "779f839dc2c80af28a27580c63e64a0a3836b48171126a2d50fa12cedc89e015";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 all__time.time_0_1 all__num_cpus.num_cpus_1_0 all__num.num_0_1 all__getopts.getopts_0_2 all__scoped_threadpool.scoped_threadpool_0_1 all__bio.bio_0_9 ];
  };
  cpr_1_0_3 = buildCratesLib {
    name = "cpr";
    version = "1.0.3";
    hash = "0fd37c905386dd24a352c9d2c7484ca372e8f6c2df735368a9252365e9cc2bb7";
    deps = with allCrates; [  all__num.num_0_1 all__lazy_static.lazy_static_0_1 all__getopts.getopts_0_2 all__scoped_threadpool.scoped_threadpool_0_1 all__num_cpus.num_cpus_1_0 all__time.time_0_1 all__bio.bio_0_9 ];
  };
  cpr_1_0_4 = buildCratesLib {
    name = "cpr";
    version = "1.0.4";
    hash = "9b97e61aa1f8db99f05e2ab00a365b80b2b02f584b3c19052e2d5a2a351882f8";
    deps = with allCrates; [  all__scoped_threadpool.scoped_threadpool_0_1 all__num.num_0_1 all__getopts.getopts_0_2 all__time.time_0_1 all__lazy_static.lazy_static_0_1 all__num_cpus.num_cpus_1_0 all__bio.bio_0_9 ];
  };
  cpr_1_0_5 = buildCratesLib {
    name = "cpr";
    version = "1.0.5";
    hash = "a98a0536a3be4596db1e2f40748dcf8f7858231b12214f784f6b6b981212ac28";
    deps = with allCrates; [  all__time.time_0_1 all__getopts.getopts_0_2 all__scoped_threadpool.scoped_threadpool_0_1 all__bio.bio_0_9 all__num_cpus.num_cpus_1_0 all__lazy_static.lazy_static_0_1 all__num.num_0_1 ];
  };
  cpr_1_0_6 = buildCratesLib {
    name = "cpr";
    version = "1.0.6";
    hash = "e195fb5f5974bbba085cc272f4e92bad762de27c051c06da53c48d115eace733";
    deps = with allCrates; [  all__num_cpus.num_cpus_1_0 all__getopts.getopts_0_2 all__time.time_0_1 all__bio.bio_0_9 all__num.num_0_1 all__lazy_static.lazy_static_0_1 all__scoped_threadpool.scoped_threadpool_0_1 ];
  };
  cpr_1_0_7 = buildCratesLib {
    name = "cpr";
    version = "1.0.7";
    hash = "8eb8b7438f9b2041c7c47fe9074222689d10c32b67d0398195d2a2019194523e";
    deps = with allCrates; [  all__time.time_0_1 all__getopts.getopts_0_2 all__lazy_static.lazy_static_0_1 all__num.num_0_1 all__bio.bio_0_9 all__scoped_threadpool.scoped_threadpool_0_1 all__num_cpus.num_cpus_1_0 ];
  };
  "cpr_1_0" = cpr_1_0_7;
  "cpr_1" = cpr_1_0_7;}