#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rtrie_0_1_0 = buildCratesLib {
    name = "rtrie";
    version = "0.1.0";
    hash = "78822de77cf505af5eb215500de749f873cb4eff0b0ba212d6d805ad072a1a80";
    deps = with allCrates; [  all__num-traits.num-traits_0_1 all__rand.rand_0_3 ];
  };
  rtrie_0_1_1 = buildCratesLib {
    name = "rtrie";
    version = "0.1.1";
    hash = "a3ba2294621f3a628a295dd92ebaff548c226a003e4a3ef29b3ad312db560ab8";
    deps = with allCrates; [  all__rand.rand_0_3 all__num-traits.num-traits_0_1 ];
  };
  "rtrie_0_1" = rtrie_0_1_1;
  "rtrie_0" = rtrie_0_1_1;}