#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  simple_bencode_0_1_0 = buildCratesLib {
    name = "simple_bencode";
    version = "0.1.0";
    hash = "4025c7cd4a4fcdfd2dff7b227be74de7266d45db691af2eb9de6534170718425";
    deps = with allCrates; [  ];
  };
  simple_bencode_0_1_1 = buildCratesLib {
    name = "simple_bencode";
    version = "0.1.1";
    hash = "1ae0754a7b93a6c55da8d0671046c0f717aaa5b26836971f6f43e3d263efc6de";
    deps = with allCrates; [  ];
  };
  simple_bencode_0_1_2 = buildCratesLib {
    name = "simple_bencode";
    version = "0.1.2";
    hash = "b98f542ad36152c43622fd5c5d70ce666a534fcefff5e1414364e820bad81076";
    deps = with allCrates; [  ];
  };
  simple_bencode_0_1_3 = buildCratesLib {
    name = "simple_bencode";
    version = "0.1.3";
    hash = "46e6c8e3556fc6df2b056b009dccb59682de3535f3ef8734cf5959202977569c";
    deps = with allCrates; [  ];
  };
  simple_bencode_0_1_4 = buildCratesLib {
    name = "simple_bencode";
    version = "0.1.4";
    hash = "fa18521605f49aadcd6fbcfcf9d8002d8d918b0b5f0ea1ba2a3cd43b66a8dfe1";
    deps = with allCrates; [  ];
  };
  "simple_bencode_0_1" = simple_bencode_0_1_4;
  "simple_bencode_0" = simple_bencode_0_1_4;}