#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  mlcr_0_1_0 = buildCratesLib {
    name = "mlcr";
    version = "0.1.0";
    hash = "2913b2c01859e5d20932f210393a2fa1c2a84024d9cfd1b02fa5a8d36de829ea";
    deps = with allCrates; [  all__nn.nn_0_1 ];
  };
  "mlcr_0_1" = mlcr_0_1_0;
  "mlcr_0" = mlcr_0_1_0;}