#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  serpent_0_0_0 = buildCratesLib {
    name = "serpent";
    version = "0.0.0";
    hash = "5f29c30b3470819ece961d07d8914d1aa1379325138bfc2e1f649b95d02ef11d";
    deps = with allCrates; [  ];
  };
  "serpent_0_0" = serpent_0_0_0;
  "serpent_0" = serpent_0_0_0;}