#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  lithium_gfx_0_0_0 = buildCratesLib {
    name = "lithium_gfx";
    version = "0.0.0";
    hash = "107496ae2170c7f7fe6d3986bef34ac6403989c1bb70e90828222f9aba66a3da";
    deps = with allCrates; [  ];
  };
  "lithium_gfx_0_0" = lithium_gfx_0_0_0;
  "lithium_gfx_0" = lithium_gfx_0_0_0;}