#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tor_control_0_2_0 = buildCratesLib {
    name = "tor_control";
    version = "0.2.0";
    hash = "f7f564b5411620f25c174c32c60ef4d1a11b8b76559e3584988bc3c23d4d742b";
    deps = with allCrates; [  all__bufstream.bufstream_0_1 all__futures.futures_0_1 ];
  };
  "tor_control_0_2" = tor_control_0_2_0;
  "tor_control_0" = tor_control_0_2_0;}