#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  haxonite_0_1_0 = buildCratesLib {
    name = "haxonite";
    version = "0.1.0";
    hash = "f222ce8b5d613178509771e3134202d7af29d2845f2c4573639529c7d2a3d4f9";
    deps = with allCrates; [  all__iron.iron_0_4 all__random_choice.random_choice_0_3 all__toml.toml_0_2 all__router.router_0_4 all__logger.logger_0_2 all__rustache.rustache_0_0 all__log.log_0_3 all__staticfile.staticfile_0_3 all__clap.clap_2 all__rustc-serialize.rustc-serialize_0_3 all__mount.mount_0_2 all__simplelog.simplelog_0_4 ];
  };
  "haxonite_0_1" = haxonite_0_1_0;
  "haxonite_0" = haxonite_0_1_0;}