#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  nail_0_1_0 = buildCratesLib {
    name = "nail";
    version = "0.1.0";
    hash = "4a0e4f29373b40278521efcccdfb69dea68cff6d9f876a42b8cf20c8e2d2b086";
    deps = with allCrates; [  all__linenoise-rust.linenoise-rust_0_2 all__lazy_static.lazy_static_0_2 all__repl.repl_0_7 all__regex.regex_0_1 all__clap.clap_2_5 ];
  };
  "nail_0_1" = nail_0_1_0;
  "nail_0" = nail_0_1_0;}