#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  kuznyechik_0_0_0 = buildCratesLib {
    name = "kuznyechik";
    version = "0.0.0";
    hash = "1373f45c402292b3be9f33da02b98115bea5116832f40a75b6e24e771ed45dca";
    deps = with allCrates; [  ];
  };
  "kuznyechik_0_0" = kuznyechik_0_0_0;
  "kuznyechik_0" = kuznyechik_0_0_0;}