#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  data_tracker_0_1_0 = buildCratesLib {
    name = "data_tracker";
    version = "0.1.0";
    hash = "742c99ecb32c6a1bb60a61d3f691bd19235879858490a171ee67ff2be28ef7cb";
    deps = with allCrates; [  ];
  };
  "data_tracker_0_1" = data_tracker_0_1_0;
  "data_tracker_0" = data_tracker_0_1_0;}