#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  smpl_jwt_0_1_1 = buildCratesLib {
    name = "smpl_jwt";
    version = "0.1.1";
    hash = "44f2403889a626d6903ebc8dedf3998d177e40f62c0ab0d8cc995f76b9cf83bd";
    deps = with allCrates; [  all__log.log_0_3 all__serde_json.serde_json_0_8 all__time.time_0_1 all__serde_derive.serde_derive_0_8 all__serde.serde_0_8 all__rustc-serialize.rustc-serialize_0_3 all__openssl.openssl_0_9 ];
  };
  "smpl_jwt_0_1" = smpl_jwt_0_1_1;
  "smpl_jwt_0" = smpl_jwt_0_1_1;}