#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rsdocs2docset_0_1_0 = buildCratesLib {
    name = "rsdocs2docset";
    version = "0.1.0";
    hash = "028b52e24eb821546ed16b6b125bcfff6864d20f246545332ffdacfcfdfb4638";
    deps = with allCrates; [  all__quick-error.quick-error_1 all__string_cache.string_cache_0 all__clap.clap_2 all__sqlite.sqlite_0 all__tendril.tendril_0 all__url.url_1 all__html5ever.html5ever_0 all__html5ever-atoms.html5ever-atoms_0 all__regex.regex_0 ];
  };
  rsdocs2docset_0_1_1 = buildCratesLib {
    name = "rsdocs2docset";
    version = "0.1.1";
    hash = "ed902a961296a150922c0508fc66202030993259cb04277e1ba289d19777bfa2";
    deps = with allCrates; [  all__tendril.tendril_0 all__html5ever-atoms.html5ever-atoms_0 all__regex.regex_0 all__url.url_1 all__clap.clap_2 all__sqlite.sqlite_0 all__string_cache.string_cache_0 all__quick-error.quick-error_1 all__html5ever.html5ever_0 ];
  };
  rsdocs2docset_0_1_2 = buildCratesLib {
    name = "rsdocs2docset";
    version = "0.1.2";
    hash = "f4c1ecba00e38418e5b760817732ac7294fb82d8fdb98f5692c4374bf7a84d95";
    deps = with allCrates; [  all__string_cache.string_cache_0 all__url.url_1 all__quick-error.quick-error_1 all__clap.clap_2 all__tendril.tendril_0 all__html5ever.html5ever_0 all__html5ever-atoms.html5ever-atoms_0 all__sqlite.sqlite_0 all__regex.regex_0 ];
  };
  rsdocs2docset_0_2_0 = buildCratesLib {
    name = "rsdocs2docset";
    version = "0.2.0";
    hash = "a6d9de872d06e6bcfd2f6fbe62ba86aa1cbce667e833ca5f0daf8f14bf3f4204";
    deps = with allCrates; [  all__regex.regex_0 all__quick-error.quick-error_1 all__string_cache.string_cache_0 all__html5ever-atoms.html5ever-atoms_0 all__tendril.tendril_0 all__sqlite.sqlite_0 all__html5ever.html5ever_0 all__clap.clap_2 all__url.url_1 ];
  };
  "rsdocs2docset_0_1" = rsdocs2docset_0_1_2;
  rsdocs2docset_0_2_9 = buildCratesLib {
    name = "rsdocs2docset";
    version = "0.2.9";
    hash = "64db2c1936256af6b2862e57d6982b42c04e6a7260e1a7b65157ac2f5453846e";
    deps = with allCrates; [  all__tendril.tendril_0 all__clap.clap_2 all__quick-error.quick-error_1 all__regex.regex_0 all__html5ever-atoms.html5ever-atoms_0 all__html5ever.html5ever_0 all__string_cache.string_cache_0 all__sqlite.sqlite_0 all__url.url_1 ];
  };
  rsdocs2docset_0_3_0 = buildCratesLib {
    name = "rsdocs2docset";
    version = "0.3.0";
    hash = "49b94f185866ca79a020a1962ec205ab13a299d84ee04617808869ded564cfce";
    deps = with allCrates; [  all__sqlite.sqlite_0 all__clap.clap_2 all__html5ever.html5ever_0 all__html5ever-atoms.html5ever-atoms_0 all__tendril.tendril_0 all__url.url_1 all__regex.regex_0 all__quick-error.quick-error_1 all__string_cache.string_cache_0 ];
  };
  "rsdocs2docset_0_2" = rsdocs2docset_0_2_9;
  rsdocs2docset_0_4_0 = buildCratesLib {
    name = "rsdocs2docset";
    version = "0.4.0";
    hash = "9207fbe6a5b13a6f486b55deaf06583c8bf9eb71c9bc9da88d90405aa4d75d18";
    deps = with allCrates; [  all__html5ever-atoms.html5ever-atoms_0 all__html5ever.html5ever_0 all__string_cache.string_cache_0 all__regex.regex_0 all__url.url_1 all__quick-error.quick-error_1 all__tendril.tendril_0 all__clap.clap_2 all__sqlite.sqlite_0 ];
  };
  "rsdocs2docset_0_3" = rsdocs2docset_0_3_0;
  "rsdocs2docset_0_4" = rsdocs2docset_0_4_0;
  "rsdocs2docset_0" = rsdocs2docset_0_4_0;}