#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  camellia_0_0_0 = buildCratesLib {
    name = "camellia";
    version = "0.0.0";
    hash = "c3a35c6a2e38053270b24c4189500ec239f2c329e48c20f090470e45ed664442";
    deps = with allCrates; [  ];
  };
  "camellia_0_0" = camellia_0_0_0;
  "camellia_0" = camellia_0_0_0;}