#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  atomic_refcell_0_1_0 = buildCratesLib {
    name = "atomic_refcell";
    version = "0.1.0";
    hash = "fb2dcb6e6d35f20276943cc04bb98e538b348d525a04ac79c10021561d202f21";
    deps = with allCrates; [  ];
  };
  "atomic_refcell_0_1" = atomic_refcell_0_1_0;
  "atomic_refcell_0" = atomic_refcell_0_1_0;}