#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tiger_0_0_0 = buildCratesLib {
    name = "tiger";
    version = "0.0.0";
    hash = "49035f549113e35d70a32e03b8d5a8b7e6f91bfbc2fee59236d83963c2612cf6";
    deps = with allCrates; [  ];
  };
  "tiger_0_0" = tiger_0_0_0;
  "tiger_0" = tiger_0_0_0;}