#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  mandrill_sender_0_1_0 = buildCratesLib {
    name = "mandrill_sender";
    version = "0.1.0";
    hash = "168169ac6b53b8e6df6b6dc4931e7b789d7fe1e0a6dd3a1041423e953364404f";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__reqwest.reqwest_0_1 ];
  };
  "mandrill_sender_0_1" = mandrill_sender_0_1_0;
  "mandrill_sender_0" = mandrill_sender_0_1_0;}