#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  hopper_0_1_0 = buildCratesLib {
    name = "hopper";
    version = "0.1.0";
    hash = "0fb1426b1f2a94e2e923d306a0e76ed46a60a898f62b2d213ac5f2169c64c36f";
    deps = with allCrates; [  all__bincode.bincode_0_6 all__serde.serde_0_8 ];
  };
  "hopper_0_1" = hopper_0_1_0;
  "hopper_0" = hopper_0_1_0;}