#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  gjio_0_1_0 = buildCratesLib {
    name = "gjio";
    version = "0.1.0";
    hash = "5eb76398fd53d432d8cc8e2e4edde2bc24801f8540598e1bb464794755d55970";
    deps = with allCrates; [  all__time.time_0_1 all__net2.net2_0_2 all__miow.miow_0_1 all__nix.nix_0_5 all__gj.gj_0_2 ];
  };
  gjio_0_1_1 = buildCratesLib {
    name = "gjio";
    version = "0.1.1";
    hash = "64cef7ff0c36c04dc3e628f0ce0ca34925861984433dd5132ea66305b9d3543e";
    deps = with allCrates; [  all__time.time_0_1 all__gj.gj_0_2 all__nix.nix_0_5 ];
  };
  gjio_0_1_2 = buildCratesLib {
    name = "gjio";
    version = "0.1.2";
    hash = "887d5b0b66eb67408d39c2c5089096db328d9aa7e249e946b93918ce6aec06e1";
    deps = with allCrates; [  all__time.time_0_1 all__gj.gj_0_2 all__nix.nix_0_5 ];
  };
  gjio_0_1_3 = buildCratesLib {
    name = "gjio";
    version = "0.1.3";
    hash = "9f446e12c11c70a45cddda1ad44186e4858362267c6afb8ff455ea442abfcbc9";
    deps = with allCrates; [  all__time.time_0_1 all__gj.gj_0_2 all__nix.nix_0_5 ];
  };
  "gjio_0_1" = gjio_0_1_3;
  "gjio_0" = gjio_0_1_3;}