#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  jsonnet-sys_0_5_0 = buildCratesLib {
    name = "jsonnet-sys";
    version = "0.5.0";
    hash = "c6319aa97774826e07c1a9d0ab791cd9672cd1cc1701d70cbcfd52971efc24eb";
    deps = with allCrates; [  all__libc.libc_0_2 all__gcc.gcc_0_3 ];
  };
  "jsonnet-sys_0_5" = jsonnet-sys_0_5_0;
  "jsonnet-sys_0" = jsonnet-sys_0_5_0;}