#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  zero-formatter_0_1_0 = buildCratesLib {
    name = "zero-formatter";
    version = "0.1.0";
    hash = "6835ee152038384d02f4b541faac63b144a2659f64e5aec03a92f8eaccefc87a";
    deps = with allCrates; [  all__chrono.chrono_0_2 all__byteorder.byteorder_1_0 ];
  };
  "zero-formatter_0_1" = zero-formatter_0_1_0;
  "zero-formatter_0" = zero-formatter_0_1_0;}