#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rbpf_0_0_1 = buildCratesLib {
    name = "rbpf";
    version = "0.0.1";
    hash = "14d328cdb324fd91f8b19706084afec69d566ebeec04aa5f43b5bdc0360274bd";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  rbpf_0_0_2 = buildCratesLib {
    name = "rbpf";
    version = "0.0.2";
    hash = "4a86d724878ccfa8687283434bc81cce69009ce6b3c6e4645e0c805d4bede4a6";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  "rbpf_0_0" = rbpf_0_0_2;
  "rbpf_0" = rbpf_0_0_2;}