#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  lopdf_0_1_0 = buildCratesLib {
    name = "lopdf";
    version = "0.1.0";
    hash = "df8bda2bc6bcfea416141cd68af09fd6741a4457bd7667795e047114c08f4ef2";
    deps = with allCrates; [  all__nom.nom_2_0_1 ];
  };
  "lopdf_0_1" = lopdf_0_1_0;
  "lopdf_0" = lopdf_0_1_0;}