#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-ml1_beta1_1_0_0 = buildCratesLib {
    name = "google-ml1_beta1";
    version = "1.0.0";
    hash = "843b7b258ac2dffe5ed3a87056aa9c372fb42c47cf2b901a747fa926a770b55e";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__mime.mime_0_2 url ];
  };
  google-ml1_beta1_1_0_1 = buildCratesLib {
    name = "google-ml1_beta1";
    version = "1.0.1";
    hash = "44f19a1466c4a6d384e09aa50c94b59a58ed82b7c6f1c22b097a9b03e63fb589";
    deps = with allCrates; [  all__mime.mime_0_2 url all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__serde.serde_0_8 ];
  };
  google-ml1_beta1_1_0_2 = buildCratesLib {
    name = "google-ml1_beta1";
    version = "1.0.2";
    hash = "768d84d56388d1e34f69daa2366ee0af190d6a817ce74f9348e66098d60d2069";
    deps = with allCrates; [  all__mime.mime_0_2 all__serde.serde_0_8 url all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 ];
  };
  "google-ml1_beta1_1_0" = google-ml1_beta1_1_0_2;
  "google-ml1_beta1_1" = google-ml1_beta1_1_0_2;}