#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-doubleclicksearch2-cli_0_3_6 = buildCratesLib {
    name = "google-doubleclicksearch2-cli";
    version = "0.3.6";
    hash = "b532233eb6b6b084ecc979bc4846d9f74f7b5719bf1006ff51981e63ad046d5d";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__clap.clap_2_0 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde.serde_0_8 all__mime.mime_0_2 all__strsim.strsim_0_5 ];
  };
  google-doubleclicksearch2-cli_1_0_0 = buildCratesLib {
    name = "google-doubleclicksearch2-cli";
    version = "1.0.0";
    hash = "2fd8532eee38af4b2d94c03d0dbfa572798ee6bf89477de776c9465210b5be14";
    deps = with allCrates; [  all__clap.clap_2_0 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde_json.serde_json_0_8 all__strsim.strsim_0_5 all__mime.mime_0_2 all__serde.serde_0_8 all__hyper.hyper_0_9 ];
  };
  "google-doubleclicksearch2-cli_0_3" = google-doubleclicksearch2-cli_0_3_6;
  "google-doubleclicksearch2-cli_0" = google-doubleclicksearch2-cli_0_3_6;
  "google-doubleclicksearch2-cli_1_0" = google-doubleclicksearch2-cli_1_0_0;
  "google-doubleclicksearch2-cli_1" = google-doubleclicksearch2-cli_1_0_0;}