#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-manufacturers1_1_0_0 = buildCratesLib {
    name = "google-manufacturers1";
    version = "1.0.0";
    hash = "d86345c3f8d5313e94e3e5624aaa003ce67b90927403ffbe0a78844d8a535152";
    deps = with allCrates; [  all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__mime.mime_0_2 all__hyper.hyper_0_9 url ];
  };
  "google-manufacturers1_1_0" = google-manufacturers1_1_0_0;
  "google-manufacturers1_1" = google-manufacturers1_1_0_0;}