#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-replicapoolupdater1_beta1-cli_0_3_6 = buildCratesLib {
    name = "google-replicapoolupdater1_beta1-cli";
    version = "0.3.6";
    hash = "1a19b2b33b1a2deabe2f07c81de141a1144ffd4bceefa87edd81aca772609e1d";
    deps = with allCrates; [  all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__mime.mime_0_2 all__strsim.strsim_0_5 all__clap.clap_2_0 all__yup-hyper-mock.yup-hyper-mock_1_0 ];
  };
  google-replicapoolupdater1_beta1-cli_1_0_0 = buildCratesLib {
    name = "google-replicapoolupdater1_beta1-cli";
    version = "1.0.0";
    hash = "be7546ce87ae033aecd62e83d6e41b6160832f09c4a99ae3ca9d2b6cc2245538";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__strsim.strsim_0_5 all__yup-hyper-mock.yup-hyper-mock_1_0 all__clap.clap_2_0 all__serde.serde_0_8 all__mime.mime_0_2 all__serde_json.serde_json_0_8 ];
  };
  "google-replicapoolupdater1_beta1-cli_0_3" = google-replicapoolupdater1_beta1-cli_0_3_6;
  "google-replicapoolupdater1_beta1-cli_0" = google-replicapoolupdater1_beta1-cli_0_3_6;
  google-replicapoolupdater1_beta1-cli_1_0_1 = buildCratesLib {
    name = "google-replicapoolupdater1_beta1-cli";
    version = "1.0.1";
    hash = "14795d9f03a0894ba5434f1b9781cd8628451e17e8fc866950af9f5448833ade";
    deps = with allCrates; [  all__clap.clap_2_0 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__mime.mime_0_2 all__strsim.strsim_0_5 all__serde.serde_0_8 all__yup-hyper-mock.yup-hyper-mock_1_0 ];
  };
  google-replicapoolupdater1_beta1-cli_1_0_2 = buildCratesLib {
    name = "google-replicapoolupdater1_beta1-cli";
    version = "1.0.2";
    hash = "1ac0daf8292fd4fd730475b217ddc928595c1aecd7491804ebe4c34c7e48e078";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__strsim.strsim_0_5 all__serde.serde_0_8 all__yup-hyper-mock.yup-hyper-mock_1_0 all__clap.clap_2_0 all__mime.mime_0_2 ];
  };
  "google-replicapoolupdater1_beta1-cli_1_0" = google-replicapoolupdater1_beta1-cli_1_0_2;
  "google-replicapoolupdater1_beta1-cli_1" = google-replicapoolupdater1_beta1-cli_1_0_2;}