#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-appstate1-cli_0_3_6 = buildCratesLib {
    name = "google-appstate1-cli";
    version = "0.3.6";
    hash = "4eb4f948dce7956afe3b7e0287d7c7c1c730bf38b42c9ac526c2d8992134e308";
    deps = with allCrates; [  all__mime.mime_0_2 all__serde.serde_0_8 all__strsim.strsim_0_5 all__serde_json.serde_json_0_8 all__yup-hyper-mock.yup-hyper-mock_1_0 all__clap.clap_2_0 all__hyper.hyper_0_9 ];
  };
  google-appstate1-cli_1_0_0 = buildCratesLib {
    name = "google-appstate1-cli";
    version = "1.0.0";
    hash = "1b648920d1fe5b98ea43753cb5e24976c0dc6fe2ab6b94d8a2157c82c88a71bc";
    deps = with allCrates; [  all__clap.clap_2_0 all__serde_json.serde_json_0_8 all__mime.mime_0_2 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde.serde_0_8 all__hyper.hyper_0_9 all__strsim.strsim_0_5 ];
  };
  "google-appstate1-cli_0_3" = google-appstate1-cli_0_3_6;
  "google-appstate1-cli_0" = google-appstate1-cli_0_3_6;
  "google-appstate1-cli_1_0" = google-appstate1-cli_1_0_0;
  "google-appstate1-cli_1" = google-appstate1-cli_1_0_0;}