#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-iam1-cli_0_3_6 = buildCratesLib {
    name = "google-iam1-cli";
    version = "0.3.6";
    hash = "97a2df8e87d85bb78ef8485a6905264270a94f0931963a2e6c0594703ab272b5";
    deps = with allCrates; [  all__clap.clap_2_0 all__mime.mime_0_2 all__yup-hyper-mock.yup-hyper-mock_1_0 all__hyper.hyper_0_9 all__strsim.strsim_0_5 all__serde_json.serde_json_0_8 all__serde.serde_0_8 ];
  };
  google-iam1-cli_1_0_0 = buildCratesLib {
    name = "google-iam1-cli";
    version = "1.0.0";
    hash = "4ec40dea3f71d2d88a3300e3dc964fe7fbf31b0192c68cb9b3b8db9893008e43";
    deps = with allCrates; [  all__serde.serde_0_8 all__mime.mime_0_2 all__serde_json.serde_json_0_8 all__clap.clap_2_0 all__hyper.hyper_0_9 all__yup-hyper-mock.yup-hyper-mock_1_0 all__strsim.strsim_0_5 ];
  };
  "google-iam1-cli_0_3" = google-iam1-cli_0_3_6;
  "google-iam1-cli_0" = google-iam1-cli_0_3_6;
  google-iam1-cli_1_0_1 = buildCratesLib {
    name = "google-iam1-cli";
    version = "1.0.1";
    hash = "2d5ae67e2d82d39727cb144873ee00c417193e2debf13faa0df5ad042a8618e6";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__mime.mime_0_2 all__clap.clap_2_0 all__hyper.hyper_0_9 all__strsim.strsim_0_5 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde.serde_0_8 ];
  };
  google-iam1-cli_1_0_2 = buildCratesLib {
    name = "google-iam1-cli";
    version = "1.0.2";
    hash = "cebeb6c7e79426a15322aca29310ac880adcb1f96f39dbb92b9e0e3675b70d84";
    deps = with allCrates; [  all__strsim.strsim_0_5 all__mime.mime_0_2 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__yup-hyper-mock.yup-hyper-mock_1_0 all__clap.clap_2_0 all__hyper.hyper_0_9 ];
  };
  "google-iam1-cli_1_0" = google-iam1-cli_1_0_2;
  "google-iam1-cli_1" = google-iam1-cli_1_0_2;}