#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-container1-cli_0_3_6 = buildCratesLib {
    name = "google-container1-cli";
    version = "0.3.6";
    hash = "2594f05033ecc27e6684e4a6c1f6557da68ab9f6403756dcf6c4c0e1c9509009";
    deps = with allCrates; [  all__strsim.strsim_0_5 all__clap.clap_2_0 all__mime.mime_0_2 all__hyper.hyper_0_9 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde_json.serde_json_0_8 all__serde.serde_0_8 ];
  };
  google-container1-cli_1_0_0 = buildCratesLib {
    name = "google-container1-cli";
    version = "1.0.0";
    hash = "5c07bd7668db9af0438cf0ac286e23edb98e20e490f68d8e310b8b18be096f01";
    deps = with allCrates; [  all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__strsim.strsim_0_5 all__clap.clap_2_0 all__mime.mime_0_2 all__serde.serde_0_8 ];
  };
  "google-container1-cli_0_3" = google-container1-cli_0_3_6;
  "google-container1-cli_0" = google-container1-cli_0_3_6;
  google-container1-cli_1_0_1 = buildCratesLib {
    name = "google-container1-cli";
    version = "1.0.1";
    hash = "1f9210d112f65986a5e241a644676017444b7c256b177c3daaae3bacb0203814";
    deps = with allCrates; [  all__yup-hyper-mock.yup-hyper-mock_1_0 all__hyper.hyper_0_9 all__serde.serde_0_8 all__strsim.strsim_0_5 all__clap.clap_2_0 all__mime.mime_0_2 all__serde_json.serde_json_0_8 ];
  };
  google-container1-cli_1_0_2 = buildCratesLib {
    name = "google-container1-cli";
    version = "1.0.2";
    hash = "ae077c5a2e688cd025bf5e9f2b071e6ceb1c316e9e59fb08d7446aac5841acca";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde.serde_0_8 all__yup-hyper-mock.yup-hyper-mock_1_0 all__mime.mime_0_2 all__clap.clap_2_0 all__strsim.strsim_0_5 all__serde_json.serde_json_0_8 ];
  };
  "google-container1-cli_1_0" = google-container1-cli_1_0_2;
  "google-container1-cli_1" = google-container1-cli_1_0_2;}