#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-deploymentmanager2_beta2_0_1_9 = buildCratesLib {
    name = "google-deploymentmanager2_beta2";
    version = "0.1.9";
    hash = "550e68afa112b70c26b819bb12aa0de54048aa214629c9833bfa0cf7febe52cb";
    deps = with allCrates; [  serde_json hyper yup-oauth2 serde all__mime.mime_0_1 url syntex serde_codegen ];
  };
  google-deploymentmanager2_beta2_0_1_10 = buildCratesLib {
    name = "google-deploymentmanager2_beta2";
    version = "0.1.10";
    hash = "6141eccbbd573b6853134b51240af41f07d2106730c10b95081945f92e89573b";
    deps = with allCrates; [  serde yup-oauth2 serde_json url all__mime.mime_0_1 all__hyper.hyper_0_7 serde_codegen syntex ];
  };
  google-deploymentmanager2_beta2_0_1_11 = buildCratesLib {
    name = "google-deploymentmanager2_beta2";
    version = "0.1.11";
    hash = "1b705b3acd941a502380941529bd653dbd7fe224bd1164c61ee3b8d2699a392c";
    deps = with allCrates; [  url all__hyper.hyper_0_7 yup-oauth2 all__mime.mime_0_1 serde serde_json serde_codegen syntex ];
  };
  google-deploymentmanager2_beta2_0_1_14 = buildCratesLib {
    name = "google-deploymentmanager2_beta2";
    version = "0.1.14";
    hash = "89dd342fc828139b491829f858e00afe1bcf70cb7b74354b6c8422b1dbea4e5c";
    deps = with allCrates; [  url all__hyper.hyper_0_9 all__mime.mime_0_2 all__serde.serde_0_7 all__serde_json.serde_json_0_7 ];
  };
  google-deploymentmanager2_beta2_0_1_15 = buildCratesLib {
    name = "google-deploymentmanager2_beta2";
    version = "0.1.15";
    hash = "6e8f827f41e4a180f760b0c6973e24ee24ad88aeaeb6190aa15d416d9eb2cea3";
    deps = with allCrates; [  all__hyper.hyper_0_9 url all__serde_json.serde_json_0_8 all__mime.mime_0_2 all__serde.serde_0_8 ];
  };
  google-deploymentmanager2_beta2_1_0_0 = buildCratesLib {
    name = "google-deploymentmanager2_beta2";
    version = "1.0.0";
    hash = "8f0acbdfb4dfb6ec9477e07164c662b9ac7fd96270368e708e8f5e2661a35bbd";
    deps = with allCrates; [  all__mime.mime_0_2 all__serde.serde_0_8 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 url ];
  };
  "google-deploymentmanager2_beta2_0_1" = google-deploymentmanager2_beta2_0_1_15;
  "google-deploymentmanager2_beta2_0" = google-deploymentmanager2_beta2_0_1_15;
  google-deploymentmanager2_beta2_1_0_1 = buildCratesLib {
    name = "google-deploymentmanager2_beta2";
    version = "1.0.1";
    hash = "4c95031392a5b65c0733279b92dcd16855b5a20370875b77faeb8c17353000c3";
    deps = with allCrates; [  all__mime.mime_0_2 all__serde_json.serde_json_0_8 url all__serde.serde_0_8 all__hyper.hyper_0_9 ];
  };
  google-deploymentmanager2_beta2_1_0_2 = buildCratesLib {
    name = "google-deploymentmanager2_beta2";
    version = "1.0.2";
    hash = "bbb7e519b14f586fff228a4d8b872edf1e2a160c96c9325bd00afbf1a3da2caa";
    deps = with allCrates; [  all__serde.serde_0_8 all__mime.mime_0_2 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 url ];
  };
  "google-deploymentmanager2_beta2_1_0" = google-deploymentmanager2_beta2_1_0_2;
  "google-deploymentmanager2_beta2_1" = google-deploymentmanager2_beta2_1_0_2;}