#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-pubsub1_beta2_0_1_3 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.3";
    hash = "a2e0bfa4d944dbd2b552cbae1f70837e3942d189d366a1d93ed8073ac8743739";
    deps = with allCrates; [  mime serde_macros yup-oauth2 url serde hyper ];
  };
  google-pubsub1_beta2_0_1_4 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.4";
    hash = "9720caca273247ec1654229bdd6015c841a4aff57747e3fbbc202ece6971db3c";
    deps = with allCrates; [  yup-oauth2 url serde_macros serde hyper mime ];
  };
  google-pubsub1_beta2_0_1_5 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.5";
    hash = "f1ffb6e2878fac8f4782bc6471e2e20e304c383826fdf83c879be50caeb010ad";
    deps = with allCrates; [  serde_macros hyper mime yup-oauth2 url serde ];
  };
  google-pubsub1_beta2_0_1_6 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.6";
    hash = "e81b2c3e4792cca418dd6da00e955230995788466db329a71f4d61b7488a44a6";
    deps = with allCrates; [  hyper serde mime serde_macros yup-oauth2 url ];
  };
  google-pubsub1_beta2_0_1_7 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.7";
    hash = "ee6ceba9b83a763c6f61a9c49b794d7ec194b1e6a819073005e0ea0b50b74bc9";
    deps = with allCrates; [  json-tools serde url serde_macros hyper yup-oauth2 mime ];
  };
  google-pubsub1_beta2_0_1_8 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.8";
    hash = "cea69319191e7c8f38060561efe9463a8eb771f9c474196b399ea7c58bb7d95e";
    deps = with allCrates; [  yup-oauth2 all__mime.mime_0_0_11 url hyper serde serde_codegen syntex ];
  };
  google-pubsub1_beta2_0_1_9 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.9";
    hash = "e6bc832dbc98d5fa412c02f9dec040b084eeb8332f7c1ad6d1114b931a1a7939";
    deps = with allCrates; [  serde hyper serde_json yup-oauth2 url all__mime.mime_0_1 serde_codegen syntex ];
  };
  google-pubsub1_beta2_0_1_10 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.10";
    hash = "802239701727b695339c589524d74bb0c3be9a28043ebaa6a0a67ce237101184";
    deps = with allCrates; [  serde_json all__mime.mime_0_1 url serde yup-oauth2 all__hyper.hyper_0_7 serde_codegen syntex ];
  };
  google-pubsub1_beta2_0_1_11 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.11";
    hash = "0d003650893e1341c350e0fe93b9b672fca902818ce80c94894ff48f4b29aa00";
    deps = with allCrates; [  url all__hyper.hyper_0_7 serde serde_json yup-oauth2 all__mime.mime_0_1 serde_codegen syntex ];
  };
  google-pubsub1_beta2_0_1_13 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.13";
    hash = "b42ed69427231b13bfef7aa045719bbcb9c84ccf47e0d1bc6bb0a630d21c9ef1";
    deps = with allCrates; [  url all__hyper.hyper_0_8 yup-oauth2 all__serde.serde_0_6 all__mime.mime_0_2 all__serde_json.serde_json_0_6 syntex serde_codegen ];
  };
  google-pubsub1_beta2_0_1_14 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.14";
    hash = "d356b1aa8f4688397ed86a516f0462a9c1d44d9aa4aa51a089ceee048fb36ca8";
    deps = with allCrates; [  all__mime.mime_0_2 all__serde.serde_0_7 url all__hyper.hyper_0_9 all__serde_json.serde_json_0_7 ];
  };
  google-pubsub1_beta2_0_1_15 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "0.1.15";
    hash = "accc8690b91388643d534147273004fe43016cd3df775b7970e10b81d39fa610";
    deps = with allCrates; [  url all__serde.serde_0_8 all__mime.mime_0_2 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 ];
  };
  google-pubsub1_beta2_1_0_0 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "1.0.0";
    hash = "cfb678a19abe7b71b6445d9b21a18cdcddf2b8ce3922f0ed555d355dfb46afbb";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 url all__serde.serde_0_8 all__hyper.hyper_0_9 all__mime.mime_0_2 ];
  };
  "google-pubsub1_beta2_0_1" = google-pubsub1_beta2_0_1_15;
  "google-pubsub1_beta2_0" = google-pubsub1_beta2_0_1_15;
  google-pubsub1_beta2_1_0_1 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "1.0.1";
    hash = "a929a7b041051489d2bd6bf0908591ef74fb1178f5fe2a6b8d938c5c5f0eac71";
    deps = with allCrates; [  all__serde.serde_0_8 all__mime.mime_0_2 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 url ];
  };
  google-pubsub1_beta2_1_0_2 = buildCratesLib {
    name = "google-pubsub1_beta2";
    version = "1.0.2";
    hash = "dc9a5ae79170eece70502b310cb0782e3acd92b593a2dd57eb24c2c1dee0dcfe";
    deps = with allCrates; [  all__mime.mime_0_2 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__serde.serde_0_8 url ];
  };
  "google-pubsub1_beta2_1_0" = google-pubsub1_beta2_1_0_2;
  "google-pubsub1_beta2_1" = google-pubsub1_beta2_1_0_2;}