#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-cloudbilling1-cli_0_3_6 = buildCratesLib {
    name = "google-cloudbilling1-cli";
    version = "0.3.6";
    hash = "d7ec837ab62ea0d649e9019044d33557459a29dc4ead047a1cac483318b7eb14";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__mime.mime_0_2 all__strsim.strsim_0_5 all__clap.clap_2_0 all__serde.serde_0_8 all__yup-hyper-mock.yup-hyper-mock_1_0 ];
  };
  google-cloudbilling1-cli_1_0_0 = buildCratesLib {
    name = "google-cloudbilling1-cli";
    version = "1.0.0";
    hash = "61d7d6a1c4cb5c770a7db1792ae70b326c6d1241a6bfea0eea024e84676870cb";
    deps = with allCrates; [  all__serde.serde_0_8 all__yup-hyper-mock.yup-hyper-mock_1_0 all__mime.mime_0_2 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__strsim.strsim_0_5 all__clap.clap_2_0 ];
  };
  "google-cloudbilling1-cli_0_3" = google-cloudbilling1-cli_0_3_6;
  "google-cloudbilling1-cli_0" = google-cloudbilling1-cli_0_3_6;
  google-cloudbilling1-cli_1_0_1 = buildCratesLib {
    name = "google-cloudbilling1-cli";
    version = "1.0.1";
    hash = "7630fd0bafe7157a082e80510066d3aa56f8f80b83df7dcf7f200b730906b9a2";
    deps = with allCrates; [  all__clap.clap_2_0 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__strsim.strsim_0_5 all__mime.mime_0_2 all__hyper.hyper_0_9 ];
  };
  google-cloudbilling1-cli_1_0_2 = buildCratesLib {
    name = "google-cloudbilling1-cli";
    version = "1.0.2";
    hash = "000603359e8f6204c94eace144b631e56b45470726fcbbf6c1e96185231725f3";
    deps = with allCrates; [  all__serde.serde_0_8 all__strsim.strsim_0_5 all__yup-hyper-mock.yup-hyper-mock_1_0 all__mime.mime_0_2 all__clap.clap_2_0 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 ];
  };
  "google-cloudbilling1-cli_1_0" = google-cloudbilling1-cli_1_0_2;
  "google-cloudbilling1-cli_1" = google-cloudbilling1-cli_1_0_2;}