#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-bigquery2-cli_0_3_6 = buildCratesLib {
    name = "google-bigquery2-cli";
    version = "0.3.6";
    hash = "7cad3e95d578a884eb6343ee8f820f411960528e74c969408c8b97e94e160744";
    deps = with allCrates; [  all__yup-hyper-mock.yup-hyper-mock_1_0 all__mime.mime_0_2 all__hyper.hyper_0_9 all__strsim.strsim_0_5 all__clap.clap_2_0 all__serde.serde_0_8 all__serde_json.serde_json_0_8 ];
  };
  google-bigquery2-cli_1_0_0 = buildCratesLib {
    name = "google-bigquery2-cli";
    version = "1.0.0";
    hash = "de9ba36a10109a58db9dbdf3272898a7cb243900965d6b7229b50dc6d16b038b";
    deps = with allCrates; [  all__serde.serde_0_8 all__yup-hyper-mock.yup-hyper-mock_1_0 all__clap.clap_2_0 all__mime.mime_0_2 all__strsim.strsim_0_5 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 ];
  };
  "google-bigquery2-cli_0_3" = google-bigquery2-cli_0_3_6;
  "google-bigquery2-cli_0" = google-bigquery2-cli_0_3_6;
  "google-bigquery2-cli_1_0" = google-bigquery2-cli_1_0_0;
  "google-bigquery2-cli_1" = google-bigquery2-cli_1_0_0;}