#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-sqladmin1_beta4_0_1_0 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.0";
    hash = "f7ee551145167cc7019c64ef2a732983cf55445250aec98e73e0dc39eb830293";
    deps = with allCrates; [  url mime yup-oauth2 hyper serde serde_macros ];
  };
  google-sqladmin1_beta4_0_1_1 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.1";
    hash = "0c9c400462e765ae6b11c8cd8cdf9a7edef93ec372ac756dcf01c8a8be2493ed";
    deps = with allCrates; [  yup-oauth2 url serde serde_macros hyper mime ];
  };
  google-sqladmin1_beta4_0_1_2 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.2";
    hash = "39a1ace48619fb5c9f2f8821bbcfd890023af6b04f0e341ae05ca99aa9f428b1";
    deps = with allCrates; [  serde_macros mime url yup-oauth2 hyper serde ];
  };
  google-sqladmin1_beta4_0_1_3 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.3";
    hash = "dd70dfd53cb78716ff62ceb96cf24565410875bea62876c2d3a06a120711ac7c";
    deps = with allCrates; [  serde mime url yup-oauth2 serde_macros hyper ];
  };
  google-sqladmin1_beta4_0_1_4 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.4";
    hash = "bc3a2004f12e2adbcf83e0666f91ded7e5151adc9fd9a387b239181ffe4ba11c";
    deps = with allCrates; [  url serde_macros yup-oauth2 hyper mime serde ];
  };
  google-sqladmin1_beta4_0_1_5 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.5";
    hash = "062345973c4fbed703c175fab7d1fd4759f1c0933046401fa63b4405e0ccc88a";
    deps = with allCrates; [  serde hyper url mime yup-oauth2 serde_macros ];
  };
  google-sqladmin1_beta4_0_1_6 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.6";
    hash = "4491fd1341657954c892cb8dc6d4e85e56410979e6e6cb5fecd45d56909d0921";
    deps = with allCrates; [  yup-oauth2 serde hyper serde_macros mime url ];
  };
  google-sqladmin1_beta4_0_1_7 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.7";
    hash = "e7a5bbb72f7ccd942aa5d4bc44802fe0bea27887779bcd2fe67666b272c6869b";
    deps = with allCrates; [  serde_macros mime yup-oauth2 hyper serde json-tools url ];
  };
  google-sqladmin1_beta4_0_1_8 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.8";
    hash = "664f242dd7c7534291b33f476e492aa475fbd9a8662e679a4dbf6d35f81cfaaa";
    deps = with allCrates; [  serde url yup-oauth2 hyper all__mime.mime_0_0_11 syntex serde_codegen ];
  };
  google-sqladmin1_beta4_0_1_9 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.9";
    hash = "b394c5596b1b11e2b3f2fc093c4f9a39ae3faeeee98cbe9790243a65bb02040d";
    deps = with allCrates; [  all__mime.mime_0_1 yup-oauth2 url serde_json hyper serde syntex serde_codegen ];
  };
  google-sqladmin1_beta4_0_1_10 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.10";
    hash = "d0e2944a651ffa0ecce57ab3548422088db7336ba6e27b5bcfb80db1497a7089";
    deps = with allCrates; [  yup-oauth2 serde_json all__hyper.hyper_0_7 all__mime.mime_0_1 serde url syntex serde_codegen ];
  };
  google-sqladmin1_beta4_0_1_11 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.11";
    hash = "c6ed654063e60d41e3522a29074a2b92b7299426826366787ccb83febd8f69da";
    deps = with allCrates; [  all__mime.mime_0_1 serde all__hyper.hyper_0_7 serde_json url yup-oauth2 serde_codegen syntex ];
  };
  google-sqladmin1_beta4_0_1_13 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.13";
    hash = "62ebd0948f5ea0d95c78891b05b40a2d8cbfd18217c581fa8cf15bf80e21d245";
    deps = with allCrates; [  all__hyper.hyper_0_8 all__serde_json.serde_json_0_6 url all__serde.serde_0_6 all__mime.mime_0_2 yup-oauth2 serde_codegen syntex ];
  };
  google-sqladmin1_beta4_0_1_14 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.14";
    hash = "1929a6bc2203d3421bf9febecf9e89a8358f45ab499b122c418a22923158dba3";
    deps = with allCrates; [  all__serde.serde_0_8 all__mime.mime_0_2 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 url ];
  };
  google-sqladmin1_beta4_0_1_15 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "0.1.15";
    hash = "be52aa72350d02ed72979670bd46a7d0911498f2678c85fd8e547d3f121c9611";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 url all__mime.mime_0_2 all__serde.serde_0_8 ];
  };
  google-sqladmin1_beta4_1_0_0 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "1.0.0";
    hash = "008b196fb69bb6d2f32a5767fb465df1659cd7c62751d59ef828919b2d03bcfa";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__mime.mime_0_2 url all__hyper.hyper_0_9 ];
  };
  "google-sqladmin1_beta4_0_1" = google-sqladmin1_beta4_0_1_15;
  "google-sqladmin1_beta4_0" = google-sqladmin1_beta4_0_1_15;
  google-sqladmin1_beta4_1_0_1 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "1.0.1";
    hash = "ef9cefb7e5f33adbb3ddaf7b79d9162ff5f8e4c0a837f7575610a574428246e8";
    deps = with allCrates; [  all__serde.serde_0_8 all__mime.mime_0_2 url all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 ];
  };
  google-sqladmin1_beta4_1_0_2 = buildCratesLib {
    name = "google-sqladmin1_beta4";
    version = "1.0.2";
    hash = "19655d61417866b39ccb55a375f0d857fa2b2bc7e35c0cfee4b6fc2fd655c146";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__mime.mime_0_2 all__serde.serde_0_8 url all__hyper.hyper_0_9 ];
  };
  "google-sqladmin1_beta4_1_0" = google-sqladmin1_beta4_1_0_2;
  "google-sqladmin1_beta4_1" = google-sqladmin1_beta4_1_0_2;}