#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-androidpublisher2_0_1_0 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.0";
    hash = "4f3737224a80bf28d64eb33f05004071d2df55afee7a999e2e94f6225e8ffb0d";
    deps = with allCrates; [  hyper serde_macros yup-oauth2 serde mime url ];
  };
  google-androidpublisher2_0_1_1 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.1";
    hash = "86eb352a6d27b3863fa06a2092e6c117ffe01635a4dcecd99bfdc42a6e372bd9";
    deps = with allCrates; [  mime serde_macros url hyper yup-oauth2 serde ];
  };
  google-androidpublisher2_0_1_2 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.2";
    hash = "6bf2cef81e6034bedf5e75cbf2ad525997da3f2125b221ce031d1405116dc4d2";
    deps = with allCrates; [  serde_macros yup-oauth2 mime url hyper serde ];
  };
  google-androidpublisher2_0_1_3 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.3";
    hash = "4258aaab290b2f4311ad33e587b0df82c86ea22c6cb1634bf2a9f2a1a574a116";
    deps = with allCrates; [  url serde_macros yup-oauth2 mime hyper serde ];
  };
  google-androidpublisher2_0_1_4 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.4";
    hash = "b3b1f72a32b991b3a85d84b0347e5f12a7a3b4204af2755a2dbb5f5f12a09613";
    deps = with allCrates; [  yup-oauth2 serde_macros hyper serde url mime ];
  };
  google-androidpublisher2_0_1_5 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.5";
    hash = "52a171dcb1950f7d5a022b4541486ad2df8c972cb7678261b4b3e6065fd4ffad";
    deps = with allCrates; [  serde_macros hyper serde url mime yup-oauth2 ];
  };
  google-androidpublisher2_0_1_6 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.6";
    hash = "dddfb725ef82ce271dd68335b802f4882a219d8943607376dc5448da670f6509";
    deps = with allCrates; [  serde_macros hyper yup-oauth2 serde url mime ];
  };
  google-androidpublisher2_0_1_7 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.7";
    hash = "d98c9660f327f2bb42dba271d311504dee1e36d6a2661a7079fdb1752ab00f38";
    deps = with allCrates; [  url json-tools serde_macros yup-oauth2 hyper serde mime ];
  };
  google-androidpublisher2_0_1_8 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.8";
    hash = "492398c681b561c4b932935b65df952c41fec79047296647d3bc540cc266f66f";
    deps = with allCrates; [  yup-oauth2 serde hyper all__mime.mime_0_0_11 url syntex serde_codegen ];
  };
  google-androidpublisher2_0_1_9 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.9";
    hash = "0b983d002a5e173a9bc0e8879e4802b77fbad5ecdf92affb2534bf2617974ba6";
    deps = with allCrates; [  url all__mime.mime_0_1 serde_json hyper serde yup-oauth2 syntex serde_codegen ];
  };
  google-androidpublisher2_0_1_10 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.10";
    hash = "7312e717afeb1d3a2191c9be71c58e6dea2de8066537dab4ccdabb161b8b523d";
    deps = with allCrates; [  serde serde_json yup-oauth2 url all__mime.mime_0_1 all__hyper.hyper_0_7 serde_codegen syntex ];
  };
  google-androidpublisher2_0_1_11 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.11";
    hash = "af7821d685b2481442ae2623d20169f78683e90de338f389bb3e2c292da3e82d";
    deps = with allCrates; [  yup-oauth2 all__hyper.hyper_0_7 serde_json serde url all__mime.mime_0_1 syntex serde_codegen ];
  };
  google-androidpublisher2_0_1_13 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.13";
    hash = "aca2cdc4f842a9ff5af6cce3e8fc957af3b70a262727615de254ba381674c27c";
    deps = with allCrates; [  url yup-oauth2 all__serde.serde_0_6 all__serde_json.serde_json_0_6 all__mime.mime_0_2 all__hyper.hyper_0_8 serde_codegen syntex ];
  };
  google-androidpublisher2_0_1_14 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.14";
    hash = "e5d2448ed68ff664c3dd87d32e4a6a2ccf574784d287c543bc042f182d0c7a25";
    deps = with allCrates; [  all__hyper.hyper_0_9 url all__serde_json.serde_json_0_8 all__mime.mime_0_2 all__serde.serde_0_8 ];
  };
  google-androidpublisher2_0_1_15 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "0.1.15";
    hash = "0c5509cb5fc4cf975032d30622118e26abfd91347c290762f133f8fb3e73883f";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__mime.mime_0_2 url all__hyper.hyper_0_9 all__serde.serde_0_8 ];
  };
  google-androidpublisher2_1_0_0 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "1.0.0";
    hash = "a664ec8c0511547fc9f17822837eeb20d335bd943884b82a80c1a77da06543fb";
    deps = with allCrates; [  url all__hyper.hyper_0_9 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__mime.mime_0_2 ];
  };
  "google-androidpublisher2_0_1" = google-androidpublisher2_0_1_15;
  "google-androidpublisher2_0" = google-androidpublisher2_0_1_15;
  google-androidpublisher2_1_0_1 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "1.0.1";
    hash = "5b3569a9e15e189f7c68df472a8a77d8727fe0e457883131484e3a3da4b6cdb5";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__mime.mime_0_2 url ];
  };
  google-androidpublisher2_1_0_2 = buildCratesLib {
    name = "google-androidpublisher2";
    version = "1.0.2";
    hash = "17b33053446ee6b2a8b8149006e5fc147b072bdb558c215c07d5d3661295c053";
    deps = with allCrates; [  url all__hyper.hyper_0_9 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__mime.mime_0_2 ];
  };
  "google-androidpublisher2_1_0" = google-androidpublisher2_1_0_2;
  "google-androidpublisher2_1" = google-androidpublisher2_1_0_2;}