#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-proximitybeacon1_beta1-cli_0_3_6 = buildCratesLib {
    name = "google-proximitybeacon1_beta1-cli";
    version = "0.3.6";
    hash = "ec4702ba45bb7e9ba444893e37e7e0021d223b7b4bbc079beb6213cd56e6ee32";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__mime.mime_0_2 all__clap.clap_2_0 all__strsim.strsim_0_5 all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__yup-hyper-mock.yup-hyper-mock_1_0 ];
  };
  google-proximitybeacon1_beta1-cli_1_0_0 = buildCratesLib {
    name = "google-proximitybeacon1_beta1-cli";
    version = "1.0.0";
    hash = "d9144b6b8a72e8dbb860d9246e15ab8f1d61930703763b42f5aaa6874d9e42ef";
    deps = with allCrates; [  all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__clap.clap_2_0 all__serde.serde_0_8 all__mime.mime_0_2 all__strsim.strsim_0_5 ];
  };
  "google-proximitybeacon1_beta1-cli_0_3" = google-proximitybeacon1_beta1-cli_0_3_6;
  "google-proximitybeacon1_beta1-cli_0" = google-proximitybeacon1_beta1-cli_0_3_6;
  google-proximitybeacon1_beta1-cli_1_0_1 = buildCratesLib {
    name = "google-proximitybeacon1_beta1-cli";
    version = "1.0.1";
    hash = "93067a37f4ab5315c3163f3ccc6b727729dd8ceea8d921e712614fa46d67f3ee";
    deps = with allCrates; [  all__clap.clap_2_0 all__hyper.hyper_0_9 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde_json.serde_json_0_8 all__mime.mime_0_2 all__serde.serde_0_8 all__strsim.strsim_0_5 ];
  };
  google-proximitybeacon1_beta1-cli_1_0_2 = buildCratesLib {
    name = "google-proximitybeacon1_beta1-cli";
    version = "1.0.2";
    hash = "88331885ffed250126aede70877bfec364f0b254999f181103a2fa46456039e2";
    deps = with allCrates; [  all__mime.mime_0_2 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde_json.serde_json_0_8 all__clap.clap_2_0 all__serde.serde_0_8 all__strsim.strsim_0_5 all__hyper.hyper_0_9 ];
  };
  "google-proximitybeacon1_beta1-cli_1_0" = google-proximitybeacon1_beta1-cli_1_0_2;
  "google-proximitybeacon1_beta1-cli_1" = google-proximitybeacon1_beta1-cli_1_0_2;}