#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-content2_0_1_0 = buildCratesLib {
    name = "google-content2";
    version = "0.1.0";
    hash = "3a0aed04116f8344319150d1acdf05c757160a9e00e128dbdcd32ee9b111c3f7";
    deps = with allCrates; [  yup-oauth2 serde_macros serde mime hyper url ];
  };
  google-content2_0_1_1 = buildCratesLib {
    name = "google-content2";
    version = "0.1.1";
    hash = "fd12579b674c7d981f89165d74a8ff7a432f0f86fd0d3e0a2dc92f1d93a04e8d";
    deps = with allCrates; [  serde hyper mime url yup-oauth2 serde_macros ];
  };
  google-content2_0_1_2 = buildCratesLib {
    name = "google-content2";
    version = "0.1.2";
    hash = "0b77d629477fd3d8c66b08e9481a2d9dc197349a9afcb18d563f13c7750df0e2";
    deps = with allCrates; [  url serde_macros hyper yup-oauth2 serde mime ];
  };
  google-content2_0_1_3 = buildCratesLib {
    name = "google-content2";
    version = "0.1.3";
    hash = "9fbc833894199b763c581951baa3fa7b41b5238d1072528cd47c8b9e3722189e";
    deps = with allCrates; [  hyper serde_macros yup-oauth2 mime serde url ];
  };
  google-content2_0_1_4 = buildCratesLib {
    name = "google-content2";
    version = "0.1.4";
    hash = "0131fff25bbe7d0b7398c5597450c8bca0b8d79f513a12a76d2957efbdec78e3";
    deps = with allCrates; [  hyper serde yup-oauth2 url serde_macros mime ];
  };
  google-content2_0_1_5 = buildCratesLib {
    name = "google-content2";
    version = "0.1.5";
    hash = "5f3763285fbfe3eb64c308be0272346bc2c2fbbddbfb0315555696e169c0e428";
    deps = with allCrates; [  mime serde_macros serde yup-oauth2 hyper url ];
  };
  google-content2_0_1_6 = buildCratesLib {
    name = "google-content2";
    version = "0.1.6";
    hash = "81ff1b9ff3048ddbad49023b60c784b4da7f149f94724568bab39e42d9ec30c9";
    deps = with allCrates; [  hyper yup-oauth2 url mime serde serde_macros ];
  };
  google-content2_0_1_7 = buildCratesLib {
    name = "google-content2";
    version = "0.1.7";
    hash = "b7b32c11b7e98c842caece93802238f6da259bcfaa772086b3fcde9cb49b6d5e";
    deps = with allCrates; [  mime hyper url serde_macros serde yup-oauth2 json-tools ];
  };
  google-content2_0_1_8 = buildCratesLib {
    name = "google-content2";
    version = "0.1.8";
    hash = "abaaa6f5ca1d0dc7d481207ea5242cf2a29ee4975e342e13a10ba9598857ce85";
    deps = with allCrates; [  all__mime.mime_0_0_11 url serde hyper yup-oauth2 syntex serde_codegen ];
  };
  google-content2_0_1_9 = buildCratesLib {
    name = "google-content2";
    version = "0.1.9";
    hash = "420ecd07cacdd54089a2a68207c88b896a68ecb908273dfc2973a78778d57ad4";
    deps = with allCrates; [  all__mime.mime_0_1 yup-oauth2 hyper url serde_json serde serde_codegen syntex ];
  };
  google-content2_0_1_10 = buildCratesLib {
    name = "google-content2";
    version = "0.1.10";
    hash = "197db0387f9ce2a099be27b793895d3f0e19abcc8439ce815cec0b693a1ea29f";
    deps = with allCrates; [  serde_json yup-oauth2 all__mime.mime_0_1 serde url all__hyper.hyper_0_7 serde_codegen syntex ];
  };
  google-content2_0_1_11 = buildCratesLib {
    name = "google-content2";
    version = "0.1.11";
    hash = "f330d6931a711b94bd20848ece99fc1017d83c49387918b586e25b5070b9c61c";
    deps = with allCrates; [  serde_json all__hyper.hyper_0_7 all__mime.mime_0_1 serde yup-oauth2 url serde_codegen syntex ];
  };
  google-content2_0_1_13 = buildCratesLib {
    name = "google-content2";
    version = "0.1.13";
    hash = "d326898c915626331b4541f6eeeb20c134a560899483f1a3e29e6d84de620bfe";
    deps = with allCrates; [  all__serde_json.serde_json_0_6 all__hyper.hyper_0_8 url all__serde.serde_0_6 yup-oauth2 all__mime.mime_0_2 syntex serde_codegen ];
  };
  google-content2_0_1_14 = buildCratesLib {
    name = "google-content2";
    version = "0.1.14";
    hash = "44ac3ff1a2bf97552175dac1e0096c0e43ba6e18cce354725067ff4ba813d1de";
    deps = with allCrates; [  all__serde.serde_0_8 all__mime.mime_0_2 all__hyper.hyper_0_9 url all__serde_json.serde_json_0_8 ];
  };
  google-content2_0_1_15 = buildCratesLib {
    name = "google-content2";
    version = "0.1.15";
    hash = "e62d0fcbc7344beb243fb3c4d546eecf17082db5e98e7d5cc5316aa661505d0c";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 url all__mime.mime_0_2 all__serde.serde_0_8 ];
  };
  google-content2_1_0_0 = buildCratesLib {
    name = "google-content2";
    version = "1.0.0";
    hash = "98141707f30c4d824c6ef30015adf7fa6d72242d876cba1dc55c9a3a2d9a3b2a";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 url all__serde.serde_0_8 all__mime.mime_0_2 ];
  };
  "google-content2_0_1" = google-content2_0_1_15;
  "google-content2_0" = google-content2_0_1_15;
  google-content2_1_0_1 = buildCratesLib {
    name = "google-content2";
    version = "1.0.1";
    hash = "999a8292f0e6b6ccb2391bd22df494743b65550cbf7dadd071843240d33a1156";
    deps = with allCrates; [  all__serde.serde_0_8 all__serde_json.serde_json_0_8 url all__hyper.hyper_0_9 all__mime.mime_0_2 ];
  };
  google-content2_1_0_2 = buildCratesLib {
    name = "google-content2";
    version = "1.0.2";
    hash = "42ba8b74f72a01036ff573859f67a7edd187d84190e3407c02c248a97edda851";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__serde.serde_0_8 url all__hyper.hyper_0_9 all__mime.mime_0_2 ];
  };
  "google-content2_1_0" = google-content2_1_0_2;
  "google-content2_1" = google-content2_1_0_2;}