#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-logging2-cli_1_0_0 = buildCratesLib {
    name = "google-logging2-cli";
    version = "1.0.0";
    hash = "bc2170402fa61b54164bdda759ad8fb10ea0d3dc386c3b1af68f4acaba8c9eed";
    deps = with allCrates; [  all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__strsim.strsim_0_5 all__hyper.hyper_0_9 all__mime.mime_0_2 all__clap.clap_2_0 ];
  };
  "google-logging2-cli_1_0" = google-logging2-cli_1_0_0;
  "google-logging2-cli_1" = google-logging2-cli_1_0_0;}