#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-cloudmonitoring2_beta2_0_1_0 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.0";
    hash = "f09dc0e8aede9abf12af1d305b6055bd879b9bcd4cf2142ce3e5d43678f558e0";
    deps = with allCrates; [  hyper serde serde_macros mime url yup-oauth2 ];
  };
  google-cloudmonitoring2_beta2_0_1_1 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.1";
    hash = "0d16e0c2e4ca1fb475d04293f411a2c83fbefbd451d8675ac9e7a253080116cf";
    deps = with allCrates; [  hyper yup-oauth2 mime serde_macros serde url ];
  };
  google-cloudmonitoring2_beta2_0_1_2 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.2";
    hash = "c120535ada93ac30a96f6f85bf91cc567f1145c354e6606e1898404906289a00";
    deps = with allCrates; [  hyper yup-oauth2 url serde serde_macros mime ];
  };
  google-cloudmonitoring2_beta2_0_1_3 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.3";
    hash = "ffd39fce69dd1dbeb2a33257e90a31fa38793677aab845224759ee1a32b46fa5";
    deps = with allCrates; [  mime url yup-oauth2 serde serde_macros hyper ];
  };
  google-cloudmonitoring2_beta2_0_1_4 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.4";
    hash = "6eb171f7e5c572dac43e13593029c2355e3e2780f5c91fd3725a0c0aabce709a";
    deps = with allCrates; [  url hyper serde yup-oauth2 mime serde_macros ];
  };
  google-cloudmonitoring2_beta2_0_1_5 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.5";
    hash = "8ecf879ee8dea253fbb4f02795088c310c295a619addf6fd01d0fd46a5fd453b";
    deps = with allCrates; [  mime yup-oauth2 url serde_macros hyper serde ];
  };
  google-cloudmonitoring2_beta2_0_1_6 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.6";
    hash = "b1cbb10c0c8617c5a21367eb61dafe91fa7536e5ace819c5d5cbfbf5942566f6";
    deps = with allCrates; [  yup-oauth2 mime hyper url serde_macros serde ];
  };
  google-cloudmonitoring2_beta2_0_1_7 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.7";
    hash = "8916dcd921a91969f85fc1a2680b6cc6145622b9acbb90c292321a608ea5c29d";
    deps = with allCrates; [  yup-oauth2 mime hyper json-tools serde_macros serde url ];
  };
  google-cloudmonitoring2_beta2_0_1_8 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.8";
    hash = "24a3a667b1f287113343142bbc33717d4c35965b0dadd2e73897f11b410cf165";
    deps = with allCrates; [  yup-oauth2 hyper url serde all__mime.mime_0_0_11 syntex serde_codegen ];
  };
  google-cloudmonitoring2_beta2_0_1_9 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.9";
    hash = "9d36e5d72680f5a8f2b8703a341a4f368d767f165662aa882a04c3fb28ef77d3";
    deps = with allCrates; [  url serde_json serde yup-oauth2 all__mime.mime_0_1 hyper serde_codegen syntex ];
  };
  google-cloudmonitoring2_beta2_0_1_10 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.10";
    hash = "c23e3bad0bd1a9302b6734f140bb90bef98356624725afe4c220619f3880809c";
    deps = with allCrates; [  all__hyper.hyper_0_7 yup-oauth2 serde_json url all__mime.mime_0_1 serde serde_codegen syntex ];
  };
  google-cloudmonitoring2_beta2_0_1_11 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.11";
    hash = "7629da319c65590cc903e1d68d33a56b96fe563343cbf38a43da45fb83b5ab83";
    deps = with allCrates; [  serde_json all__mime.mime_0_1 serde all__hyper.hyper_0_7 yup-oauth2 url serde_codegen syntex ];
  };
  google-cloudmonitoring2_beta2_0_1_12 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.12";
    hash = "709dc84257eccfc37cfe1ac06db2e27b9025271ae8001ca2a8c3ab206e92eeba";
    deps = with allCrates; [  serde_json url yup-oauth2 all__hyper.hyper_0_7 serde all__mime.mime_0_1 serde_codegen syntex ];
  };
  google-cloudmonitoring2_beta2_0_1_13 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.13";
    hash = "e4ce0a7affeadf0aa1170cd19f5e1f0a5b0960fe40ecb84073566f3247c02fb2";
    deps = with allCrates; [  all__hyper.hyper_0_8 all__mime.mime_0_2 yup-oauth2 all__serde_json.serde_json_0_6 url all__serde.serde_0_6 serde_codegen syntex ];
  };
  google-cloudmonitoring2_beta2_0_1_14 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.14";
    hash = "beb8e5448cc0325aeea5729265cacccb4c311bf89c24de0eaa21c0088b357d24";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__mime.mime_0_2 all__serde_json.serde_json_0_8 all__serde.serde_0_8 url ];
  };
  google-cloudmonitoring2_beta2_0_1_15 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "0.1.15";
    hash = "a9cde78c0663ad295a7ea66322d9a5246b7b0a785b1e7d3c1e75cd5845387b8a";
    deps = with allCrates; [  all__mime.mime_0_2 all__serde_json.serde_json_0_8 url all__serde.serde_0_8 all__hyper.hyper_0_9 ];
  };
  google-cloudmonitoring2_beta2_1_0_0 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "1.0.0";
    hash = "3c4ba3de2b50140e0f06750ae68e322d9a895da008ab815ce8c8ac1e43e8d692";
    deps = with allCrates; [  all__mime.mime_0_2 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__serde.serde_0_8 url ];
  };
  "google-cloudmonitoring2_beta2_0_1" = google-cloudmonitoring2_beta2_0_1_15;
  "google-cloudmonitoring2_beta2_0" = google-cloudmonitoring2_beta2_0_1_15;
  google-cloudmonitoring2_beta2_1_0_1 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "1.0.1";
    hash = "653e0c0c10a5fb082dd6eae6ef5754fd905011cb70c702b97021db4898018fd3";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__mime.mime_0_2 url ];
  };
  google-cloudmonitoring2_beta2_1_0_2 = buildCratesLib {
    name = "google-cloudmonitoring2_beta2";
    version = "1.0.2";
    hash = "057945d2d556f0482c5d5a3f582ce9e2e45794069b21d33a58e9cd0a21c090af";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__serde.serde_0_8 all__mime.mime_0_2 url ];
  };
  "google-cloudmonitoring2_beta2_1_0" = google-cloudmonitoring2_beta2_1_0_2;
  "google-cloudmonitoring2_beta2_1" = google-cloudmonitoring2_beta2_1_0_2;}