#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-people1-cli_0_3_6 = buildCratesLib {
    name = "google-people1-cli";
    version = "0.3.6";
    hash = "2ba4d37606d15b7bb5da7c52711f980bd7533016c893b34437463c69ebdd0aef";
    deps = with allCrates; [  all__mime.mime_0_2 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__clap.clap_2_0 all__hyper.hyper_0_9 all__strsim.strsim_0_5 ];
  };
  google-people1-cli_1_0_0 = buildCratesLib {
    name = "google-people1-cli";
    version = "1.0.0";
    hash = "ed6b7482ceb7d35dc40d20a9aa876694155ff2fe1189818cbec96567904ef08f";
    deps = with allCrates; [  all__clap.clap_2_0 all__strsim.strsim_0_5 all__mime.mime_0_2 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 ];
  };
  "google-people1-cli_0_3" = google-people1-cli_0_3_6;
  "google-people1-cli_0" = google-people1-cli_0_3_6;
  google-people1-cli_1_0_1 = buildCratesLib {
    name = "google-people1-cli";
    version = "1.0.1";
    hash = "15020c68fed94c05d695b3c9a993c14449b600dcf8e3c750e7b1af90e361237f";
    deps = with allCrates; [  all__yup-hyper-mock.yup-hyper-mock_1_0 all__clap.clap_2_0 all__mime.mime_0_2 all__hyper.hyper_0_9 all__serde.serde_0_8 all__strsim.strsim_0_5 all__serde_json.serde_json_0_8 ];
  };
  google-people1-cli_1_0_2 = buildCratesLib {
    name = "google-people1-cli";
    version = "1.0.2";
    hash = "4cfb7c9d73608d6b868c1738b39afe829d27a1f3439276c47f3c0389f62be9f3";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__clap.clap_2_0 all__yup-hyper-mock.yup-hyper-mock_1_0 all__hyper.hyper_0_9 all__serde.serde_0_8 all__strsim.strsim_0_5 all__mime.mime_0_2 ];
  };
  "google-people1-cli_1_0" = google-people1-cli_1_0_2;
  "google-people1-cli_1" = google-people1-cli_1_0_2;}