#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  zdaemon_0_0_2 = buildCratesLib {
    name = "zdaemon";
    version = "0.0.2";
    hash = "5b4d1c8c01a92b76bf5804ae11259d9455d733dcfed7a3a71e70fe99559baa39";
    deps = with allCrates; [  all__czmq.czmq_0_1 rustc-serialize ];
  };
  "zdaemon_0_0" = zdaemon_0_0_2;
  "zdaemon_0" = zdaemon_0_0_2;}