#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  mut_static_0_1_0 = buildCratesLib {
    name = "mut_static";
    version = "0.1.0";
    hash = "ddd651751ccd77068d52d899be65f6408c989f9623658c12a6994bb7e4f6dd1c";
    deps = with allCrates; [  all__error-chain.error-chain_0_7 ];
  };
  "mut_static_0_1" = mut_static_0_1_0;
  "mut_static_0" = mut_static_0_1_0;}