#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  sparseset_0_1_0 = buildCratesLib {
    name = "sparseset";
    version = "0.1.0";
    hash = "5f9409c8f04632dcd49c06545e2021307e618a8016d2f86b9b264e1860dfa018";
    deps = with allCrates; [  ];
  };
  "sparseset_0_1" = sparseset_0_1_0;
  "sparseset_0" = sparseset_0_1_0;}