#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rmpv_0_1_0 = buildCratesLib {
    name = "rmpv";
    version = "0.1.0";
    hash = "c5c2c2241f7879fc721ed505808b25435e32e7c9ce9bd678ac3c349b49ce6342";
    deps = with allCrates; [  all__rmp.rmp_0_8 ];
  };
  "rmpv_0_1" = rmpv_0_1_0;
  "rmpv_0" = rmpv_0_1_0;}