#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  libgpg-error-sys_0_1_0 = buildCratesLib {
    name = "libgpg-error-sys";
    version = "0.1.0";
    hash = "f55745f2c859c72dac6b2143bb56d19e7bc012bbde4ad3814f5b33aeeebbd9cf";
    deps = with allCrates; [  all__libc.libc_0_1 ];
  };
  libgpg-error-sys_0_1_1 = buildCratesLib {
    name = "libgpg-error-sys";
    version = "0.1.1";
    hash = "9affa8cb51711fa3790097fbae383ec602f002f8ca33f8d607c292afacddf426";
    deps = with allCrates; [  all__libc.libc_0_1 ];
  };
  libgpg-error-sys_0_1_2 = buildCratesLib {
    name = "libgpg-error-sys";
    version = "0.1.2";
    hash = "d4397f13e582abf8053a0394b6dc73428f343636e02c2c1969b564ca0311ecd8";
    deps = with allCrates; [  ];
  };
  libgpg-error-sys_0_1_4 = buildCratesLib {
    name = "libgpg-error-sys";
    version = "0.1.4";
    hash = "1eb0575b1c2be7c13bfb93034bda0d1ff61dd9faefb4804613312c9db1c94235";
    deps = with allCrates; [  ];
  };
  libgpg-error-sys_0_1_5 = buildCratesLib {
    name = "libgpg-error-sys";
    version = "0.1.5";
    hash = "3bb64fba126a92f112f2c707b2721d177c40dd916ccacda4b8f62446813b5142";
    deps = with allCrates; [  ];
  };
  libgpg-error-sys_0_1_6 = buildCratesLib {
    name = "libgpg-error-sys";
    version = "0.1.6";
    hash = "0fc7973a5e24a8cdb02a3d519102ae3b3a97efe63d6716a21590fdbd9a2d0772";
    deps = with allCrates; [  all__gcc.gcc_0_3 ];
  };
  libgpg-error-sys_0_2_0 = buildCratesLib {
    name = "libgpg-error-sys";
    version = "0.2.0";
    hash = "c7eeca3abfe83d8832fd5caf90a5f07ad03a540dddd7774b6757a92fe8ef9b4f";
    deps = with allCrates; [  all__gcc.gcc_0_3 ];
  };
  "libgpg-error-sys_0_1" = libgpg-error-sys_0_1_6;
  "libgpg-error-sys_0_2" = libgpg-error-sys_0_2_0;
  "libgpg-error-sys_0" = libgpg-error-sys_0_2_0;}