#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  epsilonz_0_0_1 = buildCratesLib {
    name = "epsilonz";
    version = "0.0.1";
    hash = "3d560cd099ba8ca3d6fd6d6b51a751cdd0868c5fa3086c97397182d4f48e76b3";
    deps = with allCrates; [  rope monad pretty pipes free fingertree epsilonz_algebra tailrec ];
  };
  epsilonz_0_0_2 = buildCratesLib {
    name = "epsilonz";
    version = "0.0.2";
    hash = "282d2ed68e9049cb68be45b3e089e2b65f92f04d02cec3bea9313aa0946e8f8b";
    deps = with allCrates; [  free free_macros epsilonz_algebra pretty rope monad_macros tailrec morphism pipes monad fingertree ];
  };
  "epsilonz_0_0" = epsilonz_0_0_2;
  "epsilonz_0" = epsilonz_0_0_2;}