#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  dcpu16_0_0_1 = buildCratesLib {
    name = "dcpu16";
    version = "0.0.1";
    hash = "d65f46372e0e3adffa0186409776c1b80e5f69ae4c6c540bf51f2cda2eec4c0c";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  dcpu16_0_0_2 = buildCratesLib {
    name = "dcpu16";
    version = "0.0.2";
    hash = "552ecb3e1da1dcd0864a98c38dd97b9d45a50ecbea92b6058301e089a6ff49de";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  dcpu16_0_0_3 = buildCratesLib {
    name = "dcpu16";
    version = "0.0.3";
    hash = "d9d6c81753bf781a8d19db7c4e73f381b72508345c8c4bf3e2d2c2f181fc1793";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  dcpu16_0_0_4 = buildCratesLib {
    name = "dcpu16";
    version = "0.0.4";
    hash = "8c1e787f295acebd4eba32e965c56335906ef7bbfaaa06af2a1350b712862dd4";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  dcpu16_0_0_5 = buildCratesLib {
    name = "dcpu16";
    version = "0.0.5";
    hash = "9d877ef936153a6262cf86196322e49e08b7bef3669dca733ec6fef3d8f15ba4";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  dcpu16_0_0_6 = buildCratesLib {
    name = "dcpu16";
    version = "0.0.6";
    hash = "a2a201e6569e459a2822c598bf2a1a60d4df19a5cab0f95df1da57f9f4ebd610";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  dcpu16_0_0_7 = buildCratesLib {
    name = "dcpu16";
    version = "0.0.7";
    hash = "d819ade84cfc65c770a8cf9bdfad64a19e96664d1a351904f1c0558f3ecc9202";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  dcpu16_0_1_0 = buildCratesLib {
    name = "dcpu16";
    version = "0.1.0";
    hash = "d3120159035cf8e7d56ca53ab78f7ce8af139c09731b9e22bbcda439ccd669af";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  "dcpu16_0_0" = dcpu16_0_0_7;
  dcpu16_0_2_0 = buildCratesLib {
    name = "dcpu16";
    version = "0.2.0";
    hash = "50be6cf4b034d9cbe42f08ae36837a3689fe6de1747aaad1ee538080df2afa69";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  "dcpu16_0_1" = dcpu16_0_1_0;
  dcpu16_0_3_0 = buildCratesLib {
    name = "dcpu16";
    version = "0.3.0";
    hash = "550d0c0c52d7b31d116c84101a65bbe2c64773e4eebb0dec3d9cbbb5c35aa4d5";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  "dcpu16_0_2" = dcpu16_0_2_0;
  dcpu16_0_4_0 = buildCratesLib {
    name = "dcpu16";
    version = "0.4.0";
    hash = "049608aff0709d1de1677ddbda204c0e6b263e4fcca622e75b8f9e1c76f7d82b";
    deps = with allCrates; [  all__getopts.getopts_0_2 ];
  };
  "dcpu16_0_3" = dcpu16_0_3_0;
  "dcpu16_0_4" = dcpu16_0_4_0;
  "dcpu16_0" = dcpu16_0_4_0;}