#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  threshold-secret-sharing_0_1_0 = buildCratesLib {
    name = "threshold-secret-sharing";
    version = "0.1.0";
    hash = "5ba5ca41c009e765dbb516d8f87f8f9762ce55b93dff67c1e6aa52595d75417e";
    deps = with allCrates; [  rand ];
  };
  threshold-secret-sharing_0_1_1 = buildCratesLib {
    name = "threshold-secret-sharing";
    version = "0.1.1";
    hash = "56454c418cead4031396a53ca52097f23163de50686453dc5b7dc7fcd4942341";
    deps = with allCrates; [  rand ];
  };
  threshold-secret-sharing_0_2_0 = buildCratesLib {
    name = "threshold-secret-sharing";
    version = "0.2.0";
    hash = "b0c7d3746197071f91356db39d18ba9986f3018912385c3f7e9d4c1241745703";
    deps = with allCrates; [  rand ];
  };
  "threshold-secret-sharing_0_1" = threshold-secret-sharing_0_1_1;
  threshold-secret-sharing_0_2_1 = buildCratesLib {
    name = "threshold-secret-sharing";
    version = "0.2.1";
    hash = "5922616aec2bbb08595ad9eac0b70bfb5927e0bd843fa1deb5c84f99c2df760a";
    deps = with allCrates; [  rand ];
  };
  "threshold-secret-sharing_0_2" = threshold-secret-sharing_0_2_1;
  "threshold-secret-sharing_0" = threshold-secret-sharing_0_2_1;}