#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  telegraph_0_1_1 = buildCratesLib {
    name = "telegraph";
    version = "0.1.1";
    hash = "0aafb0a5de7cff778a685b1413f9fb16fa6fdd7ab00e34882949e783cd404110";
    deps = with allCrates; [  all__serde_derive.serde_derive_0_8 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__serde.serde_0_8 ];
  };
  "telegraph_0_1" = telegraph_0_1_1;
  "telegraph_0" = telegraph_0_1_1;}