#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  telebot_0_0_1 = buildCratesLib {
    name = "telebot";
    version = "0.0.1";
    hash = "bfe0f25f46c47b4aa6c22a5d0ade45ca1d98bbbcf22b3b8a4ee68314cd27cda9";
    deps = with allCrates; [  all__tokio-curl.tokio-curl_0_1 all__serde.serde_0_8 all__curl.curl_0_3 all__serde_json.serde_json_0_8 all__telebot-derive.telebot-derive_0_0_1 all__futures.futures_0_1 all__serde_derive.serde_derive_0_8 all__tokio-core.tokio-core_0_1 ];
  };
  "telebot_0_0" = telebot_0_0_1;
  "telebot_0" = telebot_0_0_1;}