#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rc6_0_0_0 = buildCratesLib {
    name = "rc6";
    version = "0.0.0";
    hash = "de7277be0f1f58848b7824370381be5693bb55aaffa381a616956390bcf8e270";
    deps = with allCrates; [  ];
  };
  "rc6_0_0" = rc6_0_0_0;
  "rc6_0" = rc6_0_0_0;}