#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rdm_0_0_1 = buildCratesLib {
    name = "rdm";
    version = "0.0.1";
    hash = "466bbeb404183c2ca11f018d5e639183e0e01624039a5365e880fdc8cd70b52a";
    deps = with allCrates; [  ];
  };
  "rdm_0_0" = rdm_0_0_1;
  "rdm_0" = rdm_0_0_1;}