#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rfc_0_1_0 = buildCratesLib {
    name = "rfc";
    version = "0.1.0";
    hash = "514064736bf7b12b620589ed5e28586dbf7adbb02742d0cf058c824395e2014c";
    deps = with allCrates; [  all__regex.regex_0_1 all__time.time_0_1 all__docopt.docopt_0_6 ];
  };
  rfc_0_2_0 = buildCratesLib {
    name = "rfc";
    version = "0.2.0";
    hash = "f416ee74151ed37b58ac423ac97b92ad0a448be2bce9829f1bb18d9550b02149";
    deps = with allCrates; [  all__docopt.docopt_0_6 all__regex.regex_0_1 lazy_static all__time.time_0_1 ];
  };
  "rfc_0_1" = rfc_0_1_0;
  rfc_0_3_0 = buildCratesLib {
    name = "rfc";
    version = "0.3.0";
    hash = "b168381a5b48c654bcd64120b7d8c393360b4d6478cc097023f3c833009350a3";
    deps = with allCrates; [  lazy_static all__regex.regex_0_1 all__docopt.docopt_0_6 all__time.time_0_1 ];
  };
  "rfc_0_2" = rfc_0_2_0;
  "rfc_0_3" = rfc_0_3_0;
  "rfc_0" = rfc_0_3_0;}