#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rgs_0_0_1 = buildCratesLib {
    name = "rgs";
    version = "0.0.1";
    hash = "5560b53ca65b6bd80d748799a52df97be31663ce5003cdfecb798452eccb6a88";
    deps = with allCrates; [  ];
  };
  "rgs_0_0" = rgs_0_0_1;
  "rgs_0" = rgs_0_0_1;}