#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  git-brws_0_1_0 = buildCratesLib {
    name = "git-brws";
    version = "0.1.0";
    hash = "bd384bcdf1ed3621155cd7a22688da33685fbfbd2e75d3e4a2f979e3443fbcf3";
    deps = with allCrates; [  all__getopts.getopts_0_2 all__open.open_1_1 all__url.url_1_2 ];
  };
  git-brws_0_2_0 = buildCratesLib {
    name = "git-brws";
    version = "0.2.0";
    hash = "380bda6fa097fda45f120edd7fc274123f2f50ed3af4619d4092ca722d6440de";
    deps = with allCrates; [  all__getopts.getopts_0_2 all__url.url_1_2 all__open.open_1_1 ];
  };
  "git-brws_0_1" = git-brws_0_1_0;
  git-brws_0_3_0 = buildCratesLib {
    name = "git-brws";
    version = "0.3.0";
    hash = "6c44e1915dc985f96632092915c9a14373c344f48f3df540b5ca6159107f0e96";
    deps = with allCrates; [  all__open.open_1_1 all__url.url_1_2 all__getopts.getopts_0_2 ];
  };
  "git-brws_0_2" = git-brws_0_2_0;
  git-brws_0_4_1 = buildCratesLib {
    name = "git-brws";
    version = "0.4.1";
    hash = "395bf1066cb03596f8275c5c44e0f021aa4c7d244be87bc1d659b323cea42053";
    deps = with allCrates; [  all__url.url_1_2 all__open.open_1_1 all__getopts.getopts_0_2 ];
  };
  "git-brws_0_3" = git-brws_0_3_0;
  "git-brws_0_4" = git-brws_0_4_1;
  "git-brws_0" = git-brws_0_4_1;}