#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  crypto-hash_0_1_0 = buildCratesLib {
    name = "crypto-hash";
    version = "0.1.0";
    hash = "b70f5ec3d0c42cf6971875f4aa87fd8c176e7cd9a8f65c23e0fbab56c8db6a51";
    deps = with allCrates; [  all__hex.hex_0_2 ];
  };
  crypto-hash_0_2_0 = buildCratesLib {
    name = "crypto-hash";
    version = "0.2.0";
    hash = "2a0254ee0f8b9ee8e730025b9262e75e11fdc336cca0927f354e8e39eea3e123";
    deps = with allCrates; [  all__hex.hex_0_2 ];
  };
  "crypto-hash_0_1" = crypto-hash_0_1_0;
  crypto-hash_0_2_1 = buildCratesLib {
    name = "crypto-hash";
    version = "0.2.1";
    hash = "a663acd6405e29214879f51860db259f9ca013e79af6ebc9b8153faf2a135aae";
    deps = with allCrates; [  all__hex.hex_0_2 ];
  };
  "crypto-hash_0_2" = crypto-hash_0_2_1;
  "crypto-hash_0" = crypto-hash_0_2_1;}