#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  numeral_0_1_0 = buildCratesLib {
    name = "numeral";
    version = "0.1.0";
    hash = "528cb7a5f139c52eeea7c70be694b3dbe7647bcf9aa0045dd95f399f094070ab";
    deps = with allCrates; [  ];
  };
  numeral_0_1_1 = buildCratesLib {
    name = "numeral";
    version = "0.1.1";
    hash = "e6543933592507a939d4f7fe5496efe9eee40eb8c2d614553c7bf8b26652988f";
    deps = with allCrates; [  ];
  };
  numeral_0_1_2 = buildCratesLib {
    name = "numeral";
    version = "0.1.2";
    hash = "4b431e6d574a3998de4f2787610ae04c56f541986e9837e71dc6dc7354ce601c";
    deps = with allCrates; [  ];
  };
  numeral_0_2_0 = buildCratesLib {
    name = "numeral";
    version = "0.2.0";
    hash = "25a9d7f24e6990d5a1668b44363d5aed0be3f62f6a1bee586eafa7ce594b9fab";
    deps = with allCrates; [  ];
  };
  "numeral_0_1" = numeral_0_1_2;
  numeral_0_3_0 = buildCratesLib {
    name = "numeral";
    version = "0.3.0";
    hash = "cedda0431c2de9bfd51395fde19757d125e7f593ac63a3d640bf69e417566d7c";
    deps = with allCrates; [  ];
  };
  "numeral_0_2" = numeral_0_2_0;
  numeral_0_3_1 = buildCratesLib {
    name = "numeral";
    version = "0.3.1";
    hash = "f7f9e1a6bfccf9954cef9de533f9a70e9671738e7cd61d867872b5fea208a0a8";
    deps = with allCrates; [  ];
  };
  "numeral_0_3" = numeral_0_3_1;
  "numeral_0" = numeral_0_3_1;}