#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  fallible-streaming-iterator_0_1_0 = buildCratesLib {
    name = "fallible-streaming-iterator";
    version = "0.1.0";
    hash = "c3a5e3af625abf705e0b9836f2ecf17fe8340efbdbe3538dd25b9745ac28cf94";
    deps = with allCrates; [  ];
  };
  fallible-streaming-iterator_0_1_1 = buildCratesLib {
    name = "fallible-streaming-iterator";
    version = "0.1.1";
    hash = "f21789a72471af7eac15198255f1697eadfa010674735104bc2c9e43e69403ca";
    deps = with allCrates; [  ];
  };
  "fallible-streaming-iterator_0_1" = fallible-streaming-iterator_0_1_1;
  "fallible-streaming-iterator_0" = fallible-streaming-iterator_0_1_1;}