#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  orbclient_0_0_1 = buildCratesLib {
    name = "orbclient";
    version = "0.0.1";
    hash = "25242f7f82f641989e9a3149d3a09e6164330e21961fd65f8bcf3266060ebd6d";
    deps = with allCrates; [  all__num.num_0_1 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__num.num_0_1 all__num.num_0_1 all__sdl2.sdl2_0_9 all__num.num_0_1 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_0 = buildCratesLib {
    name = "orbclient";
    version = "0.1.0";
    hash = "28e060b22bd97b0170bc32e1a26d83b849e256ee228654ea729a0a05fa7cbda3";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  "orbclient_0_0" = orbclient_0_0_1;
  orbclient_0_1_1 = buildCratesLib {
    name = "orbclient";
    version = "0.1.1";
    hash = "3660cec5021c980a5a5231cd32df5c82cce86929a506959f5c295d8b9217f75b";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_2 = buildCratesLib {
    name = "orbclient";
    version = "0.1.2";
    hash = "9e072b084d0b80556459b3ee48693638765ac0f828bcf604a5e71ea68d04a384";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_3 = buildCratesLib {
    name = "orbclient";
    version = "0.1.3";
    hash = "b6f49b4978aaaf03c74603695309ab81c5c6b3684c5c6da0c5c0691241dab0c5";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_4 = buildCratesLib {
    name = "orbclient";
    version = "0.1.4";
    hash = "96803c7c1131b782e4f3a89073cca1e292d19014a6f2d345acee4e1c6248c988";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_5 = buildCratesLib {
    name = "orbclient";
    version = "0.1.5";
    hash = "bb5ae85157c73d96c6e0b7fbac33f70ee20ba4f58cf7937cabebaddf92c20a24";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_6 = buildCratesLib {
    name = "orbclient";
    version = "0.1.6";
    hash = "83aa535acf8423a1fa0500f79b22d2863fed9a8751c869c3a0f24b5f996e821d";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_7 = buildCratesLib {
    name = "orbclient";
    version = "0.1.7";
    hash = "b99572dfceb8bf59970d41a7d9df9a4b8ad8450d13908ceaf1a79ecd1fd62595";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_8 = buildCratesLib {
    name = "orbclient";
    version = "0.1.8";
    hash = "b70bd3de8a748c514efa859105c31f59c1c86a9dfd232d0b6a74485d0d6240f0";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_9 = buildCratesLib {
    name = "orbclient";
    version = "0.1.9";
    hash = "1ef8106d1468f028f841fb4f720be8a32d1e876d66401d5c9c57dbf54050eb21";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_10 = buildCratesLib {
    name = "orbclient";
    version = "0.1.10";
    hash = "0898db036fca73ddcf374c0dbb1be85b29b30e2f8ad7cc734520ccd450d31f1c";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_11 = buildCratesLib {
    name = "orbclient";
    version = "0.1.11";
    hash = "46bb53417291223cfa06f0e8750d5fe10fe8930ab7b285b7de75601a68bafb30";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_12 = buildCratesLib {
    name = "orbclient";
    version = "0.1.12";
    hash = "aba5fa59910bd8b6da46b9428cd2b439ad658231a64ff3e59a2f063e8babdffd";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_13 = buildCratesLib {
    name = "orbclient";
    version = "0.1.13";
    hash = "cbc17302e0a356cdf06f9dc1211f30c2d75e2002e567976ef89b8d290460ec2c";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_14 = buildCratesLib {
    name = "orbclient";
    version = "0.1.14";
    hash = "98a833f7b478f2f47a48153e918ae338e4bea36fb55310202a72792aec1ea891";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_15 = buildCratesLib {
    name = "orbclient";
    version = "0.1.15";
    hash = "d54b64d54f3e064561e87b2c79c26908029c3d6fcba8f89322c72a132df48487";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_16 = buildCratesLib {
    name = "orbclient";
    version = "0.1.16";
    hash = "1303fc072250aa7f219395541f9874780aa6260ff22153273b6b0c6975deb1d6";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_17 = buildCratesLib {
    name = "orbclient";
    version = "0.1.17";
    hash = "4ab6cab503bcc634fe68727efe34c493b4e43e2820ad0d83431944cd5471b645";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_18 = buildCratesLib {
    name = "orbclient";
    version = "0.1.18";
    hash = "9ea7d3befdc48694d7741c03fcb5357a9737886854e56007d2d8c6e3db398900";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_19 = buildCratesLib {
    name = "orbclient";
    version = "0.1.19";
    hash = "b7b94be07d52f31836c55948f121a7cace1030b48fceb04b069486ae998ef06c";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_20 = buildCratesLib {
    name = "orbclient";
    version = "0.1.20";
    hash = "02b1e91e98661890faa3ac8643fc10c8109dfe21f841211e4d8a88300c8c3b8f";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__redox_syscall.redox_syscall_0_1 ];
  };
  orbclient_0_1_21 = buildCratesLib {
    name = "orbclient";
    version = "0.1.21";
    hash = "8ca62fdc20f3b818371d03d55e06c730136d41b6d9684ffd7cdb0f5e17471f3c";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__redox_syscall.redox_syscall_0_1 ];
  };
  orbclient_0_1_22 = buildCratesLib {
    name = "orbclient";
    version = "0.1.22";
    hash = "de98fded1fd168a4c0b0fc07794909c310c9132d1b306b8e50389d4a0ea61201";
    deps = with allCrates; [  all__redox_syscall.redox_syscall_0_1 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_23 = buildCratesLib {
    name = "orbclient";
    version = "0.1.23";
    hash = "6fe26b22fe4d299903b7f7773dac58b6dcd98f5d7e05932b445bb8f9d433fe3f";
    deps = with allCrates; [  all__redox_syscall.redox_syscall_0_1 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_1_24 = buildCratesLib {
    name = "orbclient";
    version = "0.1.24";
    hash = "9d85de5769e8249cd1dd2107e7a8d6a8863c7e5ff00278ac4f033914936e9c65";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__redox_syscall.redox_syscall_0_1 ];
  };
  orbclient_0_1_25 = buildCratesLib {
    name = "orbclient";
    version = "0.1.25";
    hash = "89c63250bfee658ab00c8984e7a761da94752c95f1eb21bab056ee607365a042";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__redox_syscall.redox_syscall_0_1 ];
  };
  orbclient_0_1_26 = buildCratesLib {
    name = "orbclient";
    version = "0.1.26";
    hash = "6e8e982388f410b93ce531c13aa6bf1203d9e806e8034d8cb91d65a570a413a5";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__redox_syscall.redox_syscall_0_1 ];
  };
  orbclient_0_2_0 = buildCratesLib {
    name = "orbclient";
    version = "0.2.0";
    hash = "f4f99d3aa14879d8d7ffe4dc9d624952e5e2d06f7a7a55e302e9290786817dc0";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__redox_syscall.redox_syscall_0_1 ];
  };
  "orbclient_0_1" = orbclient_0_1_26;
  orbclient_0_2_1 = buildCratesLib {
    name = "orbclient";
    version = "0.2.1";
    hash = "4b8ff9b5ba988465f36bf129041fc5ab37ecde562711f07dd93cf4885df7e559";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__redox_syscall.redox_syscall_0_1 ];
  };
  orbclient_0_2_2 = buildCratesLib {
    name = "orbclient";
    version = "0.2.2";
    hash = "9e0ed5849355b902f51c60210f6263c1e7f0ad8d6566f3deb2ab0a98b7c27e71";
    deps = with allCrates; [  all__redox_syscall.redox_syscall_0_1 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_2_3 = buildCratesLib {
    name = "orbclient";
    version = "0.2.3";
    hash = "023f97347099e4c7a684f0749c3872a697528ea8b2272bf2d506069ac2e49df8";
    deps = with allCrates; [  all__redox_syscall.redox_syscall_0_1 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_2_4 = buildCratesLib {
    name = "orbclient";
    version = "0.2.4";
    hash = "921daab526513301b5cc598139aea09881a1af3299f8c828551dbfde22692447";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__redox_syscall.redox_syscall_0_1 ];
  };
  orbclient_0_2_5 = buildCratesLib {
    name = "orbclient";
    version = "0.2.5";
    hash = "125fd20969490c61ad9cd76cc63151ce24a96530976ee8880b1f263e16215be5";
    deps = with allCrates; [  all__redox_syscall.redox_syscall_0_1 all__sdl2.sdl2_0_9 ];
  };
  orbclient_0_2_7 = buildCratesLib {
    name = "orbclient";
    version = "0.2.7";
    hash = "9a501450c2a707a14ac88a46f0984dfed96eff9ca13cd5c1f2d5eb4adc5f6943";
    deps = with allCrates; [  all__sdl2.sdl2_0_9 all__redox_syscall.redox_syscall_0_1 ];
  };
  orbclient_0_2_8 = buildCratesLib {
    name = "orbclient";
    version = "0.2.8";
    hash = "990a90d6dc9109abef61ee2907561dde2ea3f603eefc5458a7623ff312f60530";
    deps = with allCrates; [  all__redox_syscall.redox_syscall_0_1 all__sdl2.sdl2_0_27 ];
  };
  orbclient_0_2_9 = buildCratesLib {
    name = "orbclient";
    version = "0.2.9";
    hash = "6510f973434621f88b7a2e0be1cc4e9ccc7bfb98fa279430cdc607b635777d36";
    deps = with allCrates; [  all__redox_syscall.redox_syscall_0_1 all__sdl2.sdl2_0_27 ];
  };
  orbclient_0_2_10 = buildCratesLib {
    name = "orbclient";
    version = "0.2.10";
    hash = "a8922c80cf6e574e12588f18d81a3b1dc6c0b05576c8dc3063fb49a2def0ace9";
    deps = with allCrates; [  all__sdl2.sdl2_0_27 all__redox_syscall.redox_syscall_0_1 ];
  };
  orbclient_0_2_11 = buildCratesLib {
    name = "orbclient";
    version = "0.2.11";
    hash = "c23f84e10051a9dcd2e32e42f19f0acaa2a87a4a8b59d365deae08003a910831";
    deps = with allCrates; [  all__sdl2.sdl2_0_27 all__redox_syscall.redox_syscall_0_1 ];
  };
  orbclient_0_2_12 = buildCratesLib {
    name = "orbclient";
    version = "0.2.12";
    hash = "4b3ce382eaf20295abe68a4bdeb9c589fb551cf11403e85b5f4caa6cfed85739";
    deps = with allCrates; [  all__sdl2.sdl2_0_27 all__redox_syscall.redox_syscall_0_1 ];
  };
  "orbclient_0_2" = orbclient_0_2_12;
  "orbclient_0" = orbclient_0_2_12;}