#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  has160_0_0_0 = buildCratesLib {
    name = "has160";
    version = "0.0.0";
    hash = "6b63cd603c247c692e0c71a1d017740a4b64c032b8db8ad64b5df45bee8e55cf";
    deps = with allCrates; [  ];
  };
  "has160_0_0" = has160_0_0_0;
  "has160_0" = has160_0_0_0;}