#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  let-it-go_0_1_0 = buildCratesLib {
    name = "let-it-go";
    version = "0.1.0";
    hash = "87f3a89718ffe8a2fe0507db7194b26eda34ccd793f404fe3c2f1d409be3a6d2";
    deps = with allCrates; [  ];
  };
  let-it-go_0_1_1 = buildCratesLib {
    name = "let-it-go";
    version = "0.1.1";
    hash = "e4d4415eaf173a203988058843ae4de8d32f076f1f80247f8e36178296beb1fc";
    deps = with allCrates; [  ];
  };
  "let-it-go_0_1" = let-it-go_0_1_1;
  "let-it-go_0" = let-it-go_0_1_1;}