#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  kabuki_0_0_1 = buildCratesLib {
    name = "kabuki";
    version = "0.0.1";
    hash = "d45fd1d902d57c4228d21e802e9bfa72100ea91d15ab3f0266c68f804381a096";
    deps = with allCrates; [  ];
  };
  "kabuki_0_0" = kabuki_0_0_1;
  "kabuki_0" = kabuki_0_0_1;}