#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  moments_0_1_0 = buildCratesLib {
    name = "moments";
    version = "0.1.0";
    hash = "a51336f3dfb3dc37355e51f6c4a0171d6de710ab00016d3cfd7909ea6f500f0b";
    deps = with allCrates; [  ];
  };
  "moments_0_1" = moments_0_1_0;
  "moments_0" = moments_0_1_0;}