#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  textwrap_0_1_0 = buildCratesLib {
    name = "textwrap";
    version = "0.1.0";
    hash = "068882f62ad2428da93e8ff8aa28b7ba9a1b8686c8d4ee939a4c46d85187fa4f";
    deps = with allCrates; [  all__unicode-width.unicode-width_0_1 ];
  };
  "textwrap_0_1" = textwrap_0_1_0;
  "textwrap_0" = textwrap_0_1_0;}