#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  postgres-shared_0_1_0 = buildCratesLib {
    name = "postgres-shared";
    version = "0.1.0";
    hash = "6f09b8819c2586032ed23bfbe95f6edfbebdc18bf9d0fe02c1f785f659958fbb";
    deps = with allCrates; [  all__hex.hex_0_2 all__postgres-protocol.postgres-protocol_0_2 phf all__fallible-iterator.fallible-iterator_0_1 ];
  };
  "postgres-shared_0_1" = postgres-shared_0_1_0;
  "postgres-shared_0" = postgres-shared_0_1_0;}