#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  openat_0_1_0 = buildCratesLib {
    name = "openat";
    version = "0.1.0";
    hash = "b29f3a213fd580dc1e7d280445e6ffcf7d4edc59e78d8fe5841963813471b319";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  "openat_0_1" = openat_0_1_0;
  "openat_0" = openat_0_1_0;}