#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  grnenv-rs_0_1_1 = buildCratesLib {
    name = "grnenv-rs";
    version = "0.1.1";
    hash = "8797bcd11b44c659a1648a7e48915f1c782c625e37bd383ff0f398e26a510a1c";
    deps = with allCrates; [  all__flate2.flate2_0_2 all__num_cpus.num_cpus_1_0 all__env_proxy.env_proxy_0_1 all__tempdir.tempdir_0_3 all__kuchiki.kuchiki_0_3 all__libc.libc_0_2 all__toml.toml_0_1 all__zip.zip_0_1 all__clap.clap_2_14 all__tar.tar_0_4 all__hyper.hyper_0_9 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "grnenv-rs_0_1" = grnenv-rs_0_1_1;
  "grnenv-rs_0" = grnenv-rs_0_1_1;}