#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  zfilexfer_0_0_2 = buildCratesLib {
    name = "zfilexfer";
    version = "0.0.2";
    hash = "4a3e37e2400709a10ac874f05e37a4e7720db16d956bdfae30ae588477a929b7";
    deps = with allCrates; [  all__czmq.czmq_0_1 all__crc.crc_1_2 all__rustc-serialize.rustc-serialize_0_3 all__zdaemon.zdaemon_0_0_2 ];
  };
  "zfilexfer_0_0" = zfilexfer_0_0_2;
  "zfilexfer_0" = zfilexfer_0_0_2;}