#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  done_0_0_0 = buildCratesLib {
    name = "done";
    version = "0.0.0";
    hash = "88cc13eab50fb86ebe942e185b4acca22941a820424a45e3c44a1bead9d4129c";
    deps = with allCrates; [  ];
  };
  "done_0_0" = done_0_0_0;
  "done_0" = done_0_0_0;}