#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tk-easyloop_0_1_0 = buildCratesLib {
    name = "tk-easyloop";
    version = "0.1.0";
    hash = "0a3e4942869e26c930eb7ab6911b66e2a2ed9d27d8c19c6fb1cdea3a9b421f10";
    deps = with allCrates; [  all__futures.futures_0_1 all__scoped-tls.scoped-tls_0_1 all__tokio-core.tokio-core_0_1 ];
  };
  "tk-easyloop_0_1" = tk-easyloop_0_1_0;
  "tk-easyloop_0" = tk-easyloop_0_1_0;}