#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  elastic_responses_0_2_0 = buildCratesLib {
    name = "elastic_responses";
    version = "0.2.0";
    hash = "0353b98678a3cf8d9b7c5d91a12969ca2dea4a5485f7639770f89b898dc960b7";
    deps = with allCrates; [  all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__slog.slog_1_4 all__serde_derive.serde_derive_0_8 all__slog-envlogger.slog-envlogger_0_5 all__json_str.json_str_0_3 all__log.log_0_3 all__slog-stdlog.slog-stdlog_1_1 ];
  };
  elastic_responses_0_2_1 = buildCratesLib {
    name = "elastic_responses";
    version = "0.2.1";
    hash = "cf18cd1e3d2968b89427342e960671b67843a16da31bb051ff3ca49a30858d49";
    deps = with allCrates; [  all__json_str.json_str_0_3 all__slog-envlogger.slog-envlogger_0_5 all__serde_derive.serde_derive_0_8 all__slog-stdlog.slog-stdlog_1_1 all__serde_json.serde_json_0_8 all__slog.slog_1_4 all__log.log_0_3 all__serde.serde_0_8 ];
  };
  "elastic_responses_0_2" = elastic_responses_0_2_1;
  "elastic_responses_0" = elastic_responses_0_2_1;}