#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  libflo_dynamic_event_0_1_0 = buildCratesLib {
    name = "libflo_dynamic_event";
    version = "0.1.0";
    hash = "98c063d61391fd443eca37f7726cc593e5e65b8ec05eff7410145fa1cd59176f";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__libflo_module.libflo_module_0_1 all__error-chain.error-chain_0_7 all__serde.serde_0_8 ];
  };
  "libflo_dynamic_event_0_1" = libflo_dynamic_event_0_1_0;
  "libflo_dynamic_event_0" = libflo_dynamic_event_0_1_0;}