#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  libflo_action_0_1_0 = buildCratesLib {
    name = "libflo_action";
    version = "0.1.0";
    hash = "fe29472794c7f0712edf3bd6d0ff33900b98d968a6208aa39776a23f269e793e";
    deps = with allCrates; [  ];
  };
  "libflo_action_0_1" = libflo_action_0_1_0;
  "libflo_action_0" = libflo_action_0_1_0;}