#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  libflo_func_test_0_0_1_0 = buildCratesLib {
    name = "libflo_func_test_0";
    version = "0.1.0";
    hash = "ce4d01c5d053e21a0f63423f16d06b25f308e6868c48987e9ddb8aebc2342d2d";
    deps = with allCrates; [  all__libflo_error.libflo_error_0_1 ];
  };
  "libflo_func_test_0_0_1" = libflo_func_test_0_0_1_0;
  "libflo_func_test_0_0" = libflo_func_test_0_0_1_0;}