#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rural_0_0_0 = buildCratesLib {
    name = "rural";
    version = "0.0.0";
    hash = "e895bfbcb01fd5615c807da846d060ef4e2a6d0abd012b66c7e134039d22eee6";
    deps = with allCrates; [  ];
  };
  rural_0_1_0 = buildCratesLib {
    name = "rural";
    version = "0.1.0";
    hash = "20e3a866d4af38294bbdb046cac660130857f6233ec888e74d4de44d8450314d";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__regex.regex_0_2 all__clap.clap_2_19 all__reqwest.reqwest_0_2 ];
  };
  "rural_0_0" = rural_0_0_0;
  rural_0_2_0 = buildCratesLib {
    name = "rural";
    version = "0.2.0";
    hash = "f74af93f3961c876dba605d4b68b86890ff1bc0122e49cf2e5695a68f32153f9";
    deps = with allCrates; [  all__clap.clap_2_19 all__regex.regex_0_2 all__serde_json.serde_json_0_8 all__lazy_static.lazy_static_0_2 all__reqwest.reqwest_0_2 ];
  };
  "rural_0_1" = rural_0_1_0;
  rural_0_2_1 = buildCratesLib {
    name = "rural";
    version = "0.2.1";
    hash = "ec33a0c829350056f8b74bbf03449f59d172284165f23828f517ab27e70fb6fb";
    deps = with allCrates; [  all__clap.clap_2_19 all__reqwest.reqwest_0_2 all__lazy_static.lazy_static_0_2 all__regex.regex_0_2 all__serde_json.serde_json_0_8 ];
  };
  rural_0_3_0 = buildCratesLib {
    name = "rural";
    version = "0.3.0";
    hash = "e2ddf34b9c3f79ac41e9023f992a9121589d5a8c11c7f9e23ef3aa79821c0b10";
    deps = with allCrates; [  all__regex.regex_0_2 all__serde_json.serde_json_0_8 all__lazy_static.lazy_static_0_2 all__clap.clap_2_19 all__reqwest.reqwest_0_2 ];
  };
  "rural_0_2" = rural_0_2_1;
  rural_0_4_0 = buildCratesLib {
    name = "rural";
    version = "0.4.0";
    hash = "6bb7a5eaa9bd5a7b5d60dcffc98998b817eda4a2102109588fb62b526d071621";
    deps = with allCrates; [  all__clap.clap_2_19 all__lazy_static.lazy_static_0_2 all__regex.regex_0_2 all__serde_json.serde_json_0_8 all__reqwest.reqwest_0_2 ];
  };
  "rural_0_3" = rural_0_3_0;
  rural_0_4_1 = buildCratesLib {
    name = "rural";
    version = "0.4.1";
    hash = "2636d5874744182dcca9786c76879af3763f451f45ba0802cae6e2ee4473f56d";
    deps = with allCrates; [  all__clap.clap_2_19 all__regex.regex_0_2 all__reqwest.reqwest_0_2 all__lazy_static.lazy_static_0_2 all__serde_json.serde_json_0_8 ];
  };
  rural_0_5_0 = buildCratesLib {
    name = "rural";
    version = "0.5.0";
    hash = "c80d427a1f4e2300caf90e37de06195289f70b8bdb9c004671d99201a1865a05";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__json-color.json-color_0_2 all__regex.regex_0_2 all__lazy_static.lazy_static_0_2 all__clap.clap_2_19 all__reqwest.reqwest_0_2 ];
  };
  "rural_0_4" = rural_0_4_1;
  rural_0_6_0 = buildCratesLib {
    name = "rural";
    version = "0.6.0";
    hash = "a586ed232eacdc77eb2c5ba6a4d3d1d999a0ab036a23ea72b3bfb4acc618d84b";
    deps = with allCrates; [  all__reqwest.reqwest_0_2 all__serde_json.serde_json_0_8 all__json-color.json-color_0_2 all__clap.clap_2_19 all__lazy_static.lazy_static_0_2 all__colored.colored_1_4 all__regex.regex_0_2 ];
  };
  "rural_0_5" = rural_0_5_0;
  rural_0_6_1 = buildCratesLib {
    name = "rural";
    version = "0.6.1";
    hash = "da77fc69ca9fa50a45003a270b7d2ddbac299d4c2b4e3368503a120d00949e7c";
    deps = with allCrates; [  all__clap.clap_2_20 all__colored.colored_1_4 all__lazy_static.lazy_static_0_2 all__regex.regex_0_2 all__reqwest.reqwest_0_2 all__serde_json.serde_json_0_8 all__json-color.json-color_0_3 ];
  };
  "rural_0_6" = rural_0_6_1;
  "rural_0" = rural_0_6_1;}