#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  erl_dist_0_1_0 = buildCratesLib {
    name = "erl_dist";
    version = "0.1.0";
    hash = "69a5841c19ae46c372185806fbe7472b3e82026cbd6f51dfb8d7c505956493ff";
    deps = with allCrates; [  all__eetf.eetf_0_3 all__md5.md5_0_3 all__handy_async.handy_async_0_2 all__futures.futures_0_1 all__bitflags.bitflags_0_7 all__rand.rand_0_3 ];
  };
  "erl_dist_0_1" = erl_dist_0_1_0;
  "erl_dist_0" = erl_dist_0_1_0;}