#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  diskarbitration-sys_0_0_1 = buildCratesLib {
    name = "diskarbitration-sys";
    version = "0.0.1";
    hash = "c3e269bfaa6b006ef892d8ec45b551c3a628e0f098bb12fd1c100e207f9214e3";
    deps = with allCrates; [  all__libc.libc_0_2 all__core-foundation-sys.core-foundation-sys_0_2 ];
  };
  diskarbitration-sys_0_0_2 = buildCratesLib {
    name = "diskarbitration-sys";
    version = "0.0.2";
    hash = "db39974ac08ea65f0ce17c1dbd1d0a4afb05b58fc4d90b1b4cc7fcf668e116fb";
    deps = with allCrates; [  all__core-foundation-sys.core-foundation-sys_0_2 all__libc.libc_0_2 ];
  };
  diskarbitration-sys_0_0_3 = buildCratesLib {
    name = "diskarbitration-sys";
    version = "0.0.3";
    hash = "fc2db023c069270c6234c5fb8b3b42b5569a5c29680d3067c8191ecac7cebebe";
    deps = with allCrates; [  all__core-foundation-sys.core-foundation-sys_0_2 all__libc.libc_0_2 ];
  };
  diskarbitration-sys_0_0_4 = buildCratesLib {
    name = "diskarbitration-sys";
    version = "0.0.4";
    hash = "8f82432ae94d42f160b6e17389d6e1c1eee29827b99ad32d35a0a96bb98bedb5";
    deps = with allCrates; [  all__core-foundation-sys.core-foundation-sys_0_2 all__libc.libc_0_2 ];
  };
  "diskarbitration-sys_0_0" = diskarbitration-sys_0_0_4;
  "diskarbitration-sys_0" = diskarbitration-sys_0_0_4;}