#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  yenc_0_0_1 = buildCratesLib {
    name = "yenc";
    version = "0.0.1";
    hash = "0e432f5922fd5f34efc1e04a35140c6817cfd55f30a351f4bab858dd4b47e752";
    deps = with allCrates; [  ];
  };
  yenc_0_0_2 = buildCratesLib {
    name = "yenc";
    version = "0.0.2";
    hash = "327be272694647c5ef03c356a20c04c8aaa4b32d85a353f1e0716290a068f665";
    deps = with allCrates; [  ];
  };
  "yenc_0_0" = yenc_0_0_2;
  "yenc_0" = yenc_0_0_2;}