#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  scopeguard_0_1_0 = buildCratesLib {
    name = "scopeguard";
    version = "0.1.0";
    hash = "73992bfe258a99b09a0d95ece1ed87826a7648c182c7f3727aef4eb21fee79b4";
    deps = with allCrates; [  ];
  };
  scopeguard_0_1_1 = buildCratesLib {
    name = "scopeguard";
    version = "0.1.1";
    hash = "161802103cb6f6a9b37cf0ed94eb4e2a461862c2a90f709a8f634e67c7848979";
    deps = with allCrates; [  ];
  };
  scopeguard_0_1_2 = buildCratesLib {
    name = "scopeguard";
    version = "0.1.2";
    hash = "59a076157c1e2dc561d8de585151ee6965d910dd4dcb5dabb7ae3e83981a6c57";
    deps = with allCrates; [  ];
  };
  scopeguard_0_2_0 = buildCratesLib {
    name = "scopeguard";
    version = "0.2.0";
    hash = "551cc7e5812ffa253138ea53b3de48306005422a66a5f0cc9a5704b3d92b298a";
    deps = with allCrates; [  ];
  };
  "scopeguard_0_1" = scopeguard_0_1_2;
  scopeguard_0_3_0 = buildCratesLib {
    name = "scopeguard";
    version = "0.3.0";
    hash = "ce108ea69fbd2c47dd2e75806bd7fc14bd58e73c7720544879449088f730716d";
    deps = with allCrates; [  ];
  };
  "scopeguard_0_2" = scopeguard_0_2_0;
  scopeguard_0_3_1 = buildCratesLib {
    name = "scopeguard";
    version = "0.3.1";
    hash = "7aa5d8d293df7346f1f69c9c8595febc2df7179d672b87619b33ce64dc0a30bb";
    deps = with allCrates; [  ];
  };
  "scopeguard_0_3" = scopeguard_0_3_1;
  "scopeguard_0" = scopeguard_0_3_1;}