#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  goauth_0_1_0 = buildCratesLib {
    name = "goauth";
    version = "0.1.0";
    hash = "5f3900ba9d83eba84c2f798bfb2901311d0ea3cb97cc6b0d632507c0f923f575";
    deps = with allCrates; [  all__serde_derive.serde_derive_0_8 all__smpl_jwt.smpl_jwt_0_1 all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__time.time_0_1 all__curl.curl_0_4 all__log.log_0_3 ];
  };
  goauth_0_1_1 = buildCratesLib {
    name = "goauth";
    version = "0.1.1";
    hash = "7b45b905795f47985092f0558ff4cfb68bd24e15f9a88a4d8753d6e83565012e";
    deps = with allCrates; [  all__log.log_0_3 all__time.time_0_1 all__curl.curl_0_4 all__serde_json.serde_json_0_8 all__serde_derive.serde_derive_0_8 all__smpl_jwt.smpl_jwt_0_1 all__serde.serde_0_8 ];
  };
  goauth_0_1_2 = buildCratesLib {
    name = "goauth";
    version = "0.1.2";
    hash = "018cd2e0ce186eba2f0bbd0d83dbc1a2728940e660afb6803e7154f6e1b67e7f";
    deps = with allCrates; [  all__curl.curl_0_4 all__serde_derive.serde_derive_0_8 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__smpl_jwt.smpl_jwt_0_1 all__time.time_0_1 all__log.log_0_3 ];
  };
  "goauth_0_1" = goauth_0_1_2;
  "goauth_0" = goauth_0_1_2;}