#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  xi-core-lib_0_1_0 = buildCratesLib {
    name = "xi-core-lib";
    version = "0.1.0";
    hash = "1ce110ac3bc5e0afa40aebce4ea5167f5cea7826f00934b8c5508963006320d1";
    deps = with allCrates; [  all__time.time_0_1 all__serde.serde_0_8 all__xi-rpc.xi-rpc_0_1 all__xi-rope.xi-rope_0_1 all__xi-unicode.xi-unicode_0_1 all__serde_json.serde_json_0_8 ];
  };
  "xi-core-lib_0_1" = xi-core-lib_0_1_0;
  "xi-core-lib_0" = xi-core-lib_0_1_0;}