#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  poolite_0_2_0 = buildCratesLib {
    name = "poolite";
    version = "0.2.0";
    hash = "30867f1c09b1291422d19d8114226f714fdc435298f0df6268adb15557c5527a";
    deps = with allCrates; [  all__stderr.stderr_0_2 all__num_cpus.num_cpus_1_0 ];
  };
  poolite_0_2_1 = buildCratesLib {
    name = "poolite";
    version = "0.2.1";
    hash = "ac4c09c27a1179a9fc9809d49fb6e3a9af31085f3e8f1cf1f1b7f02b2aadae52";
    deps = with allCrates; [  all__num_cpus.num_cpus_1_2 all__stderr.stderr_0_2 ];
  };
  poolite_0_3_0 = buildCratesLib {
    name = "poolite";
    version = "0.3.0";
    hash = "486e96d5be15ceee66e95dca24f212ce11fac3716311a8c3d899de867b2e8cec";
    deps = with allCrates; [  all__num_cpus.num_cpus_1_2 all__stderr.stderr_0_3 ];
  };
  "poolite_0_2" = poolite_0_2_1;
  "poolite_0_3" = poolite_0_3_0;
  "poolite_0" = poolite_0_3_0;}