#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  heatseeker_1_5_0 = buildCratesLib {
    name = "heatseeker";
    version = "1.5.0";
    hash = "ebdfd9286d08566c15a263541c8495e811281728578bc1c3efb7f9fa581bbd13";
    deps = with allCrates; [  all__getopts.getopts_0_2 all__libc.libc_0_2 all__crossbeam.crossbeam_0_2 all__unicode-width.unicode-width_0_1 all__num_cpus.num_cpus_1_1 all__time.time_0_1 ];
  };
  "heatseeker_1_5" = heatseeker_1_5_0;
  "heatseeker_1" = heatseeker_1_5_0;}