#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  an-rope_0_0_1 = buildCratesLib {
    name = "an-rope";
    version = "0.0.1";
    hash = "b7fa46f3be86eb809300de69d0a633cf617b7620f70b986e1a1e6cdf1c83b694";
    deps = with allCrates; [  ];
  };
  "an-rope_0_0" = an-rope_0_0_1;
  "an-rope_0" = an-rope_0_0_1;}