#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  enforce_0_0_1 = buildCratesLib {
    name = "enforce";
    version = "0.0.1";
    hash = "d1a36cdd0aff35b037edb5f3b13b6adf972ba82e217e2ed92147d270b0bd2d8b";
    deps = with allCrates; [  stainless ];
  };
  "enforce_0_0" = enforce_0_0_1;
  "enforce_0" = enforce_0_0_1;}