#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  codgenhelp_0_0_1 = buildCratesLib {
    name = "codgenhelp";
    version = "0.0.1";
    hash = "9c647856891b32040e1b29a1d4d1f64584cda8a3a14be8be2e874c2b8fd87673";
    deps = with allCrates; [  all__syn.syn_0_10 ];
  };
  "codgenhelp_0_0" = codgenhelp_0_0_1;
  "codgenhelp_0" = codgenhelp_0_0_1;}