#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  dir-signature_0_1_0 = buildCratesLib {
    name = "dir-signature";
    version = "0.1.0";
    hash = "28e6737efafc57a84a505ba9763255395b63500c8bf4a1753c5ebb639457bd49";
    deps = with allCrates; [  all__generic-array.generic-array_0_5 all__ignore.ignore_0_1 all__typenum.typenum_1_5 all__argparse.argparse_0_2 all__regex.regex_0_1 all__quick-error.quick-error_1_1 all__digest-writer.digest-writer_0_1 all__difference.difference_0_4 all__rustc-serialize.rustc-serialize_0_3 all__itertools.itertools_0_5 all__env_logger.env_logger_0_3 all__sha2.sha2_0_3 all__num_cpus.num_cpus_1_2 all__blake2.blake2_0_3 all__openat.openat_0_1 all__log.log_0_3 ];
  };
  "dir-signature_0_1" = dir-signature_0_1_0;
  "dir-signature_0" = dir-signature_0_1_0;}