#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  sysfs-pwm_0_1_0 = buildCratesLib {
    name = "sysfs-pwm";
    version = "0.1.0";
    hash = "267589d5f86a21e4da23c23be6083a6bcc42b3ea90ab952cda36917231e22849";
    deps = with allCrates; [  ];
  };
  "sysfs-pwm_0_1" = sysfs-pwm_0_1_0;
  "sysfs-pwm_0" = sysfs-pwm_0_1_0;}