#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  peel_0_0_1 = buildCratesLib {
    name = "peel";
    version = "0.0.1";
    hash = "e166362563828e3803d0a1ace75d3a49dc7e3f7cafe1fca9e7c618f200ac997e";
    deps = with allCrates; [  all__term.term_0 all__log.log_0 all__nom.nom_2 all__indextree.indextree_0 ];
  };
  "peel_0_0" = peel_0_0_1;
  "peel_0" = peel_0_0_1;}