#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  xkbcommon-sys_0_7_0 = buildCratesLib {
    name = "xkbcommon-sys";
    version = "0.7.0";
    hash = "18c6248693a3f6f93bcd32c3d6b1218f250cbb4779f918ed2a6566a7dc45bda9";
    deps = with allCrates; [  all__libc.libc_0_2 all__pkg-config.pkg-config_0_3 ];
  };
  xkbcommon-sys_0_7_1 = buildCratesLib {
    name = "xkbcommon-sys";
    version = "0.7.1";
    hash = "74d392b33c269836dde0ff07c4da1169bde73da46328b8b8089ed059b3440fce";
    deps = with allCrates; [  all__libc.libc_0_2 all__pkg-config.pkg-config_0_3 ];
  };
  xkbcommon-sys_0_7_2 = buildCratesLib {
    name = "xkbcommon-sys";
    version = "0.7.2";
    hash = "0d652eaad8914eded5c6bb769fd5fedb0d945e51c51b5a9b8c1bb2a7dfd936e4";
    deps = with allCrates; [  all__libc.libc_0_2 all__pkg-config.pkg-config_0_3 ];
  };
  xkbcommon-sys_0_7_3 = buildCratesLib {
    name = "xkbcommon-sys";
    version = "0.7.3";
    hash = "c575723dee5a0ecfc4a64d8ad4085df7e84aa63fd7115a5e57eadc698ed372a6";
    deps = with allCrates; [  all__libc.libc_0_2 all__pkg-config.pkg-config_0_3 ];
  };
  "xkbcommon-sys_0_7" = xkbcommon-sys_0_7_3;
  "xkbcommon-sys_0" = xkbcommon-sys_0_7_3;}