#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  guifast_0_1_0 = buildCratesLib {
    name = "guifast";
    version = "0.1.0";
    hash = "dfb091f499fee3d8fdb031b7b071ea7df6ccbb54170f61807761ee0a56bd897e";
    deps = with allCrates; [  all__serde.serde_0_8 all__lazy_static.lazy_static_0_2 all__libflo_module.libflo_module_0_1 all__serde_json.serde_json_0_8 all__libflo_error.libflo_error_0_1 all__mut_static.mut_static_0_1 all__error-chain.error-chain_0_7 all__libflo.libflo_0_1 ];
  };
  "guifast_0_1" = guifast_0_1_0;
  "guifast_0" = guifast_0_1_0;}