#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  init_with_0_1_0 = buildCratesLib {
    name = "init_with";
    version = "0.1.0";
    hash = "67597c58f6ab8f455f049f7d69c597bb5e5d847a5012fb5a22c0fd16d7677830";
    deps = with allCrates; [  all__nodrop.nodrop_0_1 ];
  };
  init_with_0_1_1 = buildCratesLib {
    name = "init_with";
    version = "0.1.1";
    hash = "e4e6c97ff4d325dfe17eb0f0c0cd3daf7437ceb859c75880172b84514c17e62c";
    deps = with allCrates; [  all__nodrop.nodrop_0_1 ];
  };
  "init_with_0_1" = init_with_0_1_1;
  "init_with_0" = init_with_0_1_1;}