#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  init-daemon_0_1_0 = buildCratesLib {
    name = "init-daemon";
    version = "0.1.0";
    hash = "c403eb960d1fd543b064fd6abbb6990237d6b415ebf9a9732d758c85d3cae51f";
    deps = with allCrates; [  ];
  };
  "init-daemon_0_1" = init-daemon_0_1_0;
  "init-daemon_0" = init-daemon_0_1_0;}