#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  mio-uds_0_6_0 = buildCratesLib {
    name = "mio-uds";
    version = "0.6.0";
    hash = "3b6bd83b05675b13929d3c3add6c8cabf0067a63e8bb56bf231b8203946e0aa7";
    deps = with allCrates; [  all__mio.mio_0_6 all__libc.libc_0_2 ];
  };
  "mio-uds_0_6" = mio-uds_0_6_0;
  "mio-uds_0" = mio-uds_0_6_0;}