#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  yaecs_0_1_0 = buildCratesLib {
    name = "yaecs";
    version = "0.1.0";
    hash = "f8f70a032381eb661ebcbf5d5ba2d52d0a6eb3fd89a4b4832b30c1ed06434747";
    deps = with allCrates; [  ];
  };
  yaecs_0_3_0 = buildCratesLib {
    name = "yaecs";
    version = "0.3.0";
    hash = "4588fc4fbfe90a6f1ded46c8d82ae41c07fc6d6369f814b6bffd758ba026237e";
    deps = with allCrates; [  all__anymap.anymap_0_12 ];
  };
  "yaecs_0_1" = yaecs_0_1_0;
  yaecs_0_4_0 = buildCratesLib {
    name = "yaecs";
    version = "0.4.0";
    hash = "c27c8c38d58ebce05e8726d3a209b946b5cd02e8d6cac7922a4cd095bd6863bc";
    deps = with allCrates; [  all__anymap.anymap_0_12 ];
  };
  "yaecs_0_3" = yaecs_0_3_0;
  yaecs_0_5_0 = buildCratesLib {
    name = "yaecs";
    version = "0.5.0";
    hash = "c8226a0bf2aca65659df1caa1491b8e0100885f7a506f0c7b0ebe8ca257d8684";
    deps = with allCrates; [  all__anymap.anymap_0_12 ];
  };
  "yaecs_0_4" = yaecs_0_4_0;
  yaecs_0_5_1 = buildCratesLib {
    name = "yaecs";
    version = "0.5.1";
    hash = "3e529e9504810f24364f807ceb1ca48cff57ae443e4a2d964432b73a68dd2ca9";
    deps = with allCrates; [  all__anymap.anymap_0_12 ];
  };
  yaecs_0_5_2 = buildCratesLib {
    name = "yaecs";
    version = "0.5.2";
    hash = "d548db5399978e2b2cdf9d336231cc1cd845b4216a52c698a33865dbba8af5f2";
    deps = with allCrates; [  all__anymap.anymap_0_12 ];
  };
  yaecs_0_5_3 = buildCratesLib {
    name = "yaecs";
    version = "0.5.3";
    hash = "5050551b0b08f7a9d0b508893c195ec602357862385d5bd855f5d30bc9f05ab6";
    deps = with allCrates; [  all__anymap.anymap_0_12 ];
  };
  yaecs_0_6_0 = buildCratesLib {
    name = "yaecs";
    version = "0.6.0";
    hash = "d2d5dcd5c8a90bffbf522baaccb4b49780aea202fa40547cbebf52b462e4c4b7";
    deps = with allCrates; [  all__anymap.anymap_0_12 ];
  };
  "yaecs_0_5" = yaecs_0_5_3;
  yaecs_0_7_0 = buildCratesLib {
    name = "yaecs";
    version = "0.7.0";
    hash = "7bc17f91e398f52120de14b0280ad2513f51dda086b5cdf35bafd8c2a5e5355f";
    deps = with allCrates; [  all__anymap.anymap_0_12 ];
  };
  "yaecs_0_6" = yaecs_0_6_0;
  "yaecs_0_7" = yaecs_0_7_0;
  "yaecs_0" = yaecs_0_7_0;}