#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  demon_0_0_1 = buildCratesLib {
    name = "demon";
    version = "0.0.1";
    hash = "63a2623afe114e699a54990787983cee063313d2ced3540180fe0fda9602e1cb";
    deps = with allCrates; [  ];
  };
  "demon_0_0" = demon_0_0_1;
  "demon_0" = demon_0_0_1;}