#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tk-pool_0_1_0 = buildCratesLib {
    name = "tk-pool";
    version = "0.1.0";
    hash = "92079598bef64cb381e2e37b1c769a0c007b3640e4d6ff8bc6b4a3fcef3e7298";
    deps = with allCrates; [  all__log.log_0_3 all__tokio-core.tokio-core_0_1 all__abstract-ns.abstract-ns_0_2 all__rand.rand_0_3 all__quick-error.quick-error_1_1 all__futures.futures_0_1 ];
  };
  tk-pool_0_2_0 = buildCratesLib {
    name = "tk-pool";
    version = "0.2.0";
    hash = "9efc6b39ad08bc56e7e9b06c6e99e86ac8ce4a384307c15d04e72ae9e066e518";
    deps = with allCrates; [  all__log.log_0_3 all__quick-error.quick-error_1_1 all__abstract-ns.abstract-ns_0_2 all__futures.futures_0_1 all__tokio-core.tokio-core_0_1 all__rand.rand_0_3 ];
  };
  "tk-pool_0_1" = tk-pool_0_1_0;
  tk-pool_0_2_1 = buildCratesLib {
    name = "tk-pool";
    version = "0.2.1";
    hash = "836f74e1de121133904b98cfbe29075ed9be7616c8ef031c2c4d2e164a26331d";
    deps = with allCrates; [  all__rand.rand_0_3 all__abstract-ns.abstract-ns_0_2 all__futures.futures_0_1 all__log.log_0_3 all__tokio-core.tokio-core_0_1 all__quick-error.quick-error_1_1 ];
  };
  tk-pool_0_2_2 = buildCratesLib {
    name = "tk-pool";
    version = "0.2.2";
    hash = "16ae52a2127b8d1c6b310cd2c64d7c6dd4453f9f7c3ddfdaac006b4a318564ab";
    deps = with allCrates; [  all__quick-error.quick-error_1_1 all__tokio-core.tokio-core_0_1 all__futures.futures_0_1 all__abstract-ns.abstract-ns_0_2 all__log.log_0_3 all__rand.rand_0_3 ];
  };
  "tk-pool_0_2" = tk-pool_0_2_2;
  "tk-pool_0" = tk-pool_0_2_2;}