#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tower_0_0_1 = buildCratesLib {
    name = "tower";
    version = "0.0.1";
    hash = "3169849ccfbe2a467b0fb794cb301d036adfff31a18765eb28ecfe7324f7f7ff";
    deps = with allCrates; [  ];
  };
  "tower_0_0" = tower_0_0_1;
  "tower_0" = tower_0_0_1;}