#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  objectid_0_1_0 = buildCratesLib {
    name = "objectid";
    version = "0.1.0";
    hash = "cfa9bc14a1709f80333c5fe8ffffb8172e60e62ade708d36e7ed385158c9250c";
    deps = with allCrates; [  all__rand.rand_0_3 all__hostname.hostname_0_1 all__byteorder.byteorder_0_3 all__libc.libc_0_1 all__rustc-serialize.rustc-serialize_0_3 all__lazy_static.lazy_static_0_2 all__rust-crypto.rust-crypto_0_2 all__quick-error.quick-error_1_1 ];
  };
  "objectid_0_1" = objectid_0_1_0;
  "objectid_0" = objectid_0_1_0;}