#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  funfsm_0_1_0 = buildCratesLib {
    name = "funfsm";
    version = "0.1.0";
    hash = "157db45901d2156266e2b884423025ab816fa86bd68900fdcad6c6b1dee5ac35";
    deps = with allCrates; [  ];
  };
  "funfsm_0_1" = funfsm_0_1_0;
  "funfsm_0" = funfsm_0_1_0;}