#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ripgrep_0_1_0 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.0";
    hash = "dc9aea0e1e05c4be246e94f70ef91f1f40cbb53f5d950292e41d1dff0fc2491c";
    deps = with allCrates; [  all__memmap.memmap_0_2 all__regex.regex_0_1 all__thread_local.thread_local_0_2 all__rustc-serialize.rustc-serialize_0_3 all__num_cpus.num_cpus_1 all__lazy_static.lazy_static_0_2 all__crossbeam.crossbeam_0_2 all__grep.grep_0_1 all__log.log_0_3 all__env_logger.env_logger_0_3 all__libc.libc_0_2 all__docopt.docopt_0_6 all__term.term_0_4 all__walkdir.walkdir_0_1 all__memchr.memchr_0_1 ];
  };
  ripgrep_0_1_1 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.1";
    hash = "2742da21d99c30f259f5a4506a86095bcfaf9479c271ea9681c2bf0276dce2cc";
    deps = with allCrates; [  all__docopt.docopt_0_6 all__crossbeam.crossbeam_0_2 all__log.log_0_3 all__term.term_0_4 all__grep.grep_0_1 all__num_cpus.num_cpus_1 all__lazy_static.lazy_static_0_2 all__memmap.memmap_0_2 all__env_logger.env_logger_0_3 all__regex.regex_0_1 all__libc.libc_0_2 all__rustc-serialize.rustc-serialize_0_3 all__memchr.memchr_0_1 all__walkdir.walkdir_0_1 ];
  };
  ripgrep_0_1_2 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.2";
    hash = "4d13b28323c1bd2625363b4f731d2c34e95d332cc27ffc305b3832c4dd51af52";
    deps = with allCrates; [  all__log.log_0_3 all__env_logger.env_logger_0_3 all__memchr.memchr_0_1 all__libc.libc_0_2 all__walkdir.walkdir_0_1 all__docopt.docopt_0_6 all__fnv.fnv_1_0 all__grep.grep_0_1 all__deque.deque_0_3 all__rustc-serialize.rustc-serialize_0_3 all__lazy_static.lazy_static_0_2 all__regex.regex_0_1 all__term.term_0_4 all__num_cpus.num_cpus_1 all__memmap.memmap_0_2 ];
  };
  ripgrep_0_1_3 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.3";
    hash = "03df125aed715af3582c59f8864e840c85d4f2a41bf0536ea4a8c2134dbcc413";
    deps = with allCrates; [  all__memmap.memmap_0_2 all__num_cpus.num_cpus_1 all__lazy_static.lazy_static_0_2 all__env_logger.env_logger_0_3 all__regex.regex_0_1 all__fnv.fnv_1_0 all__deque.deque_0_3 all__memchr.memchr_0_1 all__grep.grep_0_1 all__log.log_0_3 all__rustc-serialize.rustc-serialize_0_3 all__libc.libc_0_2 all__term.term_0_4 all__docopt.docopt_0_6 all__walkdir.walkdir_0_1 ];
  };
  ripgrep_0_1_4 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.4";
    hash = "54c0c912c68ea79ebdc8dabfa43759a6567e3d82b02aa9a74aa0135a155ffb87";
    deps = with allCrates; [  all__grep.grep_0_1 all__rustc-serialize.rustc-serialize_0_3 all__env_logger.env_logger_0_3 all__log.log_0_3 all__libc.libc_0_2 all__deque.deque_0_3 all__lazy_static.lazy_static_0_2 all__walkdir.walkdir_0_1 all__memmap.memmap_0_2 all__regex.regex_0_1 all__fnv.fnv_1_0 all__docopt.docopt_0_6 all__num_cpus.num_cpus_1 all__term.term_0_4 all__memchr.memchr_0_1 ];
  };
  ripgrep_0_1_5 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.5";
    hash = "7e2c33aa79573e250df55807e23b2e0dffb3e02113a48ff77a1314383a4359ea";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__log.log_0_3 all__grep.grep_0_1 all__fnv.fnv_1_0 all__memchr.memchr_0_1 all__rustc-serialize.rustc-serialize_0_3 all__lazy_static.lazy_static_0_2 all__deque.deque_0_3 all__term.term_0_4 all__regex.regex_0_1 all__libc.libc_0_2 all__walkdir.walkdir_0_1 all__memmap.memmap_0_2 all__num_cpus.num_cpus_1 all__docopt.docopt_0_6 ];
  };
  ripgrep_0_1_6 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.6";
    hash = "066eedf08af98a6520863005b3db525df4feaff191a20593d63068bb5de18c71";
    deps = with allCrates; [  all__log.log_0_3 all__lazy_static.lazy_static_0_2 all__fnv.fnv_1_0 all__term.term_0_4 all__walkdir.walkdir_0_1 all__rustc-serialize.rustc-serialize_0_3 all__grep.grep_0_1 all__num_cpus.num_cpus_1 all__memchr.memchr_0_1 all__regex.regex_0_1 all__docopt.docopt_0_6 all__env_logger.env_logger_0_3 all__libc.libc_0_2 all__deque.deque_0_3 all__memmap.memmap_0_2 ];
  };
  ripgrep_0_1_7 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.7";
    hash = "a8db7076d183d93574e1e40700c20d44c16f4a66eaf6fe2246dc3f0a449ce5c5";
    deps = with allCrates; [  all__libc.libc_0_2 all__num_cpus.num_cpus_1 all__deque.deque_0_3 all__rustc-serialize.rustc-serialize_0_3 all__walkdir.walkdir_0_1 all__term.term_0_4 all__fnv.fnv_1_0 all__lazy_static.lazy_static_0_2 all__memmap.memmap_0_2 all__env_logger.env_logger_0_3 all__memchr.memchr_0_1 all__log.log_0_3 all__grep.grep_0_1 all__regex.regex_0_1 all__docopt.docopt_0_6 ];
  };
  ripgrep_0_1_8 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.8";
    hash = "a168032813180e6e3e1195a21eb8fab08c659e5eedf27aecc6c06e0d9b6f2d87";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__memchr.memchr_0_1 all__lazy_static.lazy_static_0_2 all__libc.libc_0_2 all__memmap.memmap_0_2 all__term.term_0_4 all__fnv.fnv_1_0 all__grep.grep_0_1 all__docopt.docopt_0_6 all__log.log_0_3 all__deque.deque_0_3 all__regex.regex_0_1 all__walkdir.walkdir_0_1 all__env_logger.env_logger_0_3 all__num_cpus.num_cpus_1 ];
  };
  ripgrep_0_1_9 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.9";
    hash = "e5974d8df5f03dadc9ac49baa9291e152a1966bfe469774e045b8e5212e14fe8";
    deps = with allCrates; [  all__term.term_0_4 all__lazy_static.lazy_static_0_2 all__memmap.memmap_0_2 all__fnv.fnv_1_0 all__deque.deque_0_3 all__docopt.docopt_0_6 all__memchr.memchr_0_1 all__env_logger.env_logger_0_3 all__libc.libc_0_2 all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__regex.regex_0_1 all__num_cpus.num_cpus_1 all__grep.grep_0_1 all__walkdir.walkdir_0_1 ];
  };
  ripgrep_0_1_10 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.10";
    hash = "b5228ee254a4916a8fb92c27f2e4f867bbff11da43073ae4649d5a67221ac3c6";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__memmap.memmap_0_2 all__walkdir.walkdir_0_1 all__term.term_0_4 all__grep.grep_0_1 all__deque.deque_0_3 all__libc.libc_0_2 all__docopt.docopt_0_6 all__num_cpus.num_cpus_1 all__lazy_static.lazy_static_0_2 all__memchr.memchr_0_1 all__fnv.fnv_1_0 all__env_logger.env_logger_0_3 all__regex.regex_0_1 all__log.log_0_3 ];
  };
  ripgrep_0_1_11 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.11";
    hash = "12627d37751efc889caaa60e3e909678a243bf41888443ff22d1819d729ec1ab";
    deps = with allCrates; [  all__num_cpus.num_cpus_1 all__docopt.docopt_0_6 all__grep.grep_0_1 all__log.log_0_3 all__env_logger.env_logger_0_3 all__deque.deque_0_3 all__memchr.memchr_0_1 all__memmap.memmap_0_2 all__term.term_0_4 all__rustc-serialize.rustc-serialize_0_3 all__fnv.fnv_1_0 all__regex.regex_0_1 all__lazy_static.lazy_static_0_2 all__walkdir.walkdir_0_1 all__libc.libc_0_2 ];
  };
  ripgrep_0_1_12 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.12";
    hash = "45006e85e6d4539166fd6a00b71265282f2d22c6c036e4a415d97ac9f729b46f";
    deps = with allCrates; [  all__deque.deque_0_3 all__lazy_static.lazy_static_0_2 all__walkdir.walkdir_0_1 all__log.log_0_3 all__term.term_0_4 all__memchr.memchr_0_1 all__num_cpus.num_cpus_1 all__regex.regex_0_1 all__libc.libc_0_2 all__fnv.fnv_1_0 all__env_logger.env_logger_0_3 all__docopt.docopt_0_6 all__rustc-serialize.rustc-serialize_0_3 all__memmap.memmap_0_2 all__grep.grep_0_1 ];
  };
  ripgrep_0_1_13 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.13";
    hash = "45a1eaf2802935e19fb6d812bffe3491098b6e822db3a943fef083e17ca996c3";
    deps = with allCrates; [  all__deque.deque_0_3 all__env_logger.env_logger_0_3 all__log.log_0_3 all__grep.grep_0_1 all__lazy_static.lazy_static_0_2 all__rustc-serialize.rustc-serialize_0_3 all__docopt.docopt_0_6 all__fnv.fnv_1_0 all__memchr.memchr_0_1 all__term.term_0_4 all__walkdir.walkdir_0_1 all__memmap.memmap_0_2 all__regex.regex_0_1 all__libc.libc_0_2 all__num_cpus.num_cpus_1 ];
  };
  ripgrep_0_1_14 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.14";
    hash = "87711169a0dd3e49a82b405f0f26d11138ff1727072e10b15788f7206794f9ef";
    deps = with allCrates; [  all__docopt.docopt_0_6 all__log.log_0_3 all__grep.grep_0_1 all__env_logger.env_logger_0_3 all__term.term_0_4 all__deque.deque_0_3 all__lazy_static.lazy_static_0_2 all__memchr.memchr_0_1 all__fnv.fnv_1_0 all__regex.regex_0_1 all__libc.libc_0_2 all__memmap.memmap_0_2 all__num_cpus.num_cpus_1 all__walkdir.walkdir_0_1 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  ripgrep_0_1_15 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.15";
    hash = "17dda80b1e01ddd7a31b92f280543eee482088c4eab06e55209fd21700301d5b";
    deps = with allCrates; [  all__grep.grep_0_1 all__docopt.docopt_0_6 all__rustc-serialize.rustc-serialize_0_3 all__env_logger.env_logger_0_3 all__log.log_0_3 all__regex.regex_0_1 all__memmap.memmap_0_2 all__num_cpus.num_cpus_1 all__lazy_static.lazy_static_0_2 all__deque.deque_0_3 all__memchr.memchr_0_1 all__fnv.fnv_1_0 all__libc.libc_0_2 all__term.term_0_4 all__walkdir.walkdir_0_1 ];
  };
  ripgrep_0_1_16 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.16";
    hash = "8546dbb34970d5aab8d431739ad5862763616efa1710eafaf4096a7fbdf5af1a";
    deps = with allCrates; [  all__deque.deque_0_3 all__memchr.memchr_0_1 all__libc.libc_0_2 all__walkdir.walkdir_0_1 all__lazy_static.lazy_static_0_2 all__num_cpus.num_cpus_1 all__log.log_0_3 all__memmap.memmap_0_2 all__docopt.docopt_0_6 all__regex.regex_0_1 all__rustc-serialize.rustc-serialize_0_3 all__env_logger.env_logger_0_3 all__fnv.fnv_1_0 all__grep.grep_0_1 all__term.term_0_4 ];
  };
  ripgrep_0_1_17 = buildCratesLib {
    name = "ripgrep";
    version = "0.1.17";
    hash = "6f7ee2177d064cae54aef44f4aa3f4d17d3408ccde312de1a6208b38bd7c4f8a";
    deps = with allCrates; [  all__grep.grep_0_1 all__deque.deque_0_3 all__memmap.memmap_0_2 all__rustc-serialize.rustc-serialize_0_3 all__memchr.memchr_0_1 all__fnv.fnv_1_0 all__log.log_0_3 all__walkdir.walkdir_0_1 all__term.term_0_4 all__lazy_static.lazy_static_0_2 all__libc.libc_0_2 all__num_cpus.num_cpus_1 all__docopt.docopt_0_6 all__regex.regex_0_1 all__env_logger.env_logger_0_3 ];
  };
  ripgrep_0_2_0 = buildCratesLib {
    name = "ripgrep";
    version = "0.2.0";
    hash = "a052d6362bc3c3a121da4c4042b9a24a635453d92a8fa0e61b58e089d7b88ca8";
    deps = with allCrates; [  all__grep.grep_0_1 all__fnv.fnv_1_0 all__term.term_0_4 all__log.log_0_3 all__num_cpus.num_cpus_1 all__docopt.docopt_0_6 all__libc.libc_0_2 all__regex.regex_0_1 all__walkdir.walkdir_0_1 all__memchr.memchr_0_1 all__rustc-serialize.rustc-serialize_0_3 all__lazy_static.lazy_static_0_2 all__deque.deque_0_3 all__env_logger.env_logger_0_3 all__memmap.memmap_0_2 ];
  };
  "ripgrep_0_1" = ripgrep_0_1_17;
  ripgrep_0_2_1 = buildCratesLib {
    name = "ripgrep";
    version = "0.2.1";
    hash = "d9223c22a6f03e07ae60164932c69433d5e75fe445b88bb82f74e69c6c825d0a";
    deps = with allCrates; [  all__grep.grep_0_1 all__num_cpus.num_cpus_1 all__lazy_static.lazy_static_0_2 all__docopt.docopt_0_6 all__walkdir.walkdir_0_1 all__fnv.fnv_1_0 all__rustc-serialize.rustc-serialize_0_3 all__term.term_0_4 all__memchr.memchr_0_1 all__memmap.memmap_0_2 all__libc.libc_0_2 all__log.log_0_3 all__regex.regex_0_1 all__env_logger.env_logger_0_3 all__deque.deque_0_3 ];
  };
  ripgrep_0_2_2 = buildCratesLib {
    name = "ripgrep";
    version = "0.2.2";
    hash = "397bd504a3b5b99425c8d18e105d4530e97b624b6f7fcedfc7c19ac2fa773906";
    deps = with allCrates; [  all__memmap.memmap_0_2 all__globset.globset_0_1 all__log.log_0_3 all__term.term_0_4 all__rustc-serialize.rustc-serialize_0_3 all__walkdir.walkdir_0_1 all__docopt.docopt_0_6 all__env_logger.env_logger_0_3 all__lazy_static.lazy_static_0_2 all__deque.deque_0_3 all__memchr.memchr_0_1 all__num_cpus.num_cpus_1 all__regex.regex_0_1 all__libc.libc_0_2 all__grep.grep_0_1 ];
  };
  ripgrep_0_2_3 = buildCratesLib {
    name = "ripgrep";
    version = "0.2.3";
    hash = "10028d9fdf891126b50404d8f52a9f22f26f9210afd4407e4f627fe3221c1f12";
    deps = with allCrates; [  all__walkdir.walkdir_0_1 all__term.term_0_4 all__thread_local.thread_local_0_2 all__num_cpus.num_cpus_1 all__libc.libc_0_2 all__memchr.memchr_0_1 all__docopt.docopt_0_6 all__memmap.memmap_0_2 all__regex.regex_0_1 all__grep.grep_0_1 all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__deque.deque_0_3 all__lazy_static.lazy_static_0_2 all__env_logger.env_logger_0_3 all__globset.globset_0_1 ];
  };
  ripgrep_0_2_4 = buildCratesLib {
    name = "ripgrep";
    version = "0.2.4";
    hash = "1bbd0f7c375a64ee5627fa54958ba53d9fefb877870403e6eb0cb54aa24171e1";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__rustc-serialize.rustc-serialize_0_3 all__memmap.memmap_0_5 all__lazy_static.lazy_static_0_2 all__regex.regex_0_1 all__ctrlc.ctrlc_2_0 all__deque.deque_0_3 all__grep.grep_0_1 all__num_cpus.num_cpus_1 all__libc.libc_0_2 all__log.log_0_3 all__memchr.memchr_0_1 all__term.term_0_4 all__ignore.ignore_0_1 all__docopt.docopt_0_6 ];
  };
  ripgrep_0_2_5 = buildCratesLib {
    name = "ripgrep";
    version = "0.2.5";
    hash = "fb58b718f532b5923eabd6f4957c093a8c42f027dcd9e15889c811c25ae68d1f";
    deps = with allCrates; [  all__docopt.docopt_0_6 all__env_logger.env_logger_0_3 all__libc.libc_0_2 all__lazy_static.lazy_static_0_2 all__deque.deque_0_3 all__memmap.memmap_0_5 all__rustc-serialize.rustc-serialize_0_3 all__memchr.memchr_0_1 all__regex.regex_0_1 all__log.log_0_3 all__ignore.ignore_0_1 all__ctrlc.ctrlc_2_0 all__num_cpus.num_cpus_1 all__grep.grep_0_1 all__term.term_0_4 ];
  };
  ripgrep_0_2_6 = buildCratesLib {
    name = "ripgrep";
    version = "0.2.6";
    hash = "7a442abbeb5b762b6ea1013fd705142a6f560277c6255a10ff09a50d2fd20434";
    deps = with allCrates; [  all__memmap.memmap_0_5 all__docopt.docopt_0_6 all__grep.grep_0_1 all__env_logger.env_logger_0_3 all__num_cpus.num_cpus_1 all__rustc-serialize.rustc-serialize_0_3 all__term.term_0_4 all__ignore.ignore_0_1 all__deque.deque_0_3 all__regex.regex_0_1 all__ctrlc.ctrlc_2_0 all__libc.libc_0_2 all__lazy_static.lazy_static_0_2 all__memchr.memchr_0_1 all__log.log_0_3 ];
  };
  ripgrep_0_2_7 = buildCratesLib {
    name = "ripgrep";
    version = "0.2.7";
    hash = "ad9c7b4944807ad23fc545bfabb7fde94efa4c3f2b723842be5963fd2a68d68c";
    deps = with allCrates; [  all__grep.grep_0_1 all__regex.regex_0_1 all__num_cpus.num_cpus_1 all__rustc-serialize.rustc-serialize_0_3 all__lazy_static.lazy_static_0_2 all__ignore.ignore_0_1 all__memchr.memchr_0_1 all__bytecount.bytecount_0_1 all__docopt.docopt_0_6 all__env_logger.env_logger_0_3 all__log.log_0_3 all__libc.libc_0_2 all__memmap.memmap_0_5 all__term.term_0_4 all__ctrlc.ctrlc_2_0 ];
  };
  ripgrep_0_2_8 = buildCratesLib {
    name = "ripgrep";
    version = "0.2.8";
    hash = "3f491df76258ece1a8b4c687008f01aa7f856cdae394062e6f5f4564cc055476";
    deps = with allCrates; [  all__num_cpus.num_cpus_1 all__ignore.ignore_0_1 all__term.term_0_4 all__libc.libc_0_2 all__memmap.memmap_0_5 all__grep.grep_0_1 all__bytecount.bytecount_0_1 all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__regex.regex_0_1 all__lazy_static.lazy_static_0_2 all__memchr.memchr_0_1 all__env_logger.env_logger_0_3 all__ctrlc.ctrlc_2_0 all__docopt.docopt_0_6 ];
  };
  ripgrep_0_2_9 = buildCratesLib {
    name = "ripgrep";
    version = "0.2.9";
    hash = "8548c0a4872edfb69f2abeb40ff52843a82d090678667ae28d964dff3c782766";
    deps = with allCrates; [  all__ctrlc.ctrlc_2_0 all__term.term_0_4 all__regex.regex_0_1 all__docopt.docopt_0_6 all__bytecount.bytecount_0_1 all__memmap.memmap_0_5 all__grep.grep_0_1 all__libc.libc_0_2 all__lazy_static.lazy_static_0_2 all__num_cpus.num_cpus_1 all__ignore.ignore_0_1 rustc-serialize all__env_logger.env_logger_0_3 all__memchr.memchr_0_1 all__log.log_0_3 ];
  };
  ripgrep_0_3_0 = buildCratesLib {
    name = "ripgrep";
    version = "0.3.0";
    hash = "b30bddbcbe32096c38b1207a12b88f75a3b8c15a2e65d0f4e7b013722b874d92";
    deps = with allCrates; [  all__log.log_0_3 all__regex.regex_0_1 all__clap.clap_2_18 all__lazy_static.lazy_static_0_2 all__env_logger.env_logger_0_3 all__libc.libc_0_2 all__memchr.memchr_0_1 all__memmap.memmap_0_5 all__grep.grep_0_1 all__bytecount.bytecount_0_1 all__ignore.ignore_0_1 all__num_cpus.num_cpus_1 all__termcolor.termcolor_0_1 all__ctrlc.ctrlc_2_0 all__clap.clap_2_18 all__lazy_static.lazy_static_0_2 ];
  };
  "ripgrep_0_2" = ripgrep_0_2_9;
  ripgrep_0_3_1 = buildCratesLib {
    name = "ripgrep";
    version = "0.3.1";
    hash = "0f37b342258640323b43d50ffb72a972dfe8cb4bd28d3b8f40d1da0ffdb21987";
    deps = with allCrates; [  all__num_cpus.num_cpus_1 all__ignore.ignore_0_1 all__libc.libc_0_2 all__lazy_static.lazy_static_0_2 all__termcolor.termcolor_0_1 all__memchr.memchr_0_1 all__regex.regex_0_1 all__bytecount.bytecount_0_1 all__grep.grep_0_1 all__log.log_0_3 all__ctrlc.ctrlc_2_0 all__clap.clap_2_18 all__env_logger.env_logger_0_3 all__memmap.memmap_0_5 all__lazy_static.lazy_static_0_2 all__clap.clap_2_18 ];
  };
  ripgrep_0_3_2 = buildCratesLib {
    name = "ripgrep";
    version = "0.3.2";
    hash = "07f93175191e86f37c122014d6603a972626022bb06e7d3160d5eba3a6271c8c";
    deps = with allCrates; [  all__num_cpus.num_cpus_1 all__regex.regex_0_1 all__env_logger.env_logger_0_3 all__termcolor.termcolor_0_1 all__memchr.memchr_0_1 all__libc.libc_0_2 all__bytecount.bytecount_0_1 all__log.log_0_3 all__clap.clap_2_19 all__ignore.ignore_0_1 all__lazy_static.lazy_static_0_2 all__ctrlc.ctrlc_2_0 all__memmap.memmap_0_5 all__grep.grep_0_1 all__clap.clap_2_18 all__lazy_static.lazy_static_0_2 ];
  };
  "ripgrep_0_3" = ripgrep_0_3_2;
  "ripgrep_0" = ripgrep_0_3_2;}