#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  bip39_0_1_0 = buildCratesLib {
    name = "bip39";
    version = "0.1.0";
    hash = "1cad62f4b4659e9443b2afc8f70cbe2a371a63ad5ce3b8162f78aecd8817c05d";
    deps = with allCrates; [  all__rand.rand_0_3 all__rustc-serialize.rustc-serialize_0_3 all__bitreader.bitreader_0_1 all__rust-crypto.rust-crypto_0_2 all__bit-vec.bit-vec_0_4 ];
  };
  "bip39_0_1" = bip39_0_1_0;
  "bip39_0" = bip39_0_1_0;}