#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ndarray-numtest_0_1_0 = buildCratesLib {
    name = "ndarray-numtest";
    version = "0.1.0";
    hash = "8ef687f39df9eb471ee6cf2553756aec2475995bfb77d874d4ab6bddf15ef98d";
    deps = with allCrates; [  all__float-cmp.float-cmp_0_2 all__ndarray.ndarray_0_7 all__rand.rand_0_3 all__num-complex.num-complex_0_1 ];
  };
  "ndarray-numtest_0_1" = ndarray-numtest_0_1_0;
  "ndarray-numtest_0" = ndarray-numtest_0_1_0;}