#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  graphflo_0_1_0 = buildCratesLib {
    name = "graphflo";
    version = "0.1.0";
    hash = "b3243fbb83e9d6db8ade2a2b8fbf92ad0edfe2dfa009864476cd34c4cf059659";
    deps = with allCrates; [  all__serde.serde_0_8 all__mut_static.mut_static_0_1 all__libflo_error.libflo_error_0_1 all__serde_json.serde_json_0_8 all__libflo_module.libflo_module_0_1 all__error-chain.error-chain_0_7 all__lazy_static.lazy_static_0_2 all__libflo.libflo_0_1 ];
  };
  "graphflo_0_1" = graphflo_0_1_0;
  "graphflo_0" = graphflo_0_1_0;}