#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  token_1_0_0 = buildCratesLib {
    name = "token";
    version = "1.0.0";
    hash = "901839ad6c7082b9af935440d9b65d61048d6760767df640427508d6128ec2f2";
    deps = with allCrates; [  ];
  };
  "token_1_0" = token_1_0_0;
  "token_1" = token_1_0_0;}