#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  locale_config_0_1_0 = buildCratesLib {
    name = "locale_config";
    version = "0.1.0";
    hash = "fdec193384ce89653498a33b0831965995eef075485a8013d416d1898498caee";
    deps = with allCrates; [  all__regex.regex_0_1 all__lazy_static.lazy_static_0_2 ];
  };
  locale_config_0_1_1 = buildCratesLib {
    name = "locale_config";
    version = "0.1.1";
    hash = "459f951e3c3df5e1c5453cb56c9ed833242817bd5d6bc3ae03a5b00c2d85732e";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__regex.regex_0_1 ];
  };
  "locale_config_0_1" = locale_config_0_1_1;
  "locale_config_0" = locale_config_0_1_1;}