#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ceramic_0_1_0 = buildCratesLib {
    name = "ceramic";
    version = "0.1.0";
    hash = "7c8398ca4d497aa142b05a54f3e88620cc3c43357bd94c295ca56aa120b3c2f6";
    deps = with allCrates; [  all__nix.nix_0_7 ];
  };
  ceramic_0_1_1 = buildCratesLib {
    name = "ceramic";
    version = "0.1.1";
    hash = "1462fbad56ca4e3353e9e83087dbaba6fa74d77e2db65fd492bee997c6445a16";
    deps = with allCrates; [  all__nix.nix_0_7 ];
  };
  ceramic_0_1_2 = buildCratesLib {
    name = "ceramic";
    version = "0.1.2";
    hash = "b307ce9196b274079f91d817d8b9420645156f80cfe39fbb5c62495a1496255d";
    deps = with allCrates; [  all__nix.nix_0_7 ];
  };
  ceramic_0_1_3 = buildCratesLib {
    name = "ceramic";
    version = "0.1.3";
    hash = "9c7c73699555ec5ce7b669ed230d82095a7068a68d120a703fa4dab06e1ba7fb";
    deps = with allCrates; [  all__rain.rain_0_2 all__nix.nix_0_7 all__rustc-serialize.rustc-serialize_0_3 all__bincode.bincode_0_6 ];
  };
  ceramic_0_2_1 = buildCratesLib {
    name = "ceramic";
    version = "0.2.1";
    hash = "7b5f58cbf59cc6dcc7230c8f7a1615b75fc88ac0c32f53805ac8c48e0898b684";
    deps = with allCrates; [  all__bincode.bincode_0_6 all__nix.nix_0_7 all__rain.rain_0_2 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "ceramic_0_1" = ceramic_0_1_3;
  "ceramic_0_2" = ceramic_0_2_1;
  "ceramic_0" = ceramic_0_2_1;}