#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  html-entities_0_1_0 = buildCratesLib {
    name = "html-entities";
    version = "0.1.0";
    hash = "18d57ae052df4379087aba566ca1b4896831237e8c42aeadda905a29d5c7c2fb";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 ];
  };
  "html-entities_0_1" = html-entities_0_1_0;
  "html-entities_0" = html-entities_0_1_0;}