#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  sotassl-sys_0_7_14 = buildCratesLib {
    name = "sotassl-sys";
    version = "0.7.14";
    hash = "c6f2d22b85b51fbad2ba1f35f051ac67df3a5961dcbf9dfa7851ec2f06023ea0";
    deps = with allCrates; [  all__libc.libc_0_2 all__pkg-config.pkg-config_0_3 all__libressl-pnacl-sys.libressl-pnacl-sys_2_1 all__libressl-pnacl-sys.libressl-pnacl-sys_2_1 all__libressl-pnacl-sys.libressl-pnacl-sys_2_1 all__libressl-pnacl-sys.libressl-pnacl-sys_2_1 ];
  };
  sotassl-sys_0_7_1400 = buildCratesLib {
    name = "sotassl-sys";
    version = "0.7.1400";
    hash = "57bd7c6f0104f55b5ad40fd36938344f0021d7c67827002436ce48a38504c391";
    deps = with allCrates; [  all__libc.libc_0_2 all__pkg-config.pkg-config_0_3 all__libressl-pnacl-sys.libressl-pnacl-sys_2_1 all__libressl-pnacl-sys.libressl-pnacl-sys_2_1 all__libressl-pnacl-sys.libressl-pnacl-sys_2_1 all__libressl-pnacl-sys.libressl-pnacl-sys_2_1 ];
  };
  "sotassl-sys_0_7" = sotassl-sys_0_7_1400;
  "sotassl-sys_0" = sotassl-sys_0_7_1400;}