#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  this_0_1_0 = buildCratesLib {
    name = "this";
    version = "0.1.0";
    hash = "ee8195b83256972d2b297fe02e86c3e8994215233dd2a765187129d42ca66c95";
    deps = with allCrates; [  ];
  };
  "this_0_1" = this_0_1_0;
  "this_0" = this_0_1_0;}