#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  orbfont_0_1_0 = buildCratesLib {
    name = "orbfont";
    version = "0.1.0";
    hash = "dbb242990fee401c0dacf050c403e91a011ab96f94f5520b89aceb6d56b057d0";
    deps = with allCrates; [  all__rusttype.rusttype_0_2 all__orbclient.orbclient_0_1 ];
  };
  orbfont_0_1_1 = buildCratesLib {
    name = "orbfont";
    version = "0.1.1";
    hash = "ac480c1be63587f8290e8600a56b0f8a88eb1617e9fbfe9d3185cb1ece1e353e";
    deps = with allCrates; [  all__orbclient.orbclient_0_1 all__rusttype.rusttype_0_2 ];
  };
  orbfont_0_1_2 = buildCratesLib {
    name = "orbfont";
    version = "0.1.2";
    hash = "3b5d8c0fa6c5cd5252283e25241dc242f57d0d89d694a3e4467a716575f6076b";
    deps = with allCrates; [  all__orbclient.orbclient_0_1 all__rusttype.rusttype_0_2 ];
  };
  orbfont_0_1_3 = buildCratesLib {
    name = "orbfont";
    version = "0.1.3";
    hash = "4285ace67f9e42c91029bcd079532ca52cbb734a44fc5d0bf137d0a3f066f1c0";
    deps = with allCrates; [  all__rusttype.rusttype_0_2 all__orbclient.orbclient_0_2 ];
  };
  orbfont_0_1_4 = buildCratesLib {
    name = "orbfont";
    version = "0.1.4";
    hash = "58aa939942b5b926eb033ecbe18323bbaa38147d39c5e946247a8cb77be5abc5";
    deps = with allCrates; [  all__rusttype.rusttype_0_2 all__orbclient.orbclient_0_2 ];
  };
  orbfont_0_1_5 = buildCratesLib {
    name = "orbfont";
    version = "0.1.5";
    hash = "16de17c6c7ecf998de688c0bef537a2aa9ec41b71ca42ceb9a0c0a865b300379";
    deps = with allCrates; [  all__orbclient.orbclient_0_2 all__rusttype.rusttype_0_2 ];
  };
  "orbfont_0_1" = orbfont_0_1_5;
  "orbfont_0" = orbfont_0_1_5;}