#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ustulation-test0_0_1_0 = buildCratesLib {
    name = "ustulation-test0";
    version = "0.1.0";
    hash = "f56b2f5bbc87a5a48b6d43b3816ac84a7143e11a425ab92f658a77f043ee2485";
    deps = with allCrates; [  ];
  };
  "ustulation-test0_0_1" = ustulation-test0_0_1_0;
  "ustulation-test0_0" = ustulation-test0_0_1_0;}