#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  geohashrust_0_0_1 = buildCratesLib {
    name = "geohashrust";
    version = "0.0.1";
    hash = "6ec5ac4ecf6c9376b83ec6b61669216b5f2ee83d549601ee699ead43094053de";
    deps = with allCrates; [  ];
  };
  geohashrust_0_0_2 = buildCratesLib {
    name = "geohashrust";
    version = "0.0.2";
    hash = "8e37caa3f2d642c1f9cb2c11f0dce25df9f9478584dd8ec23e8fd659b63293ac";
    deps = with allCrates; [  ];
  };
  "geohashrust_0_0" = geohashrust_0_0_2;
  "geohashrust_0" = geohashrust_0_0_2;}