#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ed25519-dalek_0_1_0 = buildCratesLib {
    name = "ed25519-dalek";
    version = "0.1.0";
    hash = "7a3a444401d380f0b6ee84d72857111aaa351da950ceca62a47daffaafd9ea76";
    deps = with allCrates; [  all__arrayref.arrayref_0_3 all__rust-crypto.rust-crypto_0_2 all__curve25519-dalek.curve25519-dalek_0_1 all__rand.rand_0_3 ];
  };
  "ed25519-dalek_0_1" = ed25519-dalek_0_1_0;
  "ed25519-dalek_0" = ed25519-dalek_0_1_0;}