#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  duct_0_1_0 = buildCratesLib {
    name = "duct";
    version = "0.1.0";
    hash = "ec7d25ef8a548eeec92ee83ec3b7cd33135945cbd5764df8b1c481b7152846ab";
    deps = with allCrates; [  ];
  };
  duct_0_2_0 = buildCratesLib {
    name = "duct";
    version = "0.2.0";
    hash = "99960a7386e8567bd1be470f32467c6ba31e0f160bb592b412895411f3e2ac13";
    deps = with allCrates; [  libc crossbeam ];
  };
  "duct_0_1" = duct_0_1_0;
  duct_0_4_0 = buildCratesLib {
    name = "duct";
    version = "0.4.0";
    hash = "007e0b7f60e219a5c01ad7c7b7ec7b66a6e0f7b0b27f0cfd7789d8077489b1b0";
    deps = with allCrates; [  crossbeam libc ];
  };
  "duct_0_2" = duct_0_2_0;
  duct_0_5_0 = buildCratesLib {
    name = "duct";
    version = "0.5.0";
    hash = "e44ba5cafcd47b37703a3c27b91294ba88f0c8970b7773b24aecab5d920ebb0d";
    deps = with allCrates; [  all__crossbeam.crossbeam_0_2 all__os_pipe.os_pipe_0_3 ];
  };
  "duct_0_4" = duct_0_4_0;
  duct_0_5_1 = buildCratesLib {
    name = "duct";
    version = "0.5.1";
    hash = "54d8472f78165a1553734d6d0deac13b72d1f3e20ded8b109a91c9bd95d2af89";
    deps = with allCrates; [  all__os_pipe.os_pipe_0_4 ];
  };
  "duct_0_5" = duct_0_5_1;
  "duct_0" = duct_0_5_1;}