#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  zxcvbn_0_1_0 = buildCratesLib {
    name = "zxcvbn";
    version = "0.1.0";
    hash = "307972e2209c45cd054089bfced46626e46be27950277f0e7bcab70049b44a82";
    deps = with allCrates; [  all__itertools.itertools_0_5 all__quick-error.quick-error_1_1 all__regex.regex_0_1 all__lazy_static.lazy_static_0_2 all__macro-attr.macro-attr_0_2 all__onig.onig_1_2 all__time.time_0_1 all__derive_builder.derive_builder_0_2 ];
  };
  zxcvbn_0_2_0 = buildCratesLib {
    name = "zxcvbn";
    version = "0.2.0";
    hash = "9c18d086420422a8ba747c6a5edfddb80282e0ba050e1254060a0bed7cf69b6c";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__regex.regex_0_1 all__onig.onig_1_2 all__macro-attr.macro-attr_0_2 all__itertools.itertools_0_5 all__time.time_0_1 all__derive_builder.derive_builder_0_2 ];
  };
  "zxcvbn_0_1" = zxcvbn_0_1_0;
  zxcvbn_0_2_1 = buildCratesLib {
    name = "zxcvbn";
    version = "0.2.1";
    hash = "a1b27a85354f196f504691f7b0b5be86f1b946155707fb4fa0dd55ce3063911c";
    deps = with allCrates; [  all__macro-attr.macro-attr_0_2 all__regex.regex_0_2 all__onig.onig_1_2 all__lazy_static.lazy_static_0_2 all__time.time_0_1 all__itertools.itertools_0_5 all__derive_builder.derive_builder_0_2 ];
  };
  "zxcvbn_0_2" = zxcvbn_0_2_1;
  "zxcvbn_0" = zxcvbn_0_2_1;}