#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tokio-proto_0_1_0 = buildCratesLib {
    name = "tokio-proto";
    version = "0.1.0";
    hash = "7c0d6031f94d78d7b4d509d4a7c5e1cdf524a17e7b08d1c188a83cf720e69808";
    deps = with allCrates; [  all__net2.net2_0_2 all__futures.futures_0_1 all__log.log_0_3 all__slab.slab_0_3 all__smallvec.smallvec_0_2 all__tokio-core.tokio-core_0_1 all__take.take_0_1 all__tokio-service.tokio-service_0_1 all__rand.rand_0_3 ];
  };
  "tokio-proto_0_1" = tokio-proto_0_1_0;
  "tokio-proto_0" = tokio-proto_0_1_0;}