#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tokio-core_0_1_0 = buildCratesLib {
    name = "tokio-core";
    version = "0.1.0";
    hash = "659cbae6c954dee37352853816c6a52180e47feb70be73bbfeec6d58c4da4a71";
    deps = with allCrates; [  all__log.log_0_3 all__slab.slab_0_3 all__mio.mio_0_6 all__futures.futures_0_1 all__scoped-tls.scoped-tls_0_1 ];
  };
  tokio-core_0_1_1 = buildCratesLib {
    name = "tokio-core";
    version = "0.1.1";
    hash = "06f40e15561569e24dab3dcf270c0bb950195b84dbed591dfb6591e28c9b9cff";
    deps = with allCrates; [  all__scoped-tls.scoped-tls_0_1 all__futures.futures_0_1 all__log.log_0_3 all__mio.mio_0_6 all__slab.slab_0_3 ];
  };
  tokio-core_0_1_2 = buildCratesLib {
    name = "tokio-core";
    version = "0.1.2";
    hash = "52416b3e937abac22a543a7f1c66bd37feb60137ff1ab42390fa02df85347e58";
    deps = with allCrates; [  all__futures.futures_0_1 all__log.log_0_3 all__slab.slab_0_3 all__mio.mio_0_6 all__scoped-tls.scoped-tls_0_1 ];
  };
  tokio-core_0_1_3 = buildCratesLib {
    name = "tokio-core";
    version = "0.1.3";
    hash = "0800e9475303171ffbc79394079ef503b6d00949649799208f4fc8f1eca20892";
    deps = with allCrates; [  all__futures.futures_0_1 all__log.log_0_3 all__mio.mio_0_6 all__scoped-tls.scoped-tls_0_1 all__slab.slab_0_3 ];
  };
  "tokio-core_0_1" = tokio-core_0_1_3;
  "tokio-core_0" = tokio-core_0_1_3;}