#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tokio-openssl_0_1_0 = buildCratesLib {
    name = "tokio-openssl";
    version = "0.1.0";
    hash = "15c7ec95795d227dd07b7e29289700c9e45c84ec76b59627df8f52af0c043d74";
    deps = with allCrates; [  all__openssl.openssl_0_9 all__tokio-core.tokio-core_0_1 all__futures.futures_0_1 ];
  };
  "tokio-openssl_0_1" = tokio-openssl_0_1_0;
  "tokio-openssl_0" = tokio-openssl_0_1_0;}