#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tokio-curl_0_1_0 = buildCratesLib {
    name = "tokio-curl";
    version = "0.1.0";
    hash = "19c784c750da74a32bb98679b36ac62bb4cdee6ee9e5697f766e67cabc6cca69";
    deps = with allCrates; [  all__futures.futures_0_1 all__curl.curl_0_3 all__log.log_0_3 all__tokio-core.tokio-core_0_1 all__mio.mio_0_6 all__scoped-tls.scoped-tls_0_1 all__libc.libc_0_2 all__slab.slab_0_3 ];
  };
  tokio-curl_0_1_1 = buildCratesLib {
    name = "tokio-curl";
    version = "0.1.1";
    hash = "5f6805da0e024c53cbb26b3841102c1873996cbf8a44c2b5c6b6d97f0c4c03c6";
    deps = with allCrates; [  all__curl.curl_0_3 all__futures.futures_0_1 all__tokio-core.tokio-core_0_1 all__log.log_0_3 all__mio.mio_0_6 all__slab.slab_0_3 all__libc.libc_0_2 all__scoped-tls.scoped-tls_0_1 ];
  };
  tokio-curl_0_1_2 = buildCratesLib {
    name = "tokio-curl";
    version = "0.1.2";
    hash = "6f3d99ac926a9ed6c38c007e120a8c3e45aba1cc04b155978f4bafbbe70f9a3b";
    deps = with allCrates; [  all__futures.futures_0_1 all__tokio-core.tokio-core_0_1 all__curl.curl_0_3 all__log.log_0_3 all__libc.libc_0_2 all__mio.mio_0_6 all__scoped-tls.scoped-tls_0_1 all__slab.slab_0_3 ];
  };
  tokio-curl_0_1_3 = buildCratesLib {
    name = "tokio-curl";
    version = "0.1.3";
    hash = "7cf863fd2ae8982b480c5ffdcf9870bee087477fa228613fe419dcd39042f578";
    deps = with allCrates; [  all__tokio-core.tokio-core_0_1 all__log.log_0_3 all__curl.curl_0_3 all__futures.futures_0_1 all__libc.libc_0_2 all__mio.mio_0_6 all__slab.slab_0_3 all__scoped-tls.scoped-tls_0_1 ];
  };
  tokio-curl_0_1_4 = buildCratesLib {
    name = "tokio-curl";
    version = "0.1.4";
    hash = "90b8783eae655d41754cd4ff06d71ae1de3bf2f2b5ed99846e15151281dd2e40";
    deps = with allCrates; [  all__log.log_0_3 all__curl.curl_0_3 all__tokio-core.tokio-core_0_1 all__futures.futures_0_1 all__mio.mio_0_6 all__scoped-tls.scoped-tls_0_1 all__libc.libc_0_2 all__slab.slab_0_3 ];
  };
  "tokio-curl_0_1" = tokio-curl_0_1_4;
  "tokio-curl_0" = tokio-curl_0_1_4;}