#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ffmpeg-sys_2_6_2 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "2.6.2";
    hash = "c86ca186ffbc9fb09eb3d5de08dea4645eb5ee196189436318a58a4d93ea7f7b";
    deps = with allCrates; [  libc ];
  };
  ffmpeg-sys_2_7_0 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "2.7.0";
    hash = "aef00a4d64c053e4099633e9e030e04ed5f0c1a07bef08efc66aca4dade60ed3";
    deps = with allCrates; [  libc ];
  };
  "ffmpeg-sys_2_6" = ffmpeg-sys_2_6_2;
  ffmpeg-sys_2_7_1 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "2.7.1";
    hash = "a0ff68a29753ffe4ed5a6bfb1f4bb71539554dbed42af5b48653e75129cbd01c";
    deps = with allCrates; [  libc ];
  };
  ffmpeg-sys_2_8_0 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "2.8.0";
    hash = "82a1aa6aa1adea3c29c2cbd0ae593ea9595c8ef742895a7c9a0048fe098e1c26";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  "ffmpeg-sys_2_7" = ffmpeg-sys_2_7_1;
  ffmpeg-sys_2_8_2 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "2.8.2";
    hash = "3871ef9041ede7e56d919a05d6a590e20c478823a6e19c8f5f3babf3492f2731";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  ffmpeg-sys_2_8_3 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "2.8.3";
    hash = "6f057f3654dce7d6bf5b304a162269d134c6e6db489675845eec532b722dfa91";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  ffmpeg-sys_2_8_6 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "2.8.6";
    hash = "1f6c8c802c35d01ba729c99380de6e7844a137e4943efcc92042ff3cebe65841";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  ffmpeg-sys_2_8_7 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "2.8.7";
    hash = "602c5ec6f0acc2d901d422ff7dde9070e895cad240402703befe7044c44eaec0";
    deps = with allCrates; [  all__libc.libc_0_2 all__num_cpus.num_cpus_0_2 ];
  };
  ffmpeg-sys_2_8_8 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "2.8.8";
    hash = "207a9ed300327f98196659f5e198a40089a4219bf68a08e682a5a0e85a1b7c4b";
    deps = with allCrates; [  all__libc.libc_0_2 all__num_cpus.num_cpus_0_2 ];
  };
  ffmpeg-sys_2_8_9 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "2.8.9";
    hash = "683f0fa41ebe43e7162184d172190e24318af66f7065006a36c2cc877f0e0edd";
    deps = with allCrates; [  all__libc.libc_0_2 all__num_cpus.num_cpus_0_2 ];
  };
  ffmpeg-sys_3_2_0 = buildCratesLib {
    name = "ffmpeg-sys";
    version = "3.2.0";
    hash = "9004a36085eaf4fd250c727c8d6200ef1f8e9307657f84ef59b83334f6f3440f";
    deps = with allCrates; [  all__libc.libc_0_2 all__num_cpus.num_cpus_0_2 ];
  };
  "ffmpeg-sys_2_8" = ffmpeg-sys_2_8_9;
  "ffmpeg-sys_2" = ffmpeg-sys_2_8_9;
  "ffmpeg-sys_3_2" = ffmpeg-sys_3_2_0;
  "ffmpeg-sys_3" = ffmpeg-sys_3_2_0;}