#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  kaws_0_2_0 = buildCratesLib {
    name = "kaws";
    version = "0.2.0";
    hash = "b089f92b09a7abeb475ba2c96154b16cf0a8d47a3e3fb9897787bfe1489a5bd6";
    deps = with allCrates; [  all__rusoto.rusoto_0_16 all__env_logger.env_logger_0_3 all__hyper.hyper_0_9 all__clap.clap_2_9 all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__ansi_term.ansi_term_0_9 ];
  };
  kaws_0_3_0 = buildCratesLib {
    name = "kaws";
    version = "0.3.0";
    hash = "dffc68942574c2477c31cc1e74b4c95c01e1a56a12fedb28c1260aca2615685e";
    deps = with allCrates; [  all__clap.clap_2_9 all__hyper.hyper_0_9 all__rusoto.rusoto_0_16 all__ansi_term.ansi_term_0_9 all__log.log_0_3 all__rustc-serialize.rustc-serialize_0_3 all__env_logger.env_logger_0_3 ];
  };
  "kaws_0_2" = kaws_0_2_0;
  kaws_0_4_1 = buildCratesLib {
    name = "kaws";
    version = "0.4.1";
    hash = "8ec05418881de20ae2c010efb63a1c53e8cb3ebd8ad6b316071e973e2812efca";
    deps = with allCrates; [  all__log.log_0_3 all__clap.clap_2_19 all__rusoto.rusoto_0_20 all__ansi_term.ansi_term_0_9 all__hyper.hyper_0_9 all__rustc-serialize.rustc-serialize_0_3 all__env_logger.env_logger_0_3 ];
  };
  "kaws_0_3" = kaws_0_3_0;
  kaws_0_5_0 = buildCratesLib {
    name = "kaws";
    version = "0.5.0";
    hash = "eefdd327de12f81cda120d983de8dc775475d6d50a907847a56687e07c3c7e03";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__rusoto.rusoto_0_20 all__clap.clap_2_19 all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__ansi_term.ansi_term_0_9 all__env_logger.env_logger_0_3 ];
  };
  "kaws_0_4" = kaws_0_4_1;
  "kaws_0_5" = kaws_0_5_0;
  "kaws_0" = kaws_0_5_0;}