#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rgs_models_0_1_0 = buildCratesLib {
    name = "rgs_models";
    version = "0.1.0";
    hash = "190b635850ed681e97a461d12361e1a227e4bd41b9b9d6f6562db378936020b5";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__serde_derive.serde_derive_0_8 all__iso_country.iso_country_0_1 ];
  };
  rgs_models_0_1_1 = buildCratesLib {
    name = "rgs_models";
    version = "0.1.1";
    hash = "b02a6e5e8cafe1002b10ef2a50209bc46c0b5488f60c73cffee27e02ad035fa6";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__iso_country.iso_country_0_1 all__serde.serde_0_8 all__serde_derive.serde_derive_0_8 ];
  };
  rgs_models_0_2_0 = buildCratesLib {
    name = "rgs_models";
    version = "0.2.0";
    hash = "8dcdd27bae1cc4350fd91bfcd45a87a7c3e2bdcf6bd2ff6088fd6cd78f3d2dbc";
    deps = with allCrates; [  all__serde.serde_0_8 all__serde_derive.serde_derive_0_8 all__iso_country.iso_country_0_1 all__serde_json.serde_json_0_8 ];
  };
  "rgs_models_0_1" = rgs_models_0_1_1;
  "rgs_models_0_2" = rgs_models_0_2_0;
  "rgs_models_0" = rgs_models_0_2_0;}