#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  csvstore_0_1_0 = buildCratesLib {
    name = "csvstore";
    version = "0.1.0";
    hash = "41a2ec6c66f918f1c4669bbe21522410e7bb71f791fa33cc5b64b06e95098489";
    deps = with allCrates; [  all__walkdir.walkdir_1 all__rustc-serialize.rustc-serialize_0_3 all__csv.csv_0_15 ];
  };
  "csvstore_0_1" = csvstore_0_1_0;
  "csvstore_0" = csvstore_0_1_0;}