#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  bart_derive_0_0_1 = buildCratesLib {
    name = "bart_derive";
    version = "0.0.1";
    hash = "fdfebbc80094de63aa205f1696ec2bec5fc0b9d56dd9e84d5f394dabf04ac074";
    deps = with allCrates; [  all__quick-error.quick-error_1_1 all__nom.nom_2_0_1 all__quote.quote_0_3 all__syn.syn_0_10 ];
  };
  "bart_derive_0_0" = bart_derive_0_0_1;
  "bart_derive_0" = bart_derive_0_0_1;}