#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ssdp_0_1_0 = buildCratesLib {
    name = "ssdp";
    version = "0.1.0";
    hash = "2ad39c870504d8c011b8e990c12e1c519415524e33c82ee2c728fe8cad23938e";
    deps = with allCrates; [  libc hyper log time ];
  };
  ssdp_0_1_1 = buildCratesLib {
    name = "ssdp";
    version = "0.1.1";
    hash = "49738f7bf65f0d90edbba3868710df6fd9fd8952804ddfec102293b81e148693";
    deps = with allCrates; [  libc log hyper time ];
  };
  ssdp_0_1_2 = buildCratesLib {
    name = "ssdp";
    version = "0.1.2";
    hash = "c5b76c48815d9b4d977a0724b14af10cdab2905ec3f7e01a4b01598d285ee3b8";
    deps = with allCrates; [  all__hyper.hyper_0_6 all__time.time_0_1 all__libc.libc_0_1 all__log.log_0_3 ];
  };
  ssdp_0_1_3 = buildCratesLib {
    name = "ssdp";
    version = "0.1.3";
    hash = "a0b1ac21bbb9e646a9386946a62db7afc8376e2471865e666672710d46392e0e";
    deps = with allCrates; [  all__libc.libc_0_1 all__time.time_0_1 all__hyper.hyper_0_7 all__log.log_0_3 ];
  };
  ssdp_0_1_4 = buildCratesLib {
    name = "ssdp";
    version = "0.1.4";
    hash = "e4fa0d148f977c4bb85bcab2e9e511026ea37cac0e4b7048e7692945f1e03c9a";
    deps = with allCrates; [  all__log.log_0_3 all__libc.libc_0_1 all__hyper.hyper_0_7 all__time.time_0_1 ];
  };
  ssdp_0_1_5 = buildCratesLib {
    name = "ssdp";
    version = "0.1.5";
    hash = "2cb3d18aa1709ba72654b0d9343317ba16e38bfdae184c913824c76e1e55133b";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__log.log_0_3 all__time.time_0_1 all__libc.libc_0_1 ];
  };
  ssdp_0_1_6 = buildCratesLib {
    name = "ssdp";
    version = "0.1.6";
    hash = "16d421c4faf8a42c887ce53530e9b31d032e2aa46f9879168534e05d86d0e237";
    deps = with allCrates; [  all__log.log_0_3 all__time.time_0_1 all__libc.libc_0_1 all__hyper.hyper_0_9 ];
  };
  ssdp_0_2_6 = buildCratesLib {
    name = "ssdp";
    version = "0.2.6";
    hash = "9eac51d4591a3ae990a648239f8f60cb6c46d6e74543b2ec300abd3a231abaab";
    deps = with allCrates; [  all__log.log_0_3 all__time.time_0_1 all__net2.net2_0_2 all__hyper.hyper_0_9 ];
  };
  "ssdp_0_1" = ssdp_0_1_6;
  ssdp_0_3_0 = buildCratesLib {
    name = "ssdp";
    version = "0.3.0";
    hash = "a4aa674bb52f1e7ae7daf7ff91930c670c31327e137a1bcd4505e8b9a0b65247";
    deps = with allCrates; [  all__time.time_0_1 all__net2.net2_0_2 all__log.log_0_3 all__hyper.hyper_0_9 ];
  };
  "ssdp_0_2" = ssdp_0_2_6;
  ssdp_0_3_1 = buildCratesLib {
    name = "ssdp";
    version = "0.3.1";
    hash = "e3d898f2edaf0bee7fb24f927cbf7945a5906dbfc80d1fd33dbf93c33fa445da";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__log.log_0_3 all__time.time_0_1 all__net2.net2_0_2 ];
  };
  ssdp_0_3_2 = buildCratesLib {
    name = "ssdp";
    version = "0.3.2";
    hash = "260761b3b067a0c2110898b9944bd44f82f99abff3793db2afe240d083972a83";
    deps = with allCrates; [  all__net2.net2_0_2 all__hyper.hyper_0_9 all__time.time_0_1 all__log.log_0_3 ];
  };
  ssdp_0_4_0 = buildCratesLib {
    name = "ssdp";
    version = "0.4.0";
    hash = "94dc35d5a6da0147a705db0315fd4bae5d6641ece85956a79498d5f97cfa8043";
    deps = with allCrates; [  all__time.time_0_1 all__log.log_0_3 all__net2.net2_0_2 all__hyper.hyper_0_9 ];
  };
  "ssdp_0_3" = ssdp_0_3_2;
  ssdp_0_5_0 = buildCratesLib {
    name = "ssdp";
    version = "0.5.0";
    hash = "db201bcc109b114af308ed660ae6339b4096505249fc97347c1a5605b6171e7b";
    deps = with allCrates; [  all__net2.net2_0_2 all__error-chain.error-chain_0_7 all__hyper.hyper_0_9 all__log.log_0_3 all__time.time_0_1 ];
  };
  "ssdp_0_4" = ssdp_0_4_0;
  "ssdp_0_5" = ssdp_0_5_0;
  "ssdp_0" = ssdp_0_5_0;}