#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  regex-decode_0_1_0 = buildCratesLib {
    name = "regex-decode";
    version = "0.1.0";
    hash = "030bfc24f24af924f38f36560e32b1fafc7b0c3d4207ca385d0bec384fac2abc";
    deps = with allCrates; [  all__regex.regex_0_1 all__rustc-serialize.rustc-serialize_0_3 all__error-chain.error-chain_0_7 ];
  };
  "regex-decode_0_1" = regex-decode_0_1_0;
  "regex-decode_0" = regex-decode_0_1_0;}