#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rubic_0_1_0 = buildCratesLib {
    name = "rubic";
    version = "0.1.0";
    hash = "f6627384a987d756f95901d3384ae706ba5d5ead348aed157b2620a443885349";
    deps = with allCrates; [  all__error-chain.error-chain_0_7 ];
  };
  "rubic_0_1" = rubic_0_1_0;
  "rubic_0" = rubic_0_1_0;}