#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  way-cooler-bg_0_1_0 = buildCratesLib {
    name = "way-cooler-bg";
    version = "0.1.0";
    hash = "eafd696f6fda38201c7e0e538fcdd285dd86fa4cb0fc1d019f17539045669ec9";
    deps = with allCrates; [  all__tempfile.tempfile_2_1 all__wayland-sys.wayland-sys_0_6 byteorder all__wayland-client.wayland-client_0_6 all__image.image_0_10 all__gtk.gtk_0_1 ];
  };
  "way-cooler-bg_0_1" = way-cooler-bg_0_1_0;
  "way-cooler-bg_0" = way-cooler-bg_0_1_0;}