#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  futures-threadpool_0_0_1 = buildCratesLib {
    name = "futures-threadpool";
    version = "0.0.1";
    hash = "2cb875d15881785778b7f918854bf77f578453d5a888e67ebae7622d79f05d6d";
    deps = with allCrates; [  ];
  };
  futures-threadpool_0_1_0 = buildCratesLib {
    name = "futures-threadpool";
    version = "0.1.0";
    hash = "cc6a9cc013fe9b1d591757dfd53747a110b0b19eabb5cdc4fc695b469bcc5015";
    deps = with allCrates; [  all__futures-spawn.futures-spawn_0_1 all__crossbeam.crossbeam_0_2 all__futures.futures_0_1 all__num_cpus.num_cpus_1_0 ];
  };
  "futures-threadpool_0_0" = futures-threadpool_0_0_1;
  "futures-threadpool_0_1" = futures-threadpool_0_1_0;
  "futures-threadpool_0" = futures-threadpool_0_1_0;}