#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  libmath_0_1_0 = buildCratesLib {
    name = "libmath";
    version = "0.1.0";
    hash = "b3cf44202e43900bb6d66f21b49edec1a4ea1d7cc02f1ad484213ec612f612aa";
    deps = with allCrates; [  all__rand.rand_0_3 ];
  };
  libmath_0_1_1 = buildCratesLib {
    name = "libmath";
    version = "0.1.1";
    hash = "8663f8a382ffc876a12cdcbddd0b19a21f76debd33212cff1e291256efeccb63";
    deps = with allCrates; [  all__rand.rand_0_3 ];
  };
  libmath_0_1_2 = buildCratesLib {
    name = "libmath";
    version = "0.1.2";
    hash = "e594f90d73e8d785cfc6d7567ada5b166771900d29c94ecc90ba767b9ac562f6";
    deps = with allCrates; [  all__rand.rand_0_3 ];
  };
  libmath_0_1_3 = buildCratesLib {
    name = "libmath";
    version = "0.1.3";
    hash = "f38552595728398692eb3923b24e9f9014663d5f26c7c597c004684f7903ea66";
    deps = with allCrates; [  all__rand.rand_0_3 ];
  };
  libmath_0_1_4 = buildCratesLib {
    name = "libmath";
    version = "0.1.4";
    hash = "81f9daadfd4d8c4946fa32071d428cb70e493ab2c55a57a48da5261447d124cf";
    deps = with allCrates; [  all__rand.rand_0_3 ];
  };
  libmath_0_2_0 = buildCratesLib {
    name = "libmath";
    version = "0.2.0";
    hash = "7106862740a3c76312d518470824620f186f2da3e5c4a4fedeafac6d5aabd7dc";
    deps = with allCrates; [  all__rand.rand_0_3 ];
  };
  "libmath_0_1" = libmath_0_1_4;
  "libmath_0_2" = libmath_0_2_0;
  "libmath_0" = libmath_0_2_0;}