#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  hoodlum_0_1_0 = buildCratesLib {
    name = "hoodlum";
    version = "0.1.0";
    hash = "b65e215bd603329d624726d5bb508b0d4d8fdb111ed6bf7233111ac24c00853f";
    deps = with allCrates; [  all__lalrpop-util.lalrpop-util_0_11 all__lalrpop.lalrpop_0_11 ];
  };
  hoodlum_0_2_0 = buildCratesLib {
    name = "hoodlum";
    version = "0.2.0";
    hash = "44bd1444ef4505a40517721bd0dd0a0fbaa3922b742f9a7f57d7d85cc19ac392";
    deps = with allCrates; [  all__hoodlum-parser.hoodlum-parser_0_2 all__lalrpop-util.lalrpop-util_0_11 all__regex.regex_0_1 ];
  };
  "hoodlum_0_1" = hoodlum_0_1_0;
  hoodlum_0_4_0 = buildCratesLib {
    name = "hoodlum";
    version = "0.4.0";
    hash = "85a75026e4406cac5c7b9f27aab89f8e9beaf3e29fde0a1c87872f4b41d58fe1";
    deps = with allCrates; [  all__matches.matches_0_1 all__hoodlum-parser.hoodlum-parser_0_4 all__itertools.itertools_0_5 lazy_static all__lalrpop-util.lalrpop-util_0_11 all__maplit.maplit_0_1 all__clap.clap_2_19 all__regex.regex_0_1 ];
  };
  "hoodlum_0_2" = hoodlum_0_2_0;
  hoodlum_0_5_0 = buildCratesLib {
    name = "hoodlum";
    version = "0.5.0";
    hash = "884c8c2d91d83fc731f1a1e00fe63d08e6907c1a8c5af63625f41e94756f74db";
    deps = with allCrates; [  all__maplit.maplit_0_1 all__regex.regex_0_1 all__itertools.itertools_0_5 all__lalrpop-util.lalrpop-util_0_11 all__matches.matches_0_1 all__hoodlum-parser.hoodlum-parser_0_5 lazy_static all__clap.clap_2_19 ];
  };
  "hoodlum_0_4" = hoodlum_0_4_0;
  "hoodlum_0_5" = hoodlum_0_5_0;
  "hoodlum_0" = hoodlum_0_5_0;}