#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  prompto_0_0_1 = buildCratesLib {
    name = "prompto";
    version = "0.0.1";
    hash = "9470dd688ab9df533b8adf3fb6a3bedabb8ba4f4a49117c29b06a72f6378a63e";
    deps = with allCrates; [  image lazy_static ];
  };
  "prompto_0_0" = prompto_0_0_1;
  "prompto_0" = prompto_0_0_1;}