#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  exif-rs_0_1_0 = buildCratesLib {
    name = "exif-rs";
    version = "0.1.0";
    hash = "6885d5f92c14792251e741b065e5007903ab9ac9c94386ddfccc8c9b64a7c093";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 ];
  };
  "exif-rs_0_1" = exif-rs_0_1_0;
  "exif-rs_0" = exif-rs_0_1_0;}