#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  laser_0_0_1 = buildCratesLib {
    name = "laser";
    version = "0.0.1";
    hash = "ee35a58fdfda311f064a9f86e602ca200112ac3534ae87196fd0cd1fb066d878";
    deps = with allCrates; [  ilda etherdream ];
  };
  "laser_0_0" = laser_0_0_1;
  "laser_0" = laser_0_0_1;}