#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rawpointer_0_1_0 = buildCratesLib {
    name = "rawpointer";
    version = "0.1.0";
    hash = "ebac11a9d2e11f2af219b8b8d833b76b1ea0e054aa0e8d8e9e4cbde353bdf019";
    deps = with allCrates; [  ];
  };
  "rawpointer_0_1" = rawpointer_0_1_0;
  "rawpointer_0" = rawpointer_0_1_0;}