#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  swc-hosts_0_1_0 = buildCratesLib {
    name = "swc-hosts";
    version = "0.1.0";
    hash = "b167a3e622f697e9f73402c6a522cf96ab4fe43c36a10a53374be0178d047739";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__parse-hosts.parse-hosts_0_3 ];
  };
  swc-hosts_0_1_1 = buildCratesLib {
    name = "swc-hosts";
    version = "0.1.1";
    hash = "25d0f872b62e2d2bf8879f162c380fefb9552e7636c933b7911be0ef4d1bbe35";
    deps = with allCrates; [  all__parse-hosts.parse-hosts_0_3 all__hyper.hyper_0_9 ];
  };
  "swc-hosts_0_1" = swc-hosts_0_1_1;
  "swc-hosts_0" = swc-hosts_0_1_1;}