#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  fps_clock_1_0_0 = buildCratesLib {
    name = "fps_clock";
    version = "1.0.0";
    hash = "c927ce813ec3660f4481a37ce01b1fb77c9df9b7f3b5d88da8b3ce7dbab8c4ba";
    deps = with allCrates; [  ];
  };
  "fps_clock_1_0" = fps_clock_1_0_0;
  "fps_clock_1" = fps_clock_1_0_0;}