#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  test-to-vec_0_1_0 = buildCratesLib {
    name = "test-to-vec";
    version = "0.1.0";
    hash = "525181fd8b0b209a6ebdf79f9c949ed94f73dd981214016d614b52c2d7641e5a";
    deps = with allCrates; [  all__nom.nom_2_0_1 ];
  };
  test-to-vec_0_2_0 = buildCratesLib {
    name = "test-to-vec";
    version = "0.2.0";
    hash = "3063ffa2801b7d30f17065efb369ecf142482778733a7c7ad5cc60115ccd8b11";
    deps = with allCrates; [  all__nom.nom_2_0_1 ];
  };
  "test-to-vec_0_1" = test-to-vec_0_1_0;
  test-to-vec_0_3_0 = buildCratesLib {
    name = "test-to-vec";
    version = "0.3.0";
    hash = "802aaf0552513fe38c6b2e0de29dba73d60f719db5fe78839178e80cf54214a2";
    deps = with allCrates; [  all__nom.nom_2_0_1 ];
  };
  "test-to-vec_0_2" = test-to-vec_0_2_0;
  test-to-vec_0_4_0 = buildCratesLib {
    name = "test-to-vec";
    version = "0.4.0";
    hash = "a79a462990f5a6e4649c3c29d56ee139b355c6ebf8607910e04fee2d6396728f";
    deps = with allCrates; [  all__nom.nom_2_0_1 ];
  };
  "test-to-vec_0_3" = test-to-vec_0_3_0;
  test-to-vec_0_4_1 = buildCratesLib {
    name = "test-to-vec";
    version = "0.4.1";
    hash = "8692459b06db816fedfda93e7ff2331d8e54b325d270c16f9d404a6c3e1b4749";
    deps = with allCrates; [  all__nom.nom_2_0_1 ];
  };
  "test-to-vec_0_4" = test-to-vec_0_4_1;
  "test-to-vec_0" = test-to-vec_0_4_1;}