#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  bip_bencode_0_1_0 = buildCratesLib {
    name = "bip_bencode";
    version = "0.1.0";
    hash = "a9ccb74aa170f4d9755d872c5da58fec4fd5add653461b498b724b87162d3687";
    deps = with allCrates; [  ];
  };
  bip_bencode_0_1_1 = buildCratesLib {
    name = "bip_bencode";
    version = "0.1.1";
    hash = "004756298009b59bfc5f6bdafc63c4fb64621239b628c6374c79c09a8eebaf98";
    deps = with allCrates; [  ];
  };
  bip_bencode_0_1_2 = buildCratesLib {
    name = "bip_bencode";
    version = "0.1.2";
    hash = "76e216458136c7c1244a2afe67635a9de382f0526e18799ed59ddb5f11df4235";
    deps = with allCrates; [  ];
  };
  bip_bencode_0_1_3 = buildCratesLib {
    name = "bip_bencode";
    version = "0.1.3";
    hash = "81a1f2c63cbf265fa0a40fd493898f60c0633cd8d819e42fc6748d1080f0e108";
    deps = with allCrates; [  ];
  };
  bip_bencode_0_2_0 = buildCratesLib {
    name = "bip_bencode";
    version = "0.2.0";
    hash = "53ab21b1f1623fd9fd520ac9f790c32af3e7ce5e95e813a3b3573cae20512591";
    deps = with allCrates; [  all__error-chain.error-chain_0_7 ];
  };
  "bip_bencode_0_1" = bip_bencode_0_1_3;
  "bip_bencode_0_2" = bip_bencode_0_2_0;
  "bip_bencode_0" = bip_bencode_0_2_0;}