#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rusty_crc16_0_1_0 = buildCratesLib {
    name = "rusty_crc16";
    version = "0.1.0";
    hash = "8395147b26055c8bc000e2c77c9f5e5d1b9d942be7282b862cb3fd52e9cd126b";
    deps = with allCrates; [  ];
  };
  rusty_crc16_0_1_1 = buildCratesLib {
    name = "rusty_crc16";
    version = "0.1.1";
    hash = "3a7cec3ebacf8905150e0d09c4b0935a7186210b3283569d1b5c357230a57a1e";
    deps = with allCrates; [  ];
  };
  "rusty_crc16_0_1" = rusty_crc16_0_1_1;
  "rusty_crc16_0" = rusty_crc16_0_1_1;}