#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rust-3d_0_3_2 = buildCratesLib {
    name = "rust-3d";
    version = "0.3.2";
    hash = "c16514c4dc51e938b9c043076f5713893301864fb9e19b132b69de7549a043c3";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  "rust-3d_0_3" = rust-3d_0_3_2;
  "rust-3d_0" = rust-3d_0_3_2;}