#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rust_lsp_0_6_0 = buildCratesLib {
    name = "rust_lsp";
    version = "0.6.0";
    hash = "73a89d593f02c0bc254ea3ceb9d8100ae70d00841581b23265f48dfd04260783";
    deps = with allCrates; [  all__log.log_0_3 all__serde_json.serde_json_0_8 all__rustdt_util.rustdt_util_0_2 all__serde.serde_0_8 all__languageserver-types.languageserver-types_0_6 all__rustdt-json_rpc.rustdt-json_rpc_0_3 ];
  };
  rust_lsp_0_6_1 = buildCratesLib {
    name = "rust_lsp";
    version = "0.6.1";
    hash = "4bf8cf188dba1ffaa11109be3f8b1ec04b5744abb5abea7be3488901177ad007";
    deps = with allCrates; [  all__rustdt-json_rpc.rustdt-json_rpc_0_3 all__rustdt_util.rustdt_util_0_2 all__log.log_0_3 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__languageserver-types.languageserver-types_0_6 ];
  };
  "rust_lsp_0_6" = rust_lsp_0_6_1;
  "rust_lsp_0" = rust_lsp_0_6_1;}