#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rustfmt_0_0_1 = buildCratesLib {
    name = "rustfmt";
    version = "0.0.1";
    hash = "be56f5b26700be85ada9c2bf8b9ce71190f6150f2258838a75b9a472555ffae0";
    deps = with allCrates; [  ];
  };
  rustfmt_0_1_0 = buildCratesLib {
    name = "rustfmt";
    version = "0.1.0";
    hash = "12e5c827c9bc41c1c7a2c5638fd088757e9a2d816072fd38c759b9f1f077f1bb";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__unicode-segmentation.unicode-segmentation_0_1 all__getopts.getopts_0_2 all__regex.regex_0_1 all__rustc-serialize.rustc-serialize_0_3 all__toml.toml_0_1 all__syntex_syntax.syntex_syntax_0_23 all__diff.diff_0_1 all__strings.strings_0_0_1 all__log.log_0_3 all__term.term_0_2 ];
  };
  "rustfmt_0_0" = rustfmt_0_0_1;
  rustfmt_0_2_0 = buildCratesLib {
    name = "rustfmt";
    version = "0.2.0";
    hash = "7551cc09e2417b6574483fb8ea3aeadbb3999b426eafdbe455c7ee42883b892c";
    deps = with allCrates; [  all__unicode-segmentation.unicode-segmentation_0_1 all__regex.regex_0_1 all__strings.strings_0_0_1 all__diff.diff_0_1 all__getopts.getopts_0_2 all__log.log_0_3 all__env_logger.env_logger_0_3 all__syntex_syntax.syntex_syntax_0_23 all__rustc-serialize.rustc-serialize_0_3 all__toml.toml_0_1 all__term.term_0_2 ];
  };
  "rustfmt_0_1" = rustfmt_0_1_0;
  rustfmt_0_2_1 = buildCratesLib {
    name = "rustfmt";
    version = "0.2.1";
    hash = "00dc87e6af062be75cec36831ebeecb243007e4667b398441024b98189b975b7";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__getopts.getopts_0_2 all__term.term_0_2 all__rustc-serialize.rustc-serialize_0_3 all__regex.regex_0_1 all__log.log_0_3 all__unicode-segmentation.unicode-segmentation_0_1 all__strings.strings_0_0_1 all__toml.toml_0_1 all__diff.diff_0_1 all__syntex_syntax.syntex_syntax_0_23 ];
  };
  rustfmt_0_3_0 = buildCratesLib {
    name = "rustfmt";
    version = "0.3.0";
    hash = "07204ef01f1adb2d791865d555cee7a6ca6c78427bf2f34de5a946a4531fd520";
    deps = with allCrates; [  all__regex.regex_0_1 all__getopts.getopts_0_2 all__rustc-serialize.rustc-serialize_0_3 all__toml.toml_0_1 all__env_logger.env_logger_0_3 all__log.log_0_3 all__unicode-segmentation.unicode-segmentation_0_1 all__term.term_0_2 all__strings.strings_0_0_1 all__diff.diff_0_1 all__syntex_syntax.syntex_syntax_0_23 ];
  };
  "rustfmt_0_2" = rustfmt_0_2_1;
  rustfmt_0_4_0 = buildCratesLib {
    name = "rustfmt";
    version = "0.4.0";
    hash = "add2143a74d9dde7ddbfdd325ac6f253656662fd3b6c22600e1fa4b52f9eab01";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__syntex_syntax.syntex_syntax_0_30 all__getopts.getopts_0_2 all__env_logger.env_logger_0_3 all__strings.strings_0_0_1 all__toml.toml_0_1 all__unicode-segmentation.unicode-segmentation_0_1 all__term.term_0_2 all__diff.diff_0_1 all__log.log_0_3 all__regex.regex_0_1 ];
  };
  "rustfmt_0_3" = rustfmt_0_3_0;
  rustfmt_0_4_1 = buildCratesLib {
    name = "rustfmt";
    version = "0.4.1";
    hash = "1ce2f8db84b0a1ad705080c1f99ab0db02761577885709eb44a2b3cac4706dbd";
    deps = with allCrates; [  all__unicode-segmentation.unicode-segmentation_0_1 all__log.log_0_3 all__syntex_syntax.syntex_syntax_0_30 all__rustc-serialize.rustc-serialize_0_3 all__diff.diff_0_1 all__regex.regex_0_1 all__strings.strings_0_0_1 all__term.term_0_4 all__getopts.getopts_0_2 all__toml.toml_0_1 all__env_logger.env_logger_0_3 ];
  };
  rustfmt_0_5_0 = buildCratesLib {
    name = "rustfmt";
    version = "0.5.0";
    hash = "c2d860213f6e653527de316bdd9bf4fa821cc3c3b052540885a26653e7a77288";
    deps = with allCrates; [  all__getopts.getopts_0_2 all__term.term_0_4 all__toml.toml_0_1 all__log.log_0_3 all__diff.diff_0_1 all__rustc-serialize.rustc-serialize_0_3 all__regex.regex_0_1 all__unicode-segmentation.unicode-segmentation_0_1 all__strings.strings_0_0_1 all__syntex_syntax.syntex_syntax_0_32 all__env_logger.env_logger_0_3 ];
  };
  "rustfmt_0_4" = rustfmt_0_4_1;
  rustfmt_0_6_0 = buildCratesLib {
    name = "rustfmt";
    version = "0.6.0";
    hash = "fdd0bd76e71df05286afda72f517d1661895f49f1e082afd499864c70afb792e";
    deps = with allCrates; [  all__getopts.getopts_0_2 all__diff.diff_0_1 all__toml.toml_0_1 all__env_logger.env_logger_0_3 all__regex.regex_0_1 all__rustc-serialize.rustc-serialize_0_3 all__unicode-segmentation.unicode-segmentation_0_1 all__log.log_0_3 all__syntex_syntax.syntex_syntax_0_33 all__strings.strings_0_0_1 all__itertools.itertools_0_4 all__term.term_0_4 all__multimap.multimap_0_3 all__walkdir.walkdir_0_1 all__libc.libc_0_2 ];
  };
  "rustfmt_0_5" = rustfmt_0_5_0;
  rustfmt_0_6_1 = buildCratesLib {
    name = "rustfmt";
    version = "0.6.1";
    hash = "8c5bcf74599c60e361f39c91d7cddd12b9effc2360ee61a8d90924721f75550d";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__unicode-segmentation.unicode-segmentation_0_1 all__term.term_0_4 all__rustc-serialize.rustc-serialize_0_3 all__itertools.itertools_0_4 all__syntex_syntax.syntex_syntax_0_43 all__log.log_0_3 all__strings.strings_0_0_1 all__syntex_errors.syntex_errors_0_43 all__toml.toml_0_1 all__multimap.multimap_0_3 all__regex.regex_0_1 all__diff.diff_0_1 all__getopts.getopts_0_2 all__walkdir.walkdir_0_1 all__libc.libc_0_2 ];
  };
  rustfmt_0_6_2 = buildCratesLib {
    name = "rustfmt";
    version = "0.6.2";
    hash = "f942beb83e9bc352bb5920dccf5be2a66a4596577e85331591fc7827e7d07b97";
    deps = with allCrates; [  all__itertools.itertools_0_4 all__term.term_0_4 all__unicode-segmentation.unicode-segmentation_0_1 all__log.log_0_3 all__toml.toml_0_1 all__syntex_syntax.syntex_syntax_0_43 all__getopts.getopts_0_2 all__rustc-serialize.rustc-serialize_0_3 all__strings.strings_0_0_1 all__env_logger.env_logger_0_3 all__syntex_errors.syntex_errors_0_43 all__multimap.multimap_0_3 all__regex.regex_0_1 all__diff.diff_0_1 all__walkdir.walkdir_0_1 all__libc.libc_0_2 ];
  };
  rustfmt_0_6_3 = buildCratesLib {
    name = "rustfmt";
    version = "0.6.3";
    hash = "21a36236a22925a6057ea1025152584bc750a61051cf5f885cb5299788d76f17";
    deps = with allCrates; [  all__strings.strings_0_0_1 all__itertools.itertools_0_4 all__syntex_syntax.syntex_syntax_0_44 all__toml.toml_0_1 all__unicode-segmentation.unicode-segmentation_0_1 all__getopts.getopts_0_2 all__rustc-serialize.rustc-serialize_0_3 all__regex.regex_0_1 all__term.term_0_4 all__syntex_errors.syntex_errors_0_44 all__diff.diff_0_1 all__log.log_0_3 all__env_logger.env_logger_0_3 all__multimap.multimap_0_3 all__walkdir.walkdir_0_1 all__libc.libc_0_2 ];
  };
  "rustfmt_0_6" = rustfmt_0_6_3;
  "rustfmt_0" = rustfmt_0_6_3;}