#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rustyhub_0_2_0 = buildCratesLib {
    name = "rustyhub";
    version = "0.2.0";
    hash = "72882cc0db1fc95af3b9beaf4db1aaa8244d673e262e6c116aa924ccdf5beffe";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__log.log_0_3 all__serde.serde_0_8 all__serde_derive.serde_derive_0_8 all__serde_json.serde_json_0_8 ];
  };
  rustyhub_0_3_0 = buildCratesLib {
    name = "rustyhub";
    version = "0.3.0";
    hash = "38a64395083028e1599a2934e7655c85d73be1cc1cb8d872a26ce5c9dc3d386b";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__hyper.hyper_0_9 all__serde_derive.serde_derive_0_8 all__log.log_0_3 ];
  };
  "rustyhub_0_2" = rustyhub_0_2_0;
  "rustyhub_0_3" = rustyhub_0_3_0;
  "rustyhub_0" = rustyhub_0_3_0;}